package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_abs kernel
var unary_abs_code cu.Function

// Stores the arguments for unary_abs kernel invocation
type unary_abs_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_abs kernel invocation
var unary_abs_args unary_abs_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_abs_args.argptr[0] = unsafe.Pointer(&unary_abs_args.arg_dst)
	 unary_abs_args.argptr[1] = unsafe.Pointer(&unary_abs_args.arg_a)
	 unary_abs_args.argptr[2] = unsafe.Pointer(&unary_abs_args.arg_N)
	 }

// Wrapper for unary_abs CUDA kernel, asynchronous.
func k_unary_abs_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_abs")
	}

	unary_abs_args.Lock()
	defer unary_abs_args.Unlock()

	if unary_abs_code == 0{
		unary_abs_code = fatbinLoad(unary_abs_map, "unary_abs")
	}

	 unary_abs_args.arg_dst = dst
	 unary_abs_args.arg_a = a
	 unary_abs_args.arg_N = N
	

	args := unary_abs_args.argptr[:]
	cu.LaunchKernel(unary_abs_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_abs")
	}
}

// maps compute capability on PTX code for unary_abs kernel.
var unary_abs_map = map[int]string{ 0: "" ,
61: unary_abs_ptx_61  }

// unary_abs PTX code for various compute capabilities.
const(
  unary_abs_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_abs

.visible .entry unary_abs(
	.param .u64 unary_abs_param_0,
	.param .u64 unary_abs_param_1,
	.param .u32 unary_abs_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [unary_abs_param_0];
	ld.param.u64 	%rd2, [unary_abs_param_1];
	ld.param.u32 	%r2, [unary_abs_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f2, %f1;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f2;

$L__BB0_2:
	ret;

}

`
 )
