package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_acos kernel
var unary_acos_code cu.Function

// Stores the arguments for unary_acos kernel invocation
type unary_acos_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_acos kernel invocation
var unary_acos_args unary_acos_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_acos_args.argptr[0] = unsafe.Pointer(&unary_acos_args.arg_dst)
	 unary_acos_args.argptr[1] = unsafe.Pointer(&unary_acos_args.arg_a)
	 unary_acos_args.argptr[2] = unsafe.Pointer(&unary_acos_args.arg_N)
	 }

// Wrapper for unary_acos CUDA kernel, asynchronous.
func k_unary_acos_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_acos")
	}

	unary_acos_args.Lock()
	defer unary_acos_args.Unlock()

	if unary_acos_code == 0{
		unary_acos_code = fatbinLoad(unary_acos_map, "unary_acos")
	}

	 unary_acos_args.arg_dst = dst
	 unary_acos_args.arg_a = a
	 unary_acos_args.arg_N = N
	

	args := unary_acos_args.argptr[:]
	cu.LaunchKernel(unary_acos_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_acos")
	}
}

// maps compute capability on PTX code for unary_acos kernel.
var unary_acos_map = map[int]string{ 0: "" ,
61: unary_acos_ptx_61  }

// unary_acos PTX code for various compute capabilities.
const(
  unary_acos_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_acos

.visible .entry unary_acos(
	.param .u64 unary_acos_param_0,
	.param .u64 unary_acos_param_1,
	.param .u32 unary_acos_param_2
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<40>;
	.reg .b32 	%r<13>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [unary_acos_param_0];
	ld.param.u64 	%rd3, [unary_acos_param_1];
	ld.param.u32 	%r2, [unary_acos_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.ltu.f32 	%p2, %f1, 0fBF800000;
	setp.gtu.f32 	%p3, %f1, 0f3F800000;
	or.pred  	%p4, %p2, %p3;
	mov.f32 	%f39, 0f00000000;
	@%p4 bra 	$L__BB0_3;

	abs.f32 	%f5, %f1;
	neg.f32 	%f6, %f5;
	mov.f32 	%f7, 0f3F000000;
	fma.rn.f32 	%f8, %f7, %f6, %f7;
	rsqrt.approx.ftz.f32 	%f9, %f8;
	mul.f32 	%f10, %f8, %f9;
	mul.f32 	%f11, %f9, 0f3F000000;
	neg.f32 	%f12, %f10;
	fma.rn.f32 	%f13, %f12, %f11, %f7;
	fma.rn.f32 	%f14, %f10, %f13, %f10;
	setp.eq.f32 	%p5, %f5, 0f3F800000;
	selp.f32 	%f15, 0f00000000, %f14, %p5;
	setp.gt.f32 	%p6, %f5, 0f3F0F5C29;
	selp.f32 	%f16, %f15, %f5, %p6;
	mov.b32 	%r9, %f16;
	mov.b32 	%r10, %f1;
	and.b32  	%r11, %r10, -2147483648;
	or.b32  	%r12, %r11, %r9;
	mov.b32 	%f17, %r12;
	mul.f32 	%f18, %f17, %f17;
	mov.f32 	%f19, 0f3C8B1ABB;
	mov.f32 	%f20, 0f3D10ECEF;
	fma.rn.f32 	%f21, %f20, %f18, %f19;
	mov.f32 	%f22, 0f3CFC028C;
	fma.rn.f32 	%f23, %f21, %f18, %f22;
	mov.f32 	%f24, 0f3D372139;
	fma.rn.f32 	%f25, %f23, %f18, %f24;
	mov.f32 	%f26, 0f3D9993DB;
	fma.rn.f32 	%f27, %f25, %f18, %f26;
	mov.f32 	%f28, 0f3E2AAAC6;
	fma.rn.f32 	%f29, %f27, %f18, %f28;
	mul.f32 	%f30, %f29, %f18;
	fma.rn.f32 	%f31, %f30, %f17, %f17;
	neg.f32 	%f32, %f31;
	selp.f32 	%f33, %f31, %f32, %p6;
	mov.f32 	%f34, 0f3FD774EB;
	mov.f32 	%f35, 0f3F6EE581;
	fma.rn.f32 	%f36, %f35, %f34, %f33;
	setp.gt.f32 	%p7, %f1, 0f3F0F5C29;
	selp.f32 	%f37, %f31, %f36, %p7;
	add.f32 	%f38, %f37, %f37;
	selp.f32 	%f39, %f38, %f37, %p6;

$L__BB0_3:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f39;

$L__BB0_4:
	ret;

}

`
 )
