package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_acos kernel
var unary_acos_code cu.Function

// Stores the arguments for unary_acos kernel invocation
type unary_acos_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_acos kernel invocation
var unary_acos_args unary_acos_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_acos_args.argptr[0] = unsafe.Pointer(&unary_acos_args.arg_dst)
	 unary_acos_args.argptr[1] = unsafe.Pointer(&unary_acos_args.arg_a)
	 unary_acos_args.argptr[2] = unsafe.Pointer(&unary_acos_args.arg_N)
	 }

// Wrapper for unary_acos CUDA kernel, asynchronous.
func k_unary_acos_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_acos")
	}

	unary_acos_args.Lock()
	defer unary_acos_args.Unlock()

	if unary_acos_code == 0{
		unary_acos_code = fatbinLoad(unary_acos_map, "unary_acos")
	}

	 unary_acos_args.arg_dst = dst
	 unary_acos_args.arg_a = a
	 unary_acos_args.arg_N = N
	

	args := unary_acos_args.argptr[:]
	cu.LaunchKernel(unary_acos_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_acos")
	}
}

// maps compute capability on PTX code for unary_acos kernel.
var unary_acos_map = map[int]string{ 0: "" ,
61: unary_acos_ptx_61  }

// unary_acos PTX code for various compute capabilities.
const(
  unary_acos_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_acos

.visible .entry unary_acos(
	.param .u64 unary_acos_param_0,
	.param .u64 unary_acos_param_1,
	.param .u32 unary_acos_param_2
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<37>;
	.reg .b32 	%r<13>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [unary_acos_param_0];
	ld.param.u64 	%rd2, [unary_acos_param_1];
	ld.param.u32 	%r2, [unary_acos_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f2, %f1;
	neg.f32 	%f3, %f2;
	mov.f32 	%f4, 0f3F000000;
	fma.rn.f32 	%f5, %f4, %f3, %f4;
	rsqrt.approx.ftz.f32 	%f6, %f5;
	mul.f32 	%f7, %f5, %f6;
	mul.f32 	%f8, %f6, 0f3F000000;
	neg.f32 	%f9, %f7;
	fma.rn.f32 	%f10, %f9, %f8, %f4;
	fma.rn.f32 	%f11, %f7, %f10, %f7;
	setp.eq.f32 	%p2, %f2, 0f3F800000;
	selp.f32 	%f12, 0f00000000, %f11, %p2;
	setp.gt.f32 	%p3, %f2, 0f3F0F5C29;
	selp.f32 	%f13, %f12, %f2, %p3;
	mov.b32 	%r9, %f13;
	mov.b32 	%r10, %f1;
	and.b32  	%r11, %r10, -2147483648;
	or.b32  	%r12, %r11, %r9;
	mov.b32 	%f14, %r12;
	mul.f32 	%f15, %f14, %f14;
	mov.f32 	%f16, 0f3C8B1ABB;
	mov.f32 	%f17, 0f3D10ECEF;
	fma.rn.f32 	%f18, %f17, %f15, %f16;
	mov.f32 	%f19, 0f3CFC028C;
	fma.rn.f32 	%f20, %f18, %f15, %f19;
	mov.f32 	%f21, 0f3D372139;
	fma.rn.f32 	%f22, %f20, %f15, %f21;
	mov.f32 	%f23, 0f3D9993DB;
	fma.rn.f32 	%f24, %f22, %f15, %f23;
	mov.f32 	%f25, 0f3E2AAAC6;
	fma.rn.f32 	%f26, %f24, %f15, %f25;
	mul.f32 	%f27, %f26, %f15;
	fma.rn.f32 	%f28, %f27, %f14, %f14;
	neg.f32 	%f29, %f28;
	selp.f32 	%f30, %f28, %f29, %p3;
	mov.f32 	%f31, 0f3FD774EB;
	mov.f32 	%f32, 0f3F6EE581;
	fma.rn.f32 	%f33, %f32, %f31, %f30;
	setp.gt.f32 	%p4, %f1, 0f3F0F5C29;
	selp.f32 	%f34, %f28, %f33, %p4;
	add.f32 	%f35, %f34, %f34;
	selp.f32 	%f36, %f35, %f34, %p3;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f36;

$L__BB0_2:
	ret;

}

`
 )
