package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_asin kernel
var unary_asin_code cu.Function

// Stores the arguments for unary_asin kernel invocation
type unary_asin_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_asin kernel invocation
var unary_asin_args unary_asin_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_asin_args.argptr[0] = unsafe.Pointer(&unary_asin_args.arg_dst)
	 unary_asin_args.argptr[1] = unsafe.Pointer(&unary_asin_args.arg_a)
	 unary_asin_args.argptr[2] = unsafe.Pointer(&unary_asin_args.arg_N)
	 }

// Wrapper for unary_asin CUDA kernel, asynchronous.
func k_unary_asin_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_asin")
	}

	unary_asin_args.Lock()
	defer unary_asin_args.Unlock()

	if unary_asin_code == 0{
		unary_asin_code = fatbinLoad(unary_asin_map, "unary_asin")
	}

	 unary_asin_args.arg_dst = dst
	 unary_asin_args.arg_a = a
	 unary_asin_args.arg_N = N
	

	args := unary_asin_args.argptr[:]
	cu.LaunchKernel(unary_asin_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_asin")
	}
}

// maps compute capability on PTX code for unary_asin kernel.
var unary_asin_map = map[int]string{ 0: "" ,
61: unary_asin_ptx_61  }

// unary_asin PTX code for various compute capabilities.
const(
  unary_asin_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_asin

.visible .entry unary_asin(
	.param .u64 unary_asin_param_0,
	.param .u64 unary_asin_param_1,
	.param .u32 unary_asin_param_2
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<36>;
	.reg .b32 	%r<13>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [unary_asin_param_0];
	ld.param.u64 	%rd3, [unary_asin_param_1];
	ld.param.u32 	%r2, [unary_asin_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.ltu.f32 	%p2, %f1, 0fBF800000;
	setp.gtu.f32 	%p3, %f1, 0f3F800000;
	or.pred  	%p4, %p2, %p3;
	mov.f32 	%f35, 0f00000000;
	@%p4 bra 	$L__BB0_3;

	abs.f32 	%f5, %f1;
	neg.f32 	%f6, %f5;
	mov.f32 	%f7, 0f3F000000;
	fma.rn.f32 	%f8, %f7, %f6, %f7;
	rsqrt.approx.ftz.f32 	%f9, %f8;
	mul.f32 	%f10, %f8, %f9;
	mul.f32 	%f11, %f9, 0f3F000000;
	neg.f32 	%f12, %f10;
	fma.rn.f32 	%f13, %f12, %f11, %f7;
	fma.rn.f32 	%f14, %f10, %f13, %f10;
	setp.eq.f32 	%p5, %f5, 0f3F800000;
	selp.f32 	%f15, 0f00000000, %f14, %p5;
	setp.gt.f32 	%p6, %f5, 0f3F0F5C29;
	selp.f32 	%f16, %f15, %f5, %p6;
	mul.f32 	%f17, %f16, %f16;
	mov.f32 	%f18, 0f3C99CA97;
	mov.f32 	%f19, 0f3D4DD2F7;
	fma.rn.f32 	%f20, %f19, %f17, %f18;
	mov.f32 	%f21, 0f3D3F90E8;
	fma.rn.f32 	%f22, %f20, %f17, %f21;
	mov.f32 	%f23, 0f3D993CCF;
	fma.rn.f32 	%f24, %f22, %f17, %f23;
	mov.f32 	%f25, 0f3E2AAC04;
	fma.rn.f32 	%f26, %f24, %f17, %f25;
	mul.f32 	%f27, %f17, %f26;
	fma.rn.f32 	%f28, %f27, %f16, %f16;
	mul.f32 	%f29, %f28, 0fC0000000;
	mov.f32 	%f30, 0f3FD774EB;
	mov.f32 	%f31, 0f3F6EE581;
	fma.rn.f32 	%f32, %f31, %f30, %f29;
	selp.f32 	%f33, %f32, %f28, %p6;
	setp.le.f32 	%p7, %f33, 0f7F800000;
	mov.b32 	%r9, %f33;
	mov.b32 	%r10, %f1;
	and.b32  	%r11, %r10, -2147483648;
	or.b32  	%r12, %r11, %r9;
	mov.b32 	%f34, %r12;
	selp.f32 	%f35, %f34, %f33, %p7;

$L__BB0_3:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f35;

$L__BB0_4:
	ret;

}

`
 )
