package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_atan kernel
var unary_atan_code cu.Function

// Stores the arguments for unary_atan kernel invocation
type unary_atan_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_atan kernel invocation
var unary_atan_args unary_atan_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_atan_args.argptr[0] = unsafe.Pointer(&unary_atan_args.arg_dst)
	 unary_atan_args.argptr[1] = unsafe.Pointer(&unary_atan_args.arg_a)
	 unary_atan_args.argptr[2] = unsafe.Pointer(&unary_atan_args.arg_N)
	 }

// Wrapper for unary_atan CUDA kernel, asynchronous.
func k_unary_atan_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_atan")
	}

	unary_atan_args.Lock()
	defer unary_atan_args.Unlock()

	if unary_atan_code == 0{
		unary_atan_code = fatbinLoad(unary_atan_map, "unary_atan")
	}

	 unary_atan_args.arg_dst = dst
	 unary_atan_args.arg_a = a
	 unary_atan_args.arg_N = N
	

	args := unary_atan_args.argptr[:]
	cu.LaunchKernel(unary_atan_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_atan")
	}
}

// maps compute capability on PTX code for unary_atan kernel.
var unary_atan_map = map[int]string{ 0: "" ,
61: unary_atan_ptx_61  }

// unary_atan PTX code for various compute capabilities.
const(
  unary_atan_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_atan

.visible .entry unary_atan(
	.param .u64 unary_atan_param_0,
	.param .u64 unary_atan_param_1,
	.param .u32 unary_atan_param_2
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<20>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [unary_atan_param_0];
	ld.param.u64 	%rd2, [unary_atan_param_1];
	ld.param.u32 	%r2, [unary_atan_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f2, %f1;
	setp.leu.f32 	%p2, %f2, 0f3F800000;
	setp.gt.f32 	%p3, %f2, 0f3F800000;
	rcp.approx.ftz.f32 	%f6, %f2;
	selp.f32 	%f7, %f6, %f2, %p3;
	mul.f32 	%f8, %f7, %f7;
	mov.f32 	%f9, 0fBC6BE14F;
	mov.f32 	%f10, 0f3B2090AA;
	fma.rn.f32 	%f11, %f10, %f8, %f9;
	mov.f32 	%f12, 0f3D23397E;
	fma.rn.f32 	%f13, %f11, %f8, %f12;
	mov.f32 	%f14, 0fBD948A7A;
	fma.rn.f32 	%f15, %f13, %f8, %f14;
	mov.f32 	%f16, 0f3DD76B21;
	fma.rn.f32 	%f17, %f15, %f8, %f16;
	mov.f32 	%f18, 0fBE111E88;
	fma.rn.f32 	%f19, %f17, %f8, %f18;
	mov.f32 	%f20, 0f3E4CAF60;
	fma.rn.f32 	%f21, %f19, %f8, %f20;
	mov.f32 	%f22, 0fBEAAAA27;
	fma.rn.f32 	%f23, %f21, %f8, %f22;
	mul.f32 	%f24, %f8, %f23;
	fma.rn.f32 	%f30, %f24, %f7, %f7;
	@%p2 bra 	$L__BB0_3;

	neg.f32 	%f25, %f30;
	mov.f32 	%f26, 0f3FD774EB;
	mov.f32 	%f27, 0f3F6EE581;
	fma.rn.f32 	%f30, %f27, %f26, %f25;

$L__BB0_3:
	mov.b32 	%r9, %f1;
	and.b32  	%r10, %r9, -2147483648;
	mov.b32 	%r11, %f30;
	or.b32  	%r12, %r10, %r11;
	mov.b32 	%f28, %r12;
	setp.le.f32 	%p4, %f2, 0f7F800000;
	selp.f32 	%f29, %f28, %f30, %p4;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd8, %rd6, %rd4;
	st.global.f32 	[%rd8], %f29;

$L__BB0_4:
	ret;

}

`
 )
