package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_atanh kernel
var unary_atanh_code cu.Function

// Stores the arguments for unary_atanh kernel invocation
type unary_atanh_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_atanh kernel invocation
var unary_atanh_args unary_atanh_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_atanh_args.argptr[0] = unsafe.Pointer(&unary_atanh_args.arg_dst)
	 unary_atanh_args.argptr[1] = unsafe.Pointer(&unary_atanh_args.arg_a)
	 unary_atanh_args.argptr[2] = unsafe.Pointer(&unary_atanh_args.arg_N)
	 }

// Wrapper for unary_atanh CUDA kernel, asynchronous.
func k_unary_atanh_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_atanh")
	}

	unary_atanh_args.Lock()
	defer unary_atanh_args.Unlock()

	if unary_atanh_code == 0{
		unary_atanh_code = fatbinLoad(unary_atanh_map, "unary_atanh")
	}

	 unary_atanh_args.arg_dst = dst
	 unary_atanh_args.arg_a = a
	 unary_atanh_args.arg_N = N
	

	args := unary_atanh_args.argptr[:]
	cu.LaunchKernel(unary_atanh_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_atanh")
	}
}

// maps compute capability on PTX code for unary_atanh kernel.
var unary_atanh_map = map[int]string{ 0: "" ,
61: unary_atanh_ptx_61  }

// unary_atanh PTX code for various compute capabilities.
const(
  unary_atanh_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_atanh

.visible .entry unary_atanh(
	.param .u64 unary_atanh_param_0,
	.param .u64 unary_atanh_param_1,
	.param .u32 unary_atanh_param_2
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<50>;
	.reg .b32 	%r<27>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [unary_atanh_param_0];
	ld.param.u64 	%rd2, [unary_atanh_param_1];
	ld.param.u32 	%r3, [unary_atanh_param_2];
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %nctaid.x;
	mov.u32 	%r6, %ctaid.x;
	mad.lo.s32 	%r7, %r4, %r5, %r6;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	setp.ge.s32 	%p1, %r1, %r3;
	@%p1 bra 	$L__BB0_6;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f8, %f1;
	mov.f32 	%f9, 0f3F800000;
	sub.f32 	%f10, %f9, %f8;
	rcp.approx.ftz.f32 	%f11, %f10;
	add.f32 	%f12, %f11, %f11;
	mul.f32 	%f13, %f8, %f12;
	setp.gt.f32 	%p2, %f8, 0f7E800000;
	selp.f32 	%f2, 0fC0000000, %f13, %p2;
	add.rz.f32 	%f14, %f2, %f9;
	mov.b32 	%r10, %f14;
	add.s32 	%r11, %r10, -1061158912;
	and.b32  	%r12, %r11, -8388608;
	mov.b32 	%r2, %f2;
	sub.s32 	%r13, %r2, %r12;
	mov.b32 	%f15, %r13;
	mov.u32 	%r14, 1082130432;
	sub.s32 	%r15, %r14, %r12;
	mov.b32 	%f16, %r15;
	mov.f32 	%f17, 0fBF800000;
	mov.f32 	%f18, 0f3E800000;
	fma.rn.f32 	%f19, %f18, %f16, %f17;
	add.f32 	%f20, %f19, %f15;
	cvt.rn.f32.s32 	%f21, %r12;
	mul.f32 	%f22, %f21, 0f34000000;
	mov.f32 	%f23, 0f3DD80012;
	mov.f32 	%f24, 0fBD39BF78;
	fma.rn.f32 	%f25, %f24, %f20, %f23;
	mov.f32 	%f26, 0fBE0778E0;
	fma.rn.f32 	%f27, %f25, %f20, %f26;
	mov.f32 	%f28, 0f3E146475;
	fma.rn.f32 	%f29, %f27, %f20, %f28;
	mov.f32 	%f30, 0fBE2A68DD;
	fma.rn.f32 	%f31, %f29, %f20, %f30;
	mov.f32 	%f32, 0f3E4CAF9E;
	fma.rn.f32 	%f33, %f31, %f20, %f32;
	mov.f32 	%f34, 0fBE800042;
	fma.rn.f32 	%f35, %f33, %f20, %f34;
	mov.f32 	%f36, 0f3EAAAAE6;
	fma.rn.f32 	%f37, %f35, %f20, %f36;
	mov.f32 	%f38, 0fBF000000;
	fma.rn.f32 	%f39, %f37, %f20, %f38;
	mul.f32 	%f40, %f20, %f39;
	fma.rn.f32 	%f41, %f40, %f20, %f20;
	mov.f32 	%f42, 0f3F317218;
	fma.rn.f32 	%f48, %f22, %f42, %f41;
	setp.lt.u32 	%p3, %r2, 2139095040;
	@%p3 bra 	$L__BB0_5;

	setp.lt.s32 	%p4, %r2, -1082130431;
	@%p4 bra 	$L__BB0_4;

	mov.f32 	%f43, 0f7F800000;
	fma.rn.f32 	%f48, %f2, %f43, %f43;

$L__BB0_4:
	setp.eq.f32 	%p5, %f2, 0f00000000;
	selp.f32 	%f48, 0f80000000, %f48, %p5;

$L__BB0_5:
	mul.f32 	%f44, %f48, 0f3F000000;
	abs.f32 	%f45, %f44;
	setp.le.f32 	%p6, %f45, 0f7F800000;
	mov.b32 	%r16, %f44;
	mov.b32 	%r17, %f1;
	and.b32  	%r18, %r17, -2147483648;
	or.b32  	%r19, %r18, %r16;
	mov.b32 	%f46, %r19;
	selp.f32 	%f47, %f46, %f44, %p6;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd8, %rd6, %rd4;
	st.global.f32 	[%rd8], %f47;

$L__BB0_6:
	ret;

}

`
 )
