package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgBuildMsV kernel
var cgBuildMsV_code cu.Function

// Stores the arguments for cgBuildMsV kernel invocation
type cgBuildMsV_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_msArr unsafe.Pointer
	 arg_msMul float32
	 arg_scale float32
	 arg_N int
	 argptr [5]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgBuildMsV kernel invocation
var cgBuildMsV_args cgBuildMsV_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgBuildMsV_args.argptr[0] = unsafe.Pointer(&cgBuildMsV_args.arg_dst)
	 cgBuildMsV_args.argptr[1] = unsafe.Pointer(&cgBuildMsV_args.arg_msArr)
	 cgBuildMsV_args.argptr[2] = unsafe.Pointer(&cgBuildMsV_args.arg_msMul)
	 cgBuildMsV_args.argptr[3] = unsafe.Pointer(&cgBuildMsV_args.arg_scale)
	 cgBuildMsV_args.argptr[4] = unsafe.Pointer(&cgBuildMsV_args.arg_N)
	 }

// Wrapper for cgBuildMsV CUDA kernel, asynchronous.
func k_cgBuildMsV_async ( dst unsafe.Pointer, msArr unsafe.Pointer, msMul float32, scale float32, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgBuildMsV")
	}

	cgBuildMsV_args.Lock()
	defer cgBuildMsV_args.Unlock()

	if cgBuildMsV_code == 0{
		cgBuildMsV_code = fatbinLoad(cgBuildMsV_map, "cgBuildMsV")
	}

	 cgBuildMsV_args.arg_dst = dst
	 cgBuildMsV_args.arg_msArr = msArr
	 cgBuildMsV_args.arg_msMul = msMul
	 cgBuildMsV_args.arg_scale = scale
	 cgBuildMsV_args.arg_N = N
	

	args := cgBuildMsV_args.argptr[:]
	cu.LaunchKernel(cgBuildMsV_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgBuildMsV")
	}
}

// maps compute capability on PTX code for cgBuildMsV kernel.
var cgBuildMsV_map = map[int]string{ 0: "" ,
61: cgBuildMsV_ptx_61  }

// cgBuildMsV PTX code for various compute capabilities.
const(
  cgBuildMsV_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgBuildMsV

.visible .entry cgBuildMsV(
	.param .u64 cgBuildMsV_param_0,
	.param .u64 cgBuildMsV_param_1,
	.param .f32 cgBuildMsV_param_2,
	.param .f32 cgBuildMsV_param_3,
	.param .u32 cgBuildMsV_param_4
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [cgBuildMsV_param_0];
	ld.param.u64 	%rd2, [cgBuildMsV_param_1];
	ld.param.f32 	%f7, [cgBuildMsV_param_2];
	ld.param.f32 	%f4, [cgBuildMsV_param_3];
	ld.param.u32 	%r2, [cgBuildMsV_param_4];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	setp.eq.s64 	%p2, %rd2, 0;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.f32 	%f5, [%rd5];
	mul.f32 	%f7, %f5, %f7;

$L__BB0_3:
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	mul.f32 	%f6, %f7, %f4;
	st.global.f32 	[%rd8], %f6;

$L__BB0_4:
	ret;

}

`
 )
