package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgEpAndGradSq kernel
var cgEpAndGradSq_code cu.Function

// Stores the arguments for cgEpAndGradSq kernel invocation
type cgEpAndGradSq_args_t struct{
	 arg_g_ep unsafe.Pointer
	 arg_g_gsq unsafe.Pointer
	 arg_mhx unsafe.Pointer
	 arg_mhy unsafe.Pointer
	 arg_mhz unsafe.Pointer
	 arg_dirx unsafe.Pointer
	 arg_diry unsafe.Pointer
	 arg_dirz unsafe.Pointer
	 arg_ms unsafe.Pointer
	 arg_tsq float32
	 arg_N int
	 argptr [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgEpAndGradSq kernel invocation
var cgEpAndGradSq_args cgEpAndGradSq_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgEpAndGradSq_args.argptr[0] = unsafe.Pointer(&cgEpAndGradSq_args.arg_g_ep)
	 cgEpAndGradSq_args.argptr[1] = unsafe.Pointer(&cgEpAndGradSq_args.arg_g_gsq)
	 cgEpAndGradSq_args.argptr[2] = unsafe.Pointer(&cgEpAndGradSq_args.arg_mhx)
	 cgEpAndGradSq_args.argptr[3] = unsafe.Pointer(&cgEpAndGradSq_args.arg_mhy)
	 cgEpAndGradSq_args.argptr[4] = unsafe.Pointer(&cgEpAndGradSq_args.arg_mhz)
	 cgEpAndGradSq_args.argptr[5] = unsafe.Pointer(&cgEpAndGradSq_args.arg_dirx)
	 cgEpAndGradSq_args.argptr[6] = unsafe.Pointer(&cgEpAndGradSq_args.arg_diry)
	 cgEpAndGradSq_args.argptr[7] = unsafe.Pointer(&cgEpAndGradSq_args.arg_dirz)
	 cgEpAndGradSq_args.argptr[8] = unsafe.Pointer(&cgEpAndGradSq_args.arg_ms)
	 cgEpAndGradSq_args.argptr[9] = unsafe.Pointer(&cgEpAndGradSq_args.arg_tsq)
	 cgEpAndGradSq_args.argptr[10] = unsafe.Pointer(&cgEpAndGradSq_args.arg_N)
	 }

// Wrapper for cgEpAndGradSq CUDA kernel, asynchronous.
func k_cgEpAndGradSq_async ( g_ep unsafe.Pointer, g_gsq unsafe.Pointer, mhx unsafe.Pointer, mhy unsafe.Pointer, mhz unsafe.Pointer, dirx unsafe.Pointer, diry unsafe.Pointer, dirz unsafe.Pointer, ms unsafe.Pointer, tsq float32, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgEpAndGradSq")
	}

	cgEpAndGradSq_args.Lock()
	defer cgEpAndGradSq_args.Unlock()

	if cgEpAndGradSq_code == 0{
		cgEpAndGradSq_code = fatbinLoad(cgEpAndGradSq_map, "cgEpAndGradSq")
	}

	 cgEpAndGradSq_args.arg_g_ep = g_ep
	 cgEpAndGradSq_args.arg_g_gsq = g_gsq
	 cgEpAndGradSq_args.arg_mhx = mhx
	 cgEpAndGradSq_args.arg_mhy = mhy
	 cgEpAndGradSq_args.arg_mhz = mhz
	 cgEpAndGradSq_args.arg_dirx = dirx
	 cgEpAndGradSq_args.arg_diry = diry
	 cgEpAndGradSq_args.arg_dirz = dirz
	 cgEpAndGradSq_args.arg_ms = ms
	 cgEpAndGradSq_args.arg_tsq = tsq
	 cgEpAndGradSq_args.arg_N = N
	

	args := cgEpAndGradSq_args.argptr[:]
	cu.LaunchKernel(cgEpAndGradSq_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgEpAndGradSq")
	}
}

// maps compute capability on PTX code for cgEpAndGradSq kernel.
var cgEpAndGradSq_map = map[int]string{ 0: "" ,
61: cgEpAndGradSq_ptx_61  }

// cgEpAndGradSq PTX code for various compute capabilities.
const(
  cgEpAndGradSq_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgEpAndGradSq

.visible .entry cgEpAndGradSq(
	.param .u64 cgEpAndGradSq_param_0,
	.param .u64 cgEpAndGradSq_param_1,
	.param .u64 cgEpAndGradSq_param_2,
	.param .u64 cgEpAndGradSq_param_3,
	.param .u64 cgEpAndGradSq_param_4,
	.param .u64 cgEpAndGradSq_param_5,
	.param .u64 cgEpAndGradSq_param_6,
	.param .u64 cgEpAndGradSq_param_7,
	.param .u64 cgEpAndGradSq_param_8,
	.param .f32 cgEpAndGradSq_param_9,
	.param .u32 cgEpAndGradSq_param_10
)
{
	.reg .pred 	%p<47>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<113>;
	.reg .f64 	%fd<86>;
	.reg .b64 	%rd<29>;
	// demoted variable
	.shared .align 8 .b8 _ZZ13cgEpAndGradSqE4smem[512];

	ld.param.u64 	%rd2, [cgEpAndGradSq_param_0];
	ld.param.u64 	%rd3, [cgEpAndGradSq_param_1];
	ld.param.u64 	%rd4, [cgEpAndGradSq_param_2];
	ld.param.u64 	%rd5, [cgEpAndGradSq_param_3];
	ld.param.u64 	%rd6, [cgEpAndGradSq_param_4];
	ld.param.u64 	%rd7, [cgEpAndGradSq_param_5];
	ld.param.u64 	%rd8, [cgEpAndGradSq_param_6];
	ld.param.u64 	%rd9, [cgEpAndGradSq_param_7];
	ld.param.u64 	%rd10, [cgEpAndGradSq_param_8];
	ld.param.f32 	%f2, [cgEpAndGradSq_param_9];
	ld.param.u32 	%r5, [cgEpAndGradSq_param_10];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r6, %nctaid.x;
	mov.u32 	%r7, %ctaid.y;
	mov.u32 	%r8, %ctaid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r3, %r9, %r1, %r2;
	setp.ge.s32 	%p1, %r3, %r5;
	mov.f64 	%fd80, 0d0000000000000000;
	mov.f64 	%fd81, 0d0000000000000000;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd11, %rd10;
	cvt.s64.s32 	%rd1, %r3;
	mul.wide.s32 	%rd12, %r3, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.f32 	%f1, [%rd13];
	setp.eq.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd14, %rd7;
	shl.b64 	%rd15, %rd1, 2;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.f32 	%f3, [%rd16];
	cvt.f64.f32 	%fd19, %f3;
	cvta.to.global.u64 	%rd17, %rd8;
	add.s64 	%rd18, %rd17, %rd15;
	ld.global.f32 	%f4, [%rd18];
	cvt.f64.f32 	%fd20, %f4;
	cvta.to.global.u64 	%rd19, %rd9;
	add.s64 	%rd20, %rd19, %rd15;
	ld.global.f32 	%f5, [%rd20];
	cvt.f64.f32 	%fd21, %f5;
	cvta.to.global.u64 	%rd21, %rd4;
	add.s64 	%rd22, %rd21, %rd15;
	ld.global.f32 	%f6, [%rd22];
	cvt.f64.f32 	%fd22, %f6;
	cvta.to.global.u64 	%rd23, %rd5;
	add.s64 	%rd24, %rd23, %rd15;
	ld.global.f32 	%f7, [%rd24];
	cvt.f64.f32 	%fd23, %f7;
	cvta.to.global.u64 	%rd25, %rd6;
	add.s64 	%rd26, %rd25, %rd15;
	ld.global.f32 	%f8, [%rd26];
	cvt.f64.f32 	%fd24, %f8;
	mul.f64 	%fd25, %fd20, %fd20;
	fma.rn.f64 	%fd26, %fd19, %fd19, %fd25;
	fma.rn.f64 	%fd27, %fd21, %fd21, %fd26;
	cvt.f64.f32 	%fd28, %f2;
	fma.rn.f64 	%fd29, %fd27, %fd28, 0d3FF0000000000000;
	sqrt.rn.f64 	%fd30, %fd29;
	cvt.f64.f32 	%fd31, %f1;
	div.rn.f64 	%fd32, %fd31, %fd30;
	mul.f64 	%fd33, %fd20, %fd23;
	fma.rn.f64 	%fd34, %fd19, %fd22, %fd33;
	fma.rn.f64 	%fd35, %fd21, %fd24, %fd34;
	fma.rn.f64 	%fd80, %fd32, %fd35, 0d0000000000000000;
	mul.f64 	%fd36, %fd23, %fd23;
	fma.rn.f64 	%fd37, %fd22, %fd22, %fd36;
	fma.rn.f64 	%fd38, %fd24, %fd24, %fd37;
	mul.f64 	%fd39, %fd32, %fd32;
	fma.rn.f64 	%fd81, %fd38, %fd39, 0d0000000000000000;

$L__BB0_3:
	{
	.reg .b32 %temp; 
	mov.b64 	{%r10, %temp}, %fd80;
	}
	mov.u32 	%r11, 2;
	mov.u32 	%r12, 31;
	mov.u32 	%r13, 16;
	mov.u32 	%r14, -1;
	shfl.sync.down.b32 	%r15|%p3, %r10, %r13, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r16}, %fd80;
	}
	shfl.sync.down.b32 	%r17|%p4, %r16, %r13, %r12, %r14;
	mov.b64 	%fd40, {%r15, %r17};
	add.f64 	%fd41, %fd80, %fd40;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r18, %temp}, %fd41;
	}
	mov.u32 	%r19, 8;
	shfl.sync.down.b32 	%r20|%p5, %r18, %r19, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r21}, %fd41;
	}
	shfl.sync.down.b32 	%r22|%p6, %r21, %r19, %r12, %r14;
	mov.b64 	%fd42, {%r20, %r22};
	add.f64 	%fd43, %fd41, %fd42;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r23, %temp}, %fd43;
	}
	mov.u32 	%r24, 4;
	shfl.sync.down.b32 	%r25|%p7, %r23, %r24, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r26}, %fd43;
	}
	shfl.sync.down.b32 	%r27|%p8, %r26, %r24, %r12, %r14;
	mov.b64 	%fd44, {%r25, %r27};
	add.f64 	%fd45, %fd43, %fd44;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r28, %temp}, %fd45;
	}
	shfl.sync.down.b32 	%r29|%p9, %r28, %r11, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r30}, %fd45;
	}
	shfl.sync.down.b32 	%r31|%p10, %r30, %r11, %r12, %r14;
	mov.b64 	%fd46, {%r29, %r31};
	add.f64 	%fd47, %fd45, %fd46;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r32, %temp}, %fd47;
	}
	mov.u32 	%r33, 1;
	shfl.sync.down.b32 	%r34|%p11, %r32, %r33, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r35}, %fd47;
	}
	shfl.sync.down.b32 	%r36|%p12, %r35, %r33, %r12, %r14;
	mov.b64 	%fd48, {%r34, %r36};
	add.f64 	%fd5, %fd47, %fd48;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r37, %temp}, %fd81;
	}
	shfl.sync.down.b32 	%r38|%p13, %r37, %r13, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r39}, %fd81;
	}
	shfl.sync.down.b32 	%r40|%p14, %r39, %r13, %r12, %r14;
	mov.b64 	%fd49, {%r38, %r40};
	add.f64 	%fd50, %fd81, %fd49;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r41, %temp}, %fd50;
	}
	shfl.sync.down.b32 	%r42|%p15, %r41, %r19, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r43}, %fd50;
	}
	shfl.sync.down.b32 	%r44|%p16, %r43, %r19, %r12, %r14;
	mov.b64 	%fd51, {%r42, %r44};
	add.f64 	%fd52, %fd50, %fd51;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r45, %temp}, %fd52;
	}
	shfl.sync.down.b32 	%r46|%p17, %r45, %r24, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r47}, %fd52;
	}
	shfl.sync.down.b32 	%r48|%p18, %r47, %r24, %r12, %r14;
	mov.b64 	%fd53, {%r46, %r48};
	add.f64 	%fd54, %fd52, %fd53;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r49, %temp}, %fd54;
	}
	shfl.sync.down.b32 	%r50|%p19, %r49, %r11, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r51}, %fd54;
	}
	shfl.sync.down.b32 	%r52|%p20, %r51, %r11, %r12, %r14;
	mov.b64 	%fd55, {%r50, %r52};
	add.f64 	%fd56, %fd54, %fd55;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r53, %temp}, %fd56;
	}
	shfl.sync.down.b32 	%r54|%p21, %r53, %r33, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r55}, %fd56;
	}
	shfl.sync.down.b32 	%r56|%p22, %r55, %r33, %r12, %r14;
	mov.b64 	%fd57, {%r54, %r56};
	add.f64 	%fd6, %fd56, %fd57;
	shr.u32 	%r4, %r2, 5;
	and.b32  	%r57, %r2, 31;
	setp.ne.s32 	%p23, %r57, 0;
	@%p23 bra 	$L__BB0_5;

	shl.b32 	%r58, %r4, 3;
	mov.u32 	%r59, _ZZ13cgEpAndGradSqE4smem;
	add.s32 	%r60, %r59, %r58;
	st.shared.f64 	[%r60], %fd5;
	st.shared.f64 	[%r60+256], %fd6;

$L__BB0_5:
	bar.sync 	0;
	add.s32 	%r61, %r1, 31;
	shr.u32 	%r62, %r61, 5;
	setp.ge.u32 	%p24, %r2, %r62;
	mov.f64 	%fd84, 0d0000000000000000;
	mov.f64 	%fd85, %fd84;
	@%p24 bra 	$L__BB0_7;

	shl.b32 	%r63, %r2, 3;
	mov.u32 	%r64, _ZZ13cgEpAndGradSqE4smem;
	add.s32 	%r65, %r64, %r63;
	ld.shared.f64 	%fd84, [%r65];
	ld.shared.f64 	%fd85, [%r65+256];

$L__BB0_7:
	setp.ne.s32 	%p25, %r4, 0;
	@%p25 bra 	$L__BB0_9;

	{
	.reg .b32 %temp; 
	mov.b64 	{%r66, %temp}, %fd84;
	}
	mov.u32 	%r67, 2;
	mov.u32 	%r68, 31;
	mov.u32 	%r69, 16;
	mov.u32 	%r70, -1;
	shfl.sync.down.b32 	%r71|%p26, %r66, %r69, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r72}, %fd84;
	}
	shfl.sync.down.b32 	%r73|%p27, %r72, %r69, %r68, %r70;
	mov.b64 	%fd60, {%r71, %r73};
	add.f64 	%fd61, %fd84, %fd60;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r74, %temp}, %fd61;
	}
	mov.u32 	%r75, 8;
	shfl.sync.down.b32 	%r76|%p28, %r74, %r75, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r77}, %fd61;
	}
	shfl.sync.down.b32 	%r78|%p29, %r77, %r75, %r68, %r70;
	mov.b64 	%fd62, {%r76, %r78};
	add.f64 	%fd63, %fd61, %fd62;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r79, %temp}, %fd63;
	}
	mov.u32 	%r80, 4;
	shfl.sync.down.b32 	%r81|%p30, %r79, %r80, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r82}, %fd63;
	}
	shfl.sync.down.b32 	%r83|%p31, %r82, %r80, %r68, %r70;
	mov.b64 	%fd64, {%r81, %r83};
	add.f64 	%fd65, %fd63, %fd64;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r84, %temp}, %fd65;
	}
	shfl.sync.down.b32 	%r85|%p32, %r84, %r67, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r86}, %fd65;
	}
	shfl.sync.down.b32 	%r87|%p33, %r86, %r67, %r68, %r70;
	mov.b64 	%fd66, {%r85, %r87};
	add.f64 	%fd67, %fd65, %fd66;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r88, %temp}, %fd67;
	}
	mov.u32 	%r89, 1;
	shfl.sync.down.b32 	%r90|%p34, %r88, %r89, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r91}, %fd67;
	}
	shfl.sync.down.b32 	%r92|%p35, %r91, %r89, %r68, %r70;
	mov.b64 	%fd68, {%r90, %r92};
	add.f64 	%fd84, %fd67, %fd68;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r93, %temp}, %fd85;
	}
	shfl.sync.down.b32 	%r94|%p36, %r93, %r69, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r95}, %fd85;
	}
	shfl.sync.down.b32 	%r96|%p37, %r95, %r69, %r68, %r70;
	mov.b64 	%fd69, {%r94, %r96};
	add.f64 	%fd70, %fd85, %fd69;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r97, %temp}, %fd70;
	}
	shfl.sync.down.b32 	%r98|%p38, %r97, %r75, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r99}, %fd70;
	}
	shfl.sync.down.b32 	%r100|%p39, %r99, %r75, %r68, %r70;
	mov.b64 	%fd71, {%r98, %r100};
	add.f64 	%fd72, %fd70, %fd71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r101, %temp}, %fd72;
	}
	shfl.sync.down.b32 	%r102|%p40, %r101, %r80, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r103}, %fd72;
	}
	shfl.sync.down.b32 	%r104|%p41, %r103, %r80, %r68, %r70;
	mov.b64 	%fd73, {%r102, %r104};
	add.f64 	%fd74, %fd72, %fd73;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r105, %temp}, %fd74;
	}
	shfl.sync.down.b32 	%r106|%p42, %r105, %r67, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r107}, %fd74;
	}
	shfl.sync.down.b32 	%r108|%p43, %r107, %r67, %r68, %r70;
	mov.b64 	%fd75, {%r106, %r108};
	add.f64 	%fd76, %fd74, %fd75;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r109, %temp}, %fd76;
	}
	shfl.sync.down.b32 	%r110|%p44, %r109, %r89, %r68, %r70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r111}, %fd76;
	}
	shfl.sync.down.b32 	%r112|%p45, %r111, %r89, %r68, %r70;
	mov.b64 	%fd77, {%r110, %r112};
	add.f64 	%fd85, %fd76, %fd77;

$L__BB0_9:
	setp.ne.s32 	%p46, %r2, 0;
	@%p46 bra 	$L__BB0_11;

	cvt.rn.f32.f64 	%f9, %fd84;
	cvta.to.global.u64 	%rd27, %rd2;
	atom.global.add.f32 	%f10, [%rd27], %f9;
	cvt.rn.f32.f64 	%f11, %fd85;
	cvta.to.global.u64 	%rd28, %rd3;
	atom.global.add.f32 	%f12, [%rd28], %f11;

$L__BB0_11:
	ret;

}

`
 )
