package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgGammaPR kernel
var cgGammaPR_code cu.Function

// Stores the arguments for cgGammaPR kernel invocation
type cgGammaPR_args_t struct{
	 arg_g_gsq unsafe.Pointer
	 arg_g_gamma unsafe.Pointer
	 arg_curx unsafe.Pointer
	 arg_cury unsafe.Pointer
	 arg_curz unsafe.Pointer
	 arg_px unsafe.Pointer
	 arg_py unsafe.Pointer
	 arg_pz unsafe.Pointer
	 arg_msv unsafe.Pointer
	 arg_N int
	 argptr [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgGammaPR kernel invocation
var cgGammaPR_args cgGammaPR_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgGammaPR_args.argptr[0] = unsafe.Pointer(&cgGammaPR_args.arg_g_gsq)
	 cgGammaPR_args.argptr[1] = unsafe.Pointer(&cgGammaPR_args.arg_g_gamma)
	 cgGammaPR_args.argptr[2] = unsafe.Pointer(&cgGammaPR_args.arg_curx)
	 cgGammaPR_args.argptr[3] = unsafe.Pointer(&cgGammaPR_args.arg_cury)
	 cgGammaPR_args.argptr[4] = unsafe.Pointer(&cgGammaPR_args.arg_curz)
	 cgGammaPR_args.argptr[5] = unsafe.Pointer(&cgGammaPR_args.arg_px)
	 cgGammaPR_args.argptr[6] = unsafe.Pointer(&cgGammaPR_args.arg_py)
	 cgGammaPR_args.argptr[7] = unsafe.Pointer(&cgGammaPR_args.arg_pz)
	 cgGammaPR_args.argptr[8] = unsafe.Pointer(&cgGammaPR_args.arg_msv)
	 cgGammaPR_args.argptr[9] = unsafe.Pointer(&cgGammaPR_args.arg_N)
	 }

// Wrapper for cgGammaPR CUDA kernel, asynchronous.
func k_cgGammaPR_async ( g_gsq unsafe.Pointer, g_gamma unsafe.Pointer, curx unsafe.Pointer, cury unsafe.Pointer, curz unsafe.Pointer, px unsafe.Pointer, py unsafe.Pointer, pz unsafe.Pointer, msv unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgGammaPR")
	}

	cgGammaPR_args.Lock()
	defer cgGammaPR_args.Unlock()

	if cgGammaPR_code == 0{
		cgGammaPR_code = fatbinLoad(cgGammaPR_map, "cgGammaPR")
	}

	 cgGammaPR_args.arg_g_gsq = g_gsq
	 cgGammaPR_args.arg_g_gamma = g_gamma
	 cgGammaPR_args.arg_curx = curx
	 cgGammaPR_args.arg_cury = cury
	 cgGammaPR_args.arg_curz = curz
	 cgGammaPR_args.arg_px = px
	 cgGammaPR_args.arg_py = py
	 cgGammaPR_args.arg_pz = pz
	 cgGammaPR_args.arg_msv = msv
	 cgGammaPR_args.arg_N = N
	

	args := cgGammaPR_args.argptr[:]
	cu.LaunchKernel(cgGammaPR_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgGammaPR")
	}
}

// maps compute capability on PTX code for cgGammaPR kernel.
var cgGammaPR_map = map[int]string{ 0: "" ,
61: cgGammaPR_ptx_61  }

// cgGammaPR PTX code for various compute capabilities.
const(
  cgGammaPR_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgGammaPR

.visible .entry cgGammaPR(
	.param .u64 cgGammaPR_param_0,
	.param .u64 cgGammaPR_param_1,
	.param .u64 cgGammaPR_param_2,
	.param .u64 cgGammaPR_param_3,
	.param .u64 cgGammaPR_param_4,
	.param .u64 cgGammaPR_param_5,
	.param .u64 cgGammaPR_param_6,
	.param .u64 cgGammaPR_param_7,
	.param .u64 cgGammaPR_param_8,
	.param .u32 cgGammaPR_param_9
)
{
	.reg .pred 	%p<47>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<114>;
	.reg .f64 	%fd<82>;
	.reg .b64 	%rd<29>;
	// demoted variable
	.shared .align 8 .b8 _ZZ9cgGammaPRE4smem[512];

	ld.param.u64 	%rd5, [cgGammaPR_param_0];
	ld.param.u64 	%rd6, [cgGammaPR_param_1];
	ld.param.u64 	%rd7, [cgGammaPR_param_2];
	ld.param.u64 	%rd8, [cgGammaPR_param_3];
	ld.param.u64 	%rd9, [cgGammaPR_param_4];
	ld.param.u64 	%rd10, [cgGammaPR_param_5];
	ld.param.u64 	%rd11, [cgGammaPR_param_6];
	ld.param.u64 	%rd12, [cgGammaPR_param_7];
	ld.param.u64 	%rd13, [cgGammaPR_param_8];
	ld.param.u32 	%r5, [cgGammaPR_param_9];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r6, %nctaid.x;
	mov.u32 	%r7, %ctaid.y;
	mov.u32 	%r8, %ctaid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r3, %r9, %r1, %r2;
	setp.ge.s32 	%p1, %r3, %r5;
	mov.f64 	%fd76, 0d0000000000000000;
	mov.f64 	%fd77, %fd76;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd14, %rd13;
	cvt.s64.s32 	%rd1, %r3;
	mul.wide.s32 	%rd15, %r3, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.f32 	%f1, [%rd16];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd17, %rd10;
	add.s64 	%rd2, %rd17, %rd15;
	cvta.to.global.u64 	%rd18, %rd11;
	add.s64 	%rd3, %rd18, %rd15;
	cvta.to.global.u64 	%rd19, %rd12;
	add.s64 	%rd4, %rd19, %rd15;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	cvt.f64.f32 	%fd19, %f1;
	mul.f64 	%fd20, %fd19, %fd19;
	cvta.to.global.u64 	%rd20, %rd7;
	shl.b64 	%rd21, %rd1, 2;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.f32 	%f2, [%rd22];
	cvt.f64.f32 	%fd21, %f2;
	cvta.to.global.u64 	%rd23, %rd8;
	add.s64 	%rd24, %rd23, %rd21;
	ld.global.f32 	%f3, [%rd24];
	cvt.f64.f32 	%fd22, %f3;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd26, %rd25, %rd21;
	ld.global.f32 	%f4, [%rd26];
	cvt.f64.f32 	%fd23, %f4;
	ld.global.f32 	%f5, [%rd2];
	cvt.f64.f32 	%fd24, %f5;
	ld.global.f32 	%f6, [%rd3];
	cvt.f64.f32 	%fd25, %f6;
	ld.global.f32 	%f7, [%rd4];
	cvt.f64.f32 	%fd26, %f7;
	mul.f64 	%fd27, %fd22, %fd22;
	fma.rn.f64 	%fd28, %fd21, %fd21, %fd27;
	fma.rn.f64 	%fd29, %fd23, %fd23, %fd28;
	mul.f64 	%fd76, %fd20, %fd29;
	sub.f64 	%fd30, %fd21, %fd24;
	sub.f64 	%fd31, %fd22, %fd25;
	mul.f64 	%fd32, %fd31, %fd22;
	fma.rn.f64 	%fd33, %fd30, %fd21, %fd32;
	sub.f64 	%fd34, %fd23, %fd26;
	fma.rn.f64 	%fd35, %fd34, %fd23, %fd33;
	mul.f64 	%fd77, %fd20, %fd35;
	st.global.f32 	[%rd2], %f2;
	st.global.f32 	[%rd3], %f3;
	st.global.f32 	[%rd4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	mov.u32 	%r10, 0;
	st.global.u32 	[%rd2], %r10;
	st.global.u32 	[%rd3], %r10;
	st.global.u32 	[%rd4], %r10;
	mov.f64 	%fd77, %fd76;

$L__BB0_4:
	{
	.reg .b32 %temp; 
	mov.b64 	{%r11, %temp}, %fd76;
	}
	mov.u32 	%r12, 2;
	mov.u32 	%r13, 31;
	mov.u32 	%r14, 16;
	mov.u32 	%r15, -1;
	shfl.sync.down.b32 	%r16|%p3, %r11, %r14, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r17}, %fd76;
	}
	shfl.sync.down.b32 	%r18|%p4, %r17, %r14, %r13, %r15;
	mov.b64 	%fd36, {%r16, %r18};
	add.f64 	%fd37, %fd76, %fd36;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r19, %temp}, %fd37;
	}
	mov.u32 	%r20, 8;
	shfl.sync.down.b32 	%r21|%p5, %r19, %r20, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r22}, %fd37;
	}
	shfl.sync.down.b32 	%r23|%p6, %r22, %r20, %r13, %r15;
	mov.b64 	%fd38, {%r21, %r23};
	add.f64 	%fd39, %fd37, %fd38;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r24, %temp}, %fd39;
	}
	mov.u32 	%r25, 4;
	shfl.sync.down.b32 	%r26|%p7, %r24, %r25, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r27}, %fd39;
	}
	shfl.sync.down.b32 	%r28|%p8, %r27, %r25, %r13, %r15;
	mov.b64 	%fd40, {%r26, %r28};
	add.f64 	%fd41, %fd39, %fd40;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r29, %temp}, %fd41;
	}
	shfl.sync.down.b32 	%r30|%p9, %r29, %r12, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r31}, %fd41;
	}
	shfl.sync.down.b32 	%r32|%p10, %r31, %r12, %r13, %r15;
	mov.b64 	%fd42, {%r30, %r32};
	add.f64 	%fd43, %fd41, %fd42;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r33, %temp}, %fd43;
	}
	mov.u32 	%r34, 1;
	shfl.sync.down.b32 	%r35|%p11, %r33, %r34, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r36}, %fd43;
	}
	shfl.sync.down.b32 	%r37|%p12, %r36, %r34, %r13, %r15;
	mov.b64 	%fd44, {%r35, %r37};
	add.f64 	%fd5, %fd43, %fd44;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r38, %temp}, %fd77;
	}
	shfl.sync.down.b32 	%r39|%p13, %r38, %r14, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r40}, %fd77;
	}
	shfl.sync.down.b32 	%r41|%p14, %r40, %r14, %r13, %r15;
	mov.b64 	%fd45, {%r39, %r41};
	add.f64 	%fd46, %fd77, %fd45;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r42, %temp}, %fd46;
	}
	shfl.sync.down.b32 	%r43|%p15, %r42, %r20, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r44}, %fd46;
	}
	shfl.sync.down.b32 	%r45|%p16, %r44, %r20, %r13, %r15;
	mov.b64 	%fd47, {%r43, %r45};
	add.f64 	%fd48, %fd46, %fd47;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r46, %temp}, %fd48;
	}
	shfl.sync.down.b32 	%r47|%p17, %r46, %r25, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r48}, %fd48;
	}
	shfl.sync.down.b32 	%r49|%p18, %r48, %r25, %r13, %r15;
	mov.b64 	%fd49, {%r47, %r49};
	add.f64 	%fd50, %fd48, %fd49;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r50, %temp}, %fd50;
	}
	shfl.sync.down.b32 	%r51|%p19, %r50, %r12, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r52}, %fd50;
	}
	shfl.sync.down.b32 	%r53|%p20, %r52, %r12, %r13, %r15;
	mov.b64 	%fd51, {%r51, %r53};
	add.f64 	%fd52, %fd50, %fd51;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r54, %temp}, %fd52;
	}
	shfl.sync.down.b32 	%r55|%p21, %r54, %r34, %r13, %r15;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r56}, %fd52;
	}
	shfl.sync.down.b32 	%r57|%p22, %r56, %r34, %r13, %r15;
	mov.b64 	%fd53, {%r55, %r57};
	add.f64 	%fd6, %fd52, %fd53;
	shr.u32 	%r4, %r2, 5;
	and.b32  	%r58, %r2, 31;
	setp.ne.s32 	%p23, %r58, 0;
	@%p23 bra 	$L__BB0_6;

	shl.b32 	%r59, %r4, 3;
	mov.u32 	%r60, _ZZ9cgGammaPRE4smem;
	add.s32 	%r61, %r60, %r59;
	st.shared.f64 	[%r61], %fd5;
	st.shared.f64 	[%r61+256], %fd6;

$L__BB0_6:
	bar.sync 	0;
	add.s32 	%r62, %r1, 31;
	shr.u32 	%r63, %r62, 5;
	setp.ge.u32 	%p24, %r2, %r63;
	mov.f64 	%fd80, 0d0000000000000000;
	mov.f64 	%fd81, %fd80;
	@%p24 bra 	$L__BB0_8;

	shl.b32 	%r64, %r2, 3;
	mov.u32 	%r65, _ZZ9cgGammaPRE4smem;
	add.s32 	%r66, %r65, %r64;
	ld.shared.f64 	%fd80, [%r66];
	ld.shared.f64 	%fd81, [%r66+256];

$L__BB0_8:
	setp.ne.s32 	%p25, %r4, 0;
	@%p25 bra 	$L__BB0_10;

	{
	.reg .b32 %temp; 
	mov.b64 	{%r67, %temp}, %fd80;
	}
	mov.u32 	%r68, 2;
	mov.u32 	%r69, 31;
	mov.u32 	%r70, 16;
	mov.u32 	%r71, -1;
	shfl.sync.down.b32 	%r72|%p26, %r67, %r70, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r73}, %fd80;
	}
	shfl.sync.down.b32 	%r74|%p27, %r73, %r70, %r69, %r71;
	mov.b64 	%fd56, {%r72, %r74};
	add.f64 	%fd57, %fd80, %fd56;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r75, %temp}, %fd57;
	}
	mov.u32 	%r76, 8;
	shfl.sync.down.b32 	%r77|%p28, %r75, %r76, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r78}, %fd57;
	}
	shfl.sync.down.b32 	%r79|%p29, %r78, %r76, %r69, %r71;
	mov.b64 	%fd58, {%r77, %r79};
	add.f64 	%fd59, %fd57, %fd58;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r80, %temp}, %fd59;
	}
	mov.u32 	%r81, 4;
	shfl.sync.down.b32 	%r82|%p30, %r80, %r81, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r83}, %fd59;
	}
	shfl.sync.down.b32 	%r84|%p31, %r83, %r81, %r69, %r71;
	mov.b64 	%fd60, {%r82, %r84};
	add.f64 	%fd61, %fd59, %fd60;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r85, %temp}, %fd61;
	}
	shfl.sync.down.b32 	%r86|%p32, %r85, %r68, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r87}, %fd61;
	}
	shfl.sync.down.b32 	%r88|%p33, %r87, %r68, %r69, %r71;
	mov.b64 	%fd62, {%r86, %r88};
	add.f64 	%fd63, %fd61, %fd62;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r89, %temp}, %fd63;
	}
	mov.u32 	%r90, 1;
	shfl.sync.down.b32 	%r91|%p34, %r89, %r90, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r92}, %fd63;
	}
	shfl.sync.down.b32 	%r93|%p35, %r92, %r90, %r69, %r71;
	mov.b64 	%fd64, {%r91, %r93};
	add.f64 	%fd80, %fd63, %fd64;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r94, %temp}, %fd81;
	}
	shfl.sync.down.b32 	%r95|%p36, %r94, %r70, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r96}, %fd81;
	}
	shfl.sync.down.b32 	%r97|%p37, %r96, %r70, %r69, %r71;
	mov.b64 	%fd65, {%r95, %r97};
	add.f64 	%fd66, %fd81, %fd65;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r98, %temp}, %fd66;
	}
	shfl.sync.down.b32 	%r99|%p38, %r98, %r76, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r100}, %fd66;
	}
	shfl.sync.down.b32 	%r101|%p39, %r100, %r76, %r69, %r71;
	mov.b64 	%fd67, {%r99, %r101};
	add.f64 	%fd68, %fd66, %fd67;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r102, %temp}, %fd68;
	}
	shfl.sync.down.b32 	%r103|%p40, %r102, %r81, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r104}, %fd68;
	}
	shfl.sync.down.b32 	%r105|%p41, %r104, %r81, %r69, %r71;
	mov.b64 	%fd69, {%r103, %r105};
	add.f64 	%fd70, %fd68, %fd69;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r106, %temp}, %fd70;
	}
	shfl.sync.down.b32 	%r107|%p42, %r106, %r68, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r108}, %fd70;
	}
	shfl.sync.down.b32 	%r109|%p43, %r108, %r68, %r69, %r71;
	mov.b64 	%fd71, {%r107, %r109};
	add.f64 	%fd72, %fd70, %fd71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r110, %temp}, %fd72;
	}
	shfl.sync.down.b32 	%r111|%p44, %r110, %r90, %r69, %r71;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r112}, %fd72;
	}
	shfl.sync.down.b32 	%r113|%p45, %r112, %r90, %r69, %r71;
	mov.b64 	%fd73, {%r111, %r113};
	add.f64 	%fd81, %fd72, %fd73;

$L__BB0_10:
	setp.ne.s32 	%p46, %r2, 0;
	@%p46 bra 	$L__BB0_12;

	cvta.to.global.u64 	%rd27, %rd5;
	atom.global.add.f64 	%fd74, [%rd27], %fd80;
	cvta.to.global.u64 	%rd28, %rd6;
	atom.global.add.f64 	%fd75, [%rd28], %fd81;

$L__BB0_12:
	ret;

}

`
 )
