package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgGammaPR kernel
var cgGammaPR_code cu.Function

// Stores the arguments for cgGammaPR kernel invocation
type cgGammaPR_args_t struct{
	 arg_g_gsq unsafe.Pointer
	 arg_g_gamma unsafe.Pointer
	 arg_curx unsafe.Pointer
	 arg_cury unsafe.Pointer
	 arg_curz unsafe.Pointer
	 arg_px unsafe.Pointer
	 arg_py unsafe.Pointer
	 arg_pz unsafe.Pointer
	 arg_msv unsafe.Pointer
	 arg_N int
	 argptr [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgGammaPR kernel invocation
var cgGammaPR_args cgGammaPR_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgGammaPR_args.argptr[0] = unsafe.Pointer(&cgGammaPR_args.arg_g_gsq)
	 cgGammaPR_args.argptr[1] = unsafe.Pointer(&cgGammaPR_args.arg_g_gamma)
	 cgGammaPR_args.argptr[2] = unsafe.Pointer(&cgGammaPR_args.arg_curx)
	 cgGammaPR_args.argptr[3] = unsafe.Pointer(&cgGammaPR_args.arg_cury)
	 cgGammaPR_args.argptr[4] = unsafe.Pointer(&cgGammaPR_args.arg_curz)
	 cgGammaPR_args.argptr[5] = unsafe.Pointer(&cgGammaPR_args.arg_px)
	 cgGammaPR_args.argptr[6] = unsafe.Pointer(&cgGammaPR_args.arg_py)
	 cgGammaPR_args.argptr[7] = unsafe.Pointer(&cgGammaPR_args.arg_pz)
	 cgGammaPR_args.argptr[8] = unsafe.Pointer(&cgGammaPR_args.arg_msv)
	 cgGammaPR_args.argptr[9] = unsafe.Pointer(&cgGammaPR_args.arg_N)
	 }

// Wrapper for cgGammaPR CUDA kernel, asynchronous.
func k_cgGammaPR_async ( g_gsq unsafe.Pointer, g_gamma unsafe.Pointer, curx unsafe.Pointer, cury unsafe.Pointer, curz unsafe.Pointer, px unsafe.Pointer, py unsafe.Pointer, pz unsafe.Pointer, msv unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgGammaPR")
	}

	cgGammaPR_args.Lock()
	defer cgGammaPR_args.Unlock()

	if cgGammaPR_code == 0{
		cgGammaPR_code = fatbinLoad(cgGammaPR_map, "cgGammaPR")
	}

	 cgGammaPR_args.arg_g_gsq = g_gsq
	 cgGammaPR_args.arg_g_gamma = g_gamma
	 cgGammaPR_args.arg_curx = curx
	 cgGammaPR_args.arg_cury = cury
	 cgGammaPR_args.arg_curz = curz
	 cgGammaPR_args.arg_px = px
	 cgGammaPR_args.arg_py = py
	 cgGammaPR_args.arg_pz = pz
	 cgGammaPR_args.arg_msv = msv
	 cgGammaPR_args.arg_N = N
	

	args := cgGammaPR_args.argptr[:]
	cu.LaunchKernel(cgGammaPR_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgGammaPR")
	}
}

// maps compute capability on PTX code for cgGammaPR kernel.
var cgGammaPR_map = map[int]string{ 0: "" ,
61: cgGammaPR_ptx_61  }

// cgGammaPR PTX code for various compute capabilities.
const(
  cgGammaPR_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgGammaPR

.visible .entry cgGammaPR(
	.param .u64 cgGammaPR_param_0,
	.param .u64 cgGammaPR_param_1,
	.param .u64 cgGammaPR_param_2,
	.param .u64 cgGammaPR_param_3,
	.param .u64 cgGammaPR_param_4,
	.param .u64 cgGammaPR_param_5,
	.param .u64 cgGammaPR_param_6,
	.param .u64 cgGammaPR_param_7,
	.param .u64 cgGammaPR_param_8,
	.param .u32 cgGammaPR_param_9
)
{
	.reg .pred 	%p<27>;
	.reg .f32 	%f<82>;
	.reg .b32 	%r<81>;
	.reg .b64 	%rd<34>;
	// demoted variable
	.shared .align 4 .b8 _ZZ9cgGammaPRE4smem[256];

	ld.param.u64 	%rd4, [cgGammaPR_param_0];
	ld.param.u64 	%rd5, [cgGammaPR_param_1];
	ld.param.u64 	%rd6, [cgGammaPR_param_2];
	ld.param.u64 	%rd7, [cgGammaPR_param_3];
	ld.param.u64 	%rd8, [cgGammaPR_param_4];
	ld.param.u64 	%rd9, [cgGammaPR_param_5];
	ld.param.u64 	%rd10, [cgGammaPR_param_6];
	ld.param.u64 	%rd11, [cgGammaPR_param_7];
	ld.param.u64 	%rd12, [cgGammaPR_param_8];
	ld.param.u32 	%r5, [cgGammaPR_param_9];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r6, %nctaid.x;
	mov.u32 	%r7, %ctaid.y;
	mov.u32 	%r8, %ctaid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r3, %r9, %r1, %r2;
	setp.ge.s32 	%p1, %r3, %r5;
	mov.f32 	%f76, 0f00000000;
	mov.f32 	%f77, %f76;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd13, %rd12;
	mul.wide.s32 	%rd14, %r3, 4;
	add.s64 	%rd15, %rd13, %rd14;
	ld.global.f32 	%f1, [%rd15];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd16, %rd9;
	add.s64 	%rd1, %rd16, %rd14;
	cvta.to.global.u64 	%rd17, %rd10;
	add.s64 	%rd2, %rd17, %rd14;
	cvta.to.global.u64 	%rd18, %rd11;
	add.s64 	%rd3, %rd18, %rd14;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	mul.f32 	%f20, %f1, %f1;
	cvta.to.global.u64 	%rd19, %rd6;
	add.s64 	%rd21, %rd19, %rd14;
	cvta.to.global.u64 	%rd22, %rd7;
	add.s64 	%rd23, %rd22, %rd14;
	cvta.to.global.u64 	%rd24, %rd8;
	add.s64 	%rd25, %rd24, %rd14;
	ld.global.f32 	%f21, [%rd21];
	ld.global.f32 	%f22, [%rd23];
	mul.f32 	%f23, %f22, %f22;
	fma.rn.f32 	%f24, %f21, %f21, %f23;
	ld.global.f32 	%f25, [%rd25];
	fma.rn.f32 	%f26, %f25, %f25, %f24;
	mul.f32 	%f76, %f20, %f26;
	ld.global.f32 	%f27, [%rd1];
	sub.f32 	%f28, %f21, %f27;
	ld.global.f32 	%f29, [%rd2];
	sub.f32 	%f30, %f22, %f29;
	mul.f32 	%f31, %f22, %f30;
	fma.rn.f32 	%f32, %f21, %f28, %f31;
	ld.global.f32 	%f33, [%rd3];
	sub.f32 	%f34, %f25, %f33;
	fma.rn.f32 	%f35, %f25, %f34, %f32;
	mul.f32 	%f77, %f20, %f35;
	st.global.f32 	[%rd1], %f21;
	st.global.f32 	[%rd2], %f22;
	st.global.f32 	[%rd3], %f25;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	mov.u32 	%r10, 0;
	st.global.u32 	[%rd1], %r10;
	st.global.u32 	[%rd2], %r10;
	st.global.u32 	[%rd3], %r10;
	mov.f32 	%f77, %f76;

$L__BB0_4:
	mov.b32 	%r18, %f76;
	mov.u32 	%r19, 2;
	mov.u32 	%r20, 31;
	mov.u32 	%r21, 16;
	mov.u32 	%r22, -1;
	shfl.sync.down.b32 	%r23|%p3, %r18, %r21, %r20, %r22;
	mov.b32 	%f36, %r23;
	add.f32 	%f37, %f76, %f36;
	mov.b32 	%r24, %f37;
	mov.u32 	%r25, 8;
	shfl.sync.down.b32 	%r26|%p4, %r24, %r25, %r20, %r22;
	mov.b32 	%f38, %r26;
	add.f32 	%f39, %f37, %f38;
	mov.b32 	%r27, %f39;
	mov.u32 	%r28, 4;
	shfl.sync.down.b32 	%r29|%p5, %r27, %r28, %r20, %r22;
	mov.b32 	%f40, %r29;
	add.f32 	%f41, %f39, %f40;
	mov.b32 	%r30, %f41;
	shfl.sync.down.b32 	%r31|%p6, %r30, %r19, %r20, %r22;
	mov.b32 	%f42, %r31;
	add.f32 	%f43, %f41, %f42;
	mov.b32 	%r32, %f43;
	mov.u32 	%r33, 1;
	shfl.sync.down.b32 	%r34|%p7, %r32, %r33, %r20, %r22;
	mov.b32 	%f44, %r34;
	add.f32 	%f6, %f43, %f44;
	mov.b32 	%r35, %f77;
	shfl.sync.down.b32 	%r36|%p8, %r35, %r21, %r20, %r22;
	mov.b32 	%f45, %r36;
	add.f32 	%f46, %f77, %f45;
	mov.b32 	%r37, %f46;
	shfl.sync.down.b32 	%r38|%p9, %r37, %r25, %r20, %r22;
	mov.b32 	%f47, %r38;
	add.f32 	%f48, %f46, %f47;
	mov.b32 	%r39, %f48;
	shfl.sync.down.b32 	%r40|%p10, %r39, %r28, %r20, %r22;
	mov.b32 	%f49, %r40;
	add.f32 	%f50, %f48, %f49;
	mov.b32 	%r41, %f50;
	shfl.sync.down.b32 	%r42|%p11, %r41, %r19, %r20, %r22;
	mov.b32 	%f51, %r42;
	add.f32 	%f52, %f50, %f51;
	mov.b32 	%r43, %f52;
	shfl.sync.down.b32 	%r44|%p12, %r43, %r33, %r20, %r22;
	mov.b32 	%f53, %r44;
	add.f32 	%f7, %f52, %f53;
	shr.u32 	%r4, %r2, 5;
	and.b32  	%r45, %r2, 31;
	setp.ne.s32 	%p13, %r45, 0;
	@%p13 bra 	$L__BB0_6;

	shl.b32 	%r46, %r4, 2;
	mov.u32 	%r47, _ZZ9cgGammaPRE4smem;
	add.s32 	%r48, %r47, %r46;
	st.shared.f32 	[%r48], %f6;
	st.shared.f32 	[%r48+128], %f7;

$L__BB0_6:
	bar.sync 	0;
	add.s32 	%r49, %r1, 31;
	shr.u32 	%r50, %r49, 5;
	setp.ge.u32 	%p14, %r2, %r50;
	mov.f32 	%f80, 0f00000000;
	mov.f32 	%f81, %f80;
	@%p14 bra 	$L__BB0_8;

	shl.b32 	%r51, %r2, 2;
	mov.u32 	%r52, _ZZ9cgGammaPRE4smem;
	add.s32 	%r53, %r52, %r51;
	ld.shared.f32 	%f80, [%r53];
	ld.shared.f32 	%f81, [%r53+128];

$L__BB0_8:
	setp.ne.s32 	%p15, %r4, 0;
	@%p15 bra 	$L__BB0_10;

	mov.b32 	%r54, %f80;
	mov.u32 	%r55, 2;
	mov.u32 	%r56, 31;
	mov.u32 	%r57, 16;
	mov.u32 	%r58, -1;
	shfl.sync.down.b32 	%r59|%p16, %r54, %r57, %r56, %r58;
	mov.b32 	%f56, %r59;
	add.f32 	%f57, %f80, %f56;
	mov.b32 	%r60, %f57;
	mov.u32 	%r61, 8;
	shfl.sync.down.b32 	%r62|%p17, %r60, %r61, %r56, %r58;
	mov.b32 	%f58, %r62;
	add.f32 	%f59, %f57, %f58;
	mov.b32 	%r63, %f59;
	mov.u32 	%r64, 4;
	shfl.sync.down.b32 	%r65|%p18, %r63, %r64, %r56, %r58;
	mov.b32 	%f60, %r65;
	add.f32 	%f61, %f59, %f60;
	mov.b32 	%r66, %f61;
	shfl.sync.down.b32 	%r67|%p19, %r66, %r55, %r56, %r58;
	mov.b32 	%f62, %r67;
	add.f32 	%f63, %f61, %f62;
	mov.b32 	%r68, %f63;
	mov.u32 	%r69, 1;
	shfl.sync.down.b32 	%r70|%p20, %r68, %r69, %r56, %r58;
	mov.b32 	%f64, %r70;
	add.f32 	%f80, %f63, %f64;
	mov.b32 	%r71, %f81;
	shfl.sync.down.b32 	%r72|%p21, %r71, %r57, %r56, %r58;
	mov.b32 	%f65, %r72;
	add.f32 	%f66, %f81, %f65;
	mov.b32 	%r73, %f66;
	shfl.sync.down.b32 	%r74|%p22, %r73, %r61, %r56, %r58;
	mov.b32 	%f67, %r74;
	add.f32 	%f68, %f66, %f67;
	mov.b32 	%r75, %f68;
	shfl.sync.down.b32 	%r76|%p23, %r75, %r64, %r56, %r58;
	mov.b32 	%f69, %r76;
	add.f32 	%f70, %f68, %f69;
	mov.b32 	%r77, %f70;
	shfl.sync.down.b32 	%r78|%p24, %r77, %r55, %r56, %r58;
	mov.b32 	%f71, %r78;
	add.f32 	%f72, %f70, %f71;
	mov.b32 	%r79, %f72;
	shfl.sync.down.b32 	%r80|%p25, %r79, %r69, %r56, %r58;
	mov.b32 	%f73, %r80;
	add.f32 	%f81, %f72, %f73;

$L__BB0_10:
	setp.ne.s32 	%p26, %r2, 0;
	@%p26 bra 	$L__BB0_12;

	cvta.to.global.u64 	%rd32, %rd4;
	atom.global.add.f32 	%f74, [%rd32], %f80;
	cvta.to.global.u64 	%rd33, %rd5;
	atom.global.add.f32 	%f75, [%rd33], %f81;

$L__BB0_12:
	ret;

}

`
 )
