package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgGSumSqFR kernel
var cgGSumSqFR_code cu.Function

// Stores the arguments for cgGSumSqFR kernel invocation
type cgGSumSqFR_args_t struct{
	 arg_g_out unsafe.Pointer
	 arg_mhx unsafe.Pointer
	 arg_mhy unsafe.Pointer
	 arg_mhz unsafe.Pointer
	 arg_msv unsafe.Pointer
	 arg_N int
	 argptr [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgGSumSqFR kernel invocation
var cgGSumSqFR_args cgGSumSqFR_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgGSumSqFR_args.argptr[0] = unsafe.Pointer(&cgGSumSqFR_args.arg_g_out)
	 cgGSumSqFR_args.argptr[1] = unsafe.Pointer(&cgGSumSqFR_args.arg_mhx)
	 cgGSumSqFR_args.argptr[2] = unsafe.Pointer(&cgGSumSqFR_args.arg_mhy)
	 cgGSumSqFR_args.argptr[3] = unsafe.Pointer(&cgGSumSqFR_args.arg_mhz)
	 cgGSumSqFR_args.argptr[4] = unsafe.Pointer(&cgGSumSqFR_args.arg_msv)
	 cgGSumSqFR_args.argptr[5] = unsafe.Pointer(&cgGSumSqFR_args.arg_N)
	 }

// Wrapper for cgGSumSqFR CUDA kernel, asynchronous.
func k_cgGSumSqFR_async ( g_out unsafe.Pointer, mhx unsafe.Pointer, mhy unsafe.Pointer, mhz unsafe.Pointer, msv unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgGSumSqFR")
	}

	cgGSumSqFR_args.Lock()
	defer cgGSumSqFR_args.Unlock()

	if cgGSumSqFR_code == 0{
		cgGSumSqFR_code = fatbinLoad(cgGSumSqFR_map, "cgGSumSqFR")
	}

	 cgGSumSqFR_args.arg_g_out = g_out
	 cgGSumSqFR_args.arg_mhx = mhx
	 cgGSumSqFR_args.arg_mhy = mhy
	 cgGSumSqFR_args.arg_mhz = mhz
	 cgGSumSqFR_args.arg_msv = msv
	 cgGSumSqFR_args.arg_N = N
	

	args := cgGSumSqFR_args.argptr[:]
	cu.LaunchKernel(cgGSumSqFR_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgGSumSqFR")
	}
}

// maps compute capability on PTX code for cgGSumSqFR kernel.
var cgGSumSqFR_map = map[int]string{ 0: "" ,
61: cgGSumSqFR_ptx_61  }

// cgGSumSqFR PTX code for various compute capabilities.
const(
  cgGSumSqFR_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgGSumSqFR

.visible .entry cgGSumSqFR(
	.param .u64 cgGSumSqFR_param_0,
	.param .u64 cgGSumSqFR_param_1,
	.param .u64 cgGSumSqFR_param_2,
	.param .u64 cgGSumSqFR_param_3,
	.param .u64 cgGSumSqFR_param_4,
	.param .u32 cgGSumSqFR_param_5
)
{
	.reg .pred 	%p<17>;
	.reg .f32 	%f<42>;
	.reg .b32 	%r<53>;
	.reg .b64 	%rd<18>;
	// demoted variable
	.shared .align 4 .b8 _ZZ10cgGSumSqFRE4smem[128];

	ld.param.u64 	%rd2, [cgGSumSqFR_param_0];
	ld.param.u64 	%rd3, [cgGSumSqFR_param_1];
	ld.param.u64 	%rd4, [cgGSumSqFR_param_2];
	ld.param.u64 	%rd5, [cgGSumSqFR_param_3];
	ld.param.u64 	%rd6, [cgGSumSqFR_param_4];
	ld.param.u32 	%r5, [cgGSumSqFR_param_5];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r6, %nctaid.x;
	mov.u32 	%r7, %ctaid.y;
	mov.u32 	%r8, %ctaid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r3, %r9, %r1, %r2;
	setp.ge.s32 	%p1, %r3, %r5;
	mov.f32 	%f39, 0f00000000;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd7, %rd6;
	cvt.s64.s32 	%rd1, %r3;
	mul.wide.s32 	%rd8, %r3, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.f32 	%f1, [%rd9];
	setp.eq.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd3;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f11, [%rd12];
	cvta.to.global.u64 	%rd13, %rd4;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.f32 	%f12, [%rd14];
	mul.f32 	%f13, %f12, %f12;
	fma.rn.f32 	%f14, %f11, %f11, %f13;
	cvta.to.global.u64 	%rd15, %rd5;
	add.s64 	%rd16, %rd15, %rd11;
	ld.global.f32 	%f15, [%rd16];
	fma.rn.f32 	%f16, %f15, %f15, %f14;
	mul.f32 	%f17, %f1, %f1;
	mul.f32 	%f39, %f17, %f16;

$L__BB0_3:
	mov.b32 	%r10, %f39;
	mov.u32 	%r11, 2;
	mov.u32 	%r12, 31;
	mov.u32 	%r13, 16;
	mov.u32 	%r14, -1;
	shfl.sync.down.b32 	%r15|%p3, %r10, %r13, %r12, %r14;
	mov.b32 	%f18, %r15;
	add.f32 	%f19, %f39, %f18;
	mov.b32 	%r16, %f19;
	mov.u32 	%r17, 8;
	shfl.sync.down.b32 	%r18|%p4, %r16, %r17, %r12, %r14;
	mov.b32 	%f20, %r18;
	add.f32 	%f21, %f19, %f20;
	mov.b32 	%r19, %f21;
	mov.u32 	%r20, 4;
	shfl.sync.down.b32 	%r21|%p5, %r19, %r20, %r12, %r14;
	mov.b32 	%f22, %r21;
	add.f32 	%f23, %f21, %f22;
	mov.b32 	%r22, %f23;
	shfl.sync.down.b32 	%r23|%p6, %r22, %r11, %r12, %r14;
	mov.b32 	%f24, %r23;
	add.f32 	%f25, %f23, %f24;
	mov.b32 	%r24, %f25;
	mov.u32 	%r25, 1;
	shfl.sync.down.b32 	%r26|%p7, %r24, %r25, %r12, %r14;
	mov.b32 	%f26, %r26;
	add.f32 	%f4, %f25, %f26;
	shr.u32 	%r4, %r2, 5;
	and.b32  	%r27, %r2, 31;
	setp.ne.s32 	%p8, %r27, 0;
	@%p8 bra 	$L__BB0_5;

	shl.b32 	%r28, %r4, 2;
	mov.u32 	%r29, _ZZ10cgGSumSqFRE4smem;
	add.s32 	%r30, %r29, %r28;
	st.shared.f32 	[%r30], %f4;

$L__BB0_5:
	bar.sync 	0;
	add.s32 	%r31, %r1, 31;
	shr.u32 	%r32, %r31, 5;
	setp.ge.u32 	%p9, %r2, %r32;
	mov.f32 	%f41, 0f00000000;
	@%p9 bra 	$L__BB0_7;

	shl.b32 	%r33, %r2, 2;
	mov.u32 	%r34, _ZZ10cgGSumSqFRE4smem;
	add.s32 	%r35, %r34, %r33;
	ld.shared.f32 	%f41, [%r35];

$L__BB0_7:
	setp.ne.s32 	%p10, %r4, 0;
	@%p10 bra 	$L__BB0_9;

	mov.b32 	%r36, %f41;
	mov.u32 	%r37, 2;
	mov.u32 	%r38, 31;
	mov.u32 	%r39, 16;
	mov.u32 	%r40, -1;
	shfl.sync.down.b32 	%r41|%p11, %r36, %r39, %r38, %r40;
	mov.b32 	%f28, %r41;
	add.f32 	%f29, %f41, %f28;
	mov.b32 	%r42, %f29;
	mov.u32 	%r43, 8;
	shfl.sync.down.b32 	%r44|%p12, %r42, %r43, %r38, %r40;
	mov.b32 	%f30, %r44;
	add.f32 	%f31, %f29, %f30;
	mov.b32 	%r45, %f31;
	mov.u32 	%r46, 4;
	shfl.sync.down.b32 	%r47|%p13, %r45, %r46, %r38, %r40;
	mov.b32 	%f32, %r47;
	add.f32 	%f33, %f31, %f32;
	mov.b32 	%r48, %f33;
	shfl.sync.down.b32 	%r49|%p14, %r48, %r37, %r38, %r40;
	mov.b32 	%f34, %r49;
	add.f32 	%f35, %f33, %f34;
	mov.b32 	%r50, %f35;
	mov.u32 	%r51, 1;
	shfl.sync.down.b32 	%r52|%p15, %r50, %r51, %r38, %r40;
	mov.b32 	%f36, %r52;
	add.f32 	%f41, %f35, %f36;

$L__BB0_9:
	setp.ne.s32 	%p16, %r2, 0;
	@%p16 bra 	$L__BB0_11;

	cvta.to.global.u64 	%rd17, %rd2;
	atom.global.add.f32 	%f37, [%rd17], %f41;

$L__BB0_11:
	ret;

}

`
 )
