package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgSpinStep kernel
var cgSpinStep_code cu.Function

// Stores the arguments for cgSpinStep kernel invocation
type cgSpinStep_args_t struct{
	 arg_ox unsafe.Pointer
	 arg_oy unsafe.Pointer
	 arg_oz unsafe.Pointer
	 arg_sx unsafe.Pointer
	 arg_sy unsafe.Pointer
	 arg_sz unsafe.Pointer
	 arg_dx unsafe.Pointer
	 arg_dy unsafe.Pointer
	 arg_dz unsafe.Pointer
	 arg_t0sq float32
	 arg_dvec_scale float32
	 arg_N int
	 argptr [12]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgSpinStep kernel invocation
var cgSpinStep_args cgSpinStep_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgSpinStep_args.argptr[0] = unsafe.Pointer(&cgSpinStep_args.arg_ox)
	 cgSpinStep_args.argptr[1] = unsafe.Pointer(&cgSpinStep_args.arg_oy)
	 cgSpinStep_args.argptr[2] = unsafe.Pointer(&cgSpinStep_args.arg_oz)
	 cgSpinStep_args.argptr[3] = unsafe.Pointer(&cgSpinStep_args.arg_sx)
	 cgSpinStep_args.argptr[4] = unsafe.Pointer(&cgSpinStep_args.arg_sy)
	 cgSpinStep_args.argptr[5] = unsafe.Pointer(&cgSpinStep_args.arg_sz)
	 cgSpinStep_args.argptr[6] = unsafe.Pointer(&cgSpinStep_args.arg_dx)
	 cgSpinStep_args.argptr[7] = unsafe.Pointer(&cgSpinStep_args.arg_dy)
	 cgSpinStep_args.argptr[8] = unsafe.Pointer(&cgSpinStep_args.arg_dz)
	 cgSpinStep_args.argptr[9] = unsafe.Pointer(&cgSpinStep_args.arg_t0sq)
	 cgSpinStep_args.argptr[10] = unsafe.Pointer(&cgSpinStep_args.arg_dvec_scale)
	 cgSpinStep_args.argptr[11] = unsafe.Pointer(&cgSpinStep_args.arg_N)
	 }

// Wrapper for cgSpinStep CUDA kernel, asynchronous.
func k_cgSpinStep_async ( ox unsafe.Pointer, oy unsafe.Pointer, oz unsafe.Pointer, sx unsafe.Pointer, sy unsafe.Pointer, sz unsafe.Pointer, dx unsafe.Pointer, dy unsafe.Pointer, dz unsafe.Pointer, t0sq float32, dvec_scale float32, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgSpinStep")
	}

	cgSpinStep_args.Lock()
	defer cgSpinStep_args.Unlock()

	if cgSpinStep_code == 0{
		cgSpinStep_code = fatbinLoad(cgSpinStep_map, "cgSpinStep")
	}

	 cgSpinStep_args.arg_ox = ox
	 cgSpinStep_args.arg_oy = oy
	 cgSpinStep_args.arg_oz = oz
	 cgSpinStep_args.arg_sx = sx
	 cgSpinStep_args.arg_sy = sy
	 cgSpinStep_args.arg_sz = sz
	 cgSpinStep_args.arg_dx = dx
	 cgSpinStep_args.arg_dy = dy
	 cgSpinStep_args.arg_dz = dz
	 cgSpinStep_args.arg_t0sq = t0sq
	 cgSpinStep_args.arg_dvec_scale = dvec_scale
	 cgSpinStep_args.arg_N = N
	

	args := cgSpinStep_args.argptr[:]
	cu.LaunchKernel(cgSpinStep_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgSpinStep")
	}
}

// maps compute capability on PTX code for cgSpinStep kernel.
var cgSpinStep_map = map[int]string{ 0: "" ,
61: cgSpinStep_ptx_61  }

// cgSpinStep PTX code for various compute capabilities.
const(
  cgSpinStep_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgSpinStep

.visible .entry cgSpinStep(
	.param .u64 cgSpinStep_param_0,
	.param .u64 cgSpinStep_param_1,
	.param .u64 cgSpinStep_param_2,
	.param .u64 cgSpinStep_param_3,
	.param .u64 cgSpinStep_param_4,
	.param .u64 cgSpinStep_param_5,
	.param .u64 cgSpinStep_param_6,
	.param .u64 cgSpinStep_param_7,
	.param .u64 cgSpinStep_param_8,
	.param .f32 cgSpinStep_param_9,
	.param .f32 cgSpinStep_param_10,
	.param .u32 cgSpinStep_param_11
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<39>;
	.reg .b32 	%r<10>;
	.reg .b64 	%rd<43>;


	ld.param.u64 	%rd14, [cgSpinStep_param_0];
	ld.param.u64 	%rd15, [cgSpinStep_param_1];
	ld.param.u64 	%rd16, [cgSpinStep_param_2];
	ld.param.u64 	%rd8, [cgSpinStep_param_3];
	ld.param.u64 	%rd9, [cgSpinStep_param_4];
	ld.param.u64 	%rd10, [cgSpinStep_param_5];
	ld.param.u64 	%rd11, [cgSpinStep_param_6];
	ld.param.u64 	%rd12, [cgSpinStep_param_7];
	ld.param.u64 	%rd13, [cgSpinStep_param_8];
	ld.param.f32 	%f13, [cgSpinStep_param_9];
	ld.param.f32 	%f14, [cgSpinStep_param_10];
	ld.param.u32 	%r2, [cgSpinStep_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_8;

	cvta.to.global.u64 	%rd17, %rd11;
	cvt.s64.s32 	%rd4, %r1;
	mul.wide.s32 	%rd18, %r1, 4;
	add.s64 	%rd19, %rd17, %rd18;
	cvta.to.global.u64 	%rd20, %rd12;
	add.s64 	%rd21, %rd20, %rd18;
	cvta.to.global.u64 	%rd22, %rd13;
	add.s64 	%rd23, %rd22, %rd18;
	ld.global.f32 	%f1, [%rd19];
	ld.global.f32 	%f2, [%rd21];
	mul.f32 	%f15, %f2, %f2;
	fma.rn.f32 	%f16, %f1, %f1, %f15;
	ld.global.f32 	%f3, [%rd23];
	fma.rn.f32 	%f4, %f3, %f3, %f16;
	setp.lt.f32 	%p2, %f4, 0f1E3CE508;
	cvta.to.global.u64 	%rd24, %rd8;
	add.s64 	%rd5, %rd24, %rd18;
	cvta.to.global.u64 	%rd25, %rd9;
	add.s64 	%rd6, %rd25, %rd18;
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd7, %rd26, %rd18;
	@%p2 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_2;

$L__BB0_7:
	ld.global.f32 	%f36, [%rd5];
	shl.b64 	%rd39, %rd4, 2;
	add.s64 	%rd40, %rd3, %rd39;
	st.global.f32 	[%rd40], %f36;
	ld.global.f32 	%f37, [%rd6];
	add.s64 	%rd41, %rd2, %rd39;
	st.global.f32 	[%rd41], %f37;
	ld.global.f32 	%f38, [%rd7];
	add.s64 	%rd42, %rd1, %rd39;
	st.global.f32 	[%rd42], %f38;
	bra.uni 	$L__BB0_8;

$L__BB0_2:
	fma.rn.f32 	%f17, %f4, %f13, 0f3F800000;
	sqrt.rn.f32 	%f18, %f17;
	ld.global.f32 	%f5, [%rd5];
	mul.f32 	%f19, %f18, %f5;
	fma.rn.f32 	%f6, %f1, %f14, %f19;
	ld.global.f32 	%f7, [%rd6];
	mul.f32 	%f20, %f18, %f7;
	fma.rn.f32 	%f8, %f2, %f14, %f20;
	ld.global.f32 	%f9, [%rd7];
	mul.f32 	%f21, %f18, %f9;
	fma.rn.f32 	%f10, %f3, %f14, %f21;
	mul.f32 	%f22, %f8, %f8;
	fma.rn.f32 	%f23, %f6, %f6, %f22;
	fma.rn.f32 	%f11, %f10, %f10, %f23;
	setp.gt.f32 	%p3, %f11, 0f1E3CE508;
	@%p3 bra 	$L__BB0_6;
	bra.uni 	$L__BB0_3;

$L__BB0_6:
	rsqrt.approx.f32 	%f32, %f11;
	mul.f32 	%f33, %f6, %f32;
	shl.b64 	%rd35, %rd4, 2;
	add.s64 	%rd36, %rd3, %rd35;
	st.global.f32 	[%rd36], %f33;
	mul.f32 	%f34, %f8, %f32;
	add.s64 	%rd37, %rd2, %rd35;
	st.global.f32 	[%rd37], %f34;
	mul.f32 	%f35, %f10, %f32;
	add.s64 	%rd38, %rd1, %rd35;
	st.global.f32 	[%rd38], %f35;
	bra.uni 	$L__BB0_8;

$L__BB0_3:
	mul.f32 	%f24, %f7, %f7;
	fma.rn.f32 	%f25, %f5, %f5, %f24;
	fma.rn.f32 	%f12, %f9, %f9, %f25;
	setp.gt.f32 	%p4, %f12, 0f00000000;
	@%p4 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_4;

$L__BB0_5:
	rsqrt.approx.f32 	%f26, %f12;
	mul.f32 	%f27, %f26, %f5;
	shl.b64 	%rd31, %rd4, 2;
	add.s64 	%rd32, %rd3, %rd31;
	st.global.f32 	[%rd32], %f27;
	ld.global.f32 	%f28, [%rd6];
	mul.f32 	%f29, %f26, %f28;
	add.s64 	%rd33, %rd2, %rd31;
	st.global.f32 	[%rd33], %f29;
	ld.global.f32 	%f30, [%rd7];
	mul.f32 	%f31, %f26, %f30;
	add.s64 	%rd34, %rd1, %rd31;
	st.global.f32 	[%rd34], %f31;
	bra.uni 	$L__BB0_8;

$L__BB0_4:
	shl.b64 	%rd27, %rd4, 2;
	add.s64 	%rd28, %rd3, %rd27;
	mov.u32 	%r9, 0;
	st.global.u32 	[%rd28], %r9;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.u32 	[%rd29], %r9;
	add.s64 	%rd30, %rd1, %rd27;
	st.global.u32 	[%rd30], %r9;

$L__BB0_8:
	ret;

}

`
 )
