package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for cgUpdateDir kernel
var cgUpdateDir_code cu.Function

// Stores the arguments for cgUpdateDir kernel invocation
type cgUpdateDir_args_t struct{
	 arg_dirx unsafe.Pointer
	 arg_diry unsafe.Pointer
	 arg_dirz unsafe.Pointer
	 arg_mhx unsafe.Pointer
	 arg_mhy unsafe.Pointer
	 arg_mhz unsafe.Pointer
	 arg_spx unsafe.Pointer
	 arg_spy unsafe.Pointer
	 arg_spz unsafe.Pointer
	 arg_msv unsafe.Pointer
	 arg_gamma float32
	 arg_g_maxmagsq unsafe.Pointer
	 arg_g_normsumsq unsafe.Pointer
	 arg_g_ep_raw unsafe.Pointer
	 arg_g_gradsumsq_raw unsafe.Pointer
	 arg_N int
	 argptr [16]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for cgUpdateDir kernel invocation
var cgUpdateDir_args cgUpdateDir_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 cgUpdateDir_args.argptr[0] = unsafe.Pointer(&cgUpdateDir_args.arg_dirx)
	 cgUpdateDir_args.argptr[1] = unsafe.Pointer(&cgUpdateDir_args.arg_diry)
	 cgUpdateDir_args.argptr[2] = unsafe.Pointer(&cgUpdateDir_args.arg_dirz)
	 cgUpdateDir_args.argptr[3] = unsafe.Pointer(&cgUpdateDir_args.arg_mhx)
	 cgUpdateDir_args.argptr[4] = unsafe.Pointer(&cgUpdateDir_args.arg_mhy)
	 cgUpdateDir_args.argptr[5] = unsafe.Pointer(&cgUpdateDir_args.arg_mhz)
	 cgUpdateDir_args.argptr[6] = unsafe.Pointer(&cgUpdateDir_args.arg_spx)
	 cgUpdateDir_args.argptr[7] = unsafe.Pointer(&cgUpdateDir_args.arg_spy)
	 cgUpdateDir_args.argptr[8] = unsafe.Pointer(&cgUpdateDir_args.arg_spz)
	 cgUpdateDir_args.argptr[9] = unsafe.Pointer(&cgUpdateDir_args.arg_msv)
	 cgUpdateDir_args.argptr[10] = unsafe.Pointer(&cgUpdateDir_args.arg_gamma)
	 cgUpdateDir_args.argptr[11] = unsafe.Pointer(&cgUpdateDir_args.arg_g_maxmagsq)
	 cgUpdateDir_args.argptr[12] = unsafe.Pointer(&cgUpdateDir_args.arg_g_normsumsq)
	 cgUpdateDir_args.argptr[13] = unsafe.Pointer(&cgUpdateDir_args.arg_g_ep_raw)
	 cgUpdateDir_args.argptr[14] = unsafe.Pointer(&cgUpdateDir_args.arg_g_gradsumsq_raw)
	 cgUpdateDir_args.argptr[15] = unsafe.Pointer(&cgUpdateDir_args.arg_N)
	 }

// Wrapper for cgUpdateDir CUDA kernel, asynchronous.
func k_cgUpdateDir_async ( dirx unsafe.Pointer, diry unsafe.Pointer, dirz unsafe.Pointer, mhx unsafe.Pointer, mhy unsafe.Pointer, mhz unsafe.Pointer, spx unsafe.Pointer, spy unsafe.Pointer, spz unsafe.Pointer, msv unsafe.Pointer, gamma float32, g_maxmagsq unsafe.Pointer, g_normsumsq unsafe.Pointer, g_ep_raw unsafe.Pointer, g_gradsumsq_raw unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("cgUpdateDir")
	}

	cgUpdateDir_args.Lock()
	defer cgUpdateDir_args.Unlock()

	if cgUpdateDir_code == 0{
		cgUpdateDir_code = fatbinLoad(cgUpdateDir_map, "cgUpdateDir")
	}

	 cgUpdateDir_args.arg_dirx = dirx
	 cgUpdateDir_args.arg_diry = diry
	 cgUpdateDir_args.arg_dirz = dirz
	 cgUpdateDir_args.arg_mhx = mhx
	 cgUpdateDir_args.arg_mhy = mhy
	 cgUpdateDir_args.arg_mhz = mhz
	 cgUpdateDir_args.arg_spx = spx
	 cgUpdateDir_args.arg_spy = spy
	 cgUpdateDir_args.arg_spz = spz
	 cgUpdateDir_args.arg_msv = msv
	 cgUpdateDir_args.arg_gamma = gamma
	 cgUpdateDir_args.arg_g_maxmagsq = g_maxmagsq
	 cgUpdateDir_args.arg_g_normsumsq = g_normsumsq
	 cgUpdateDir_args.arg_g_ep_raw = g_ep_raw
	 cgUpdateDir_args.arg_g_gradsumsq_raw = g_gradsumsq_raw
	 cgUpdateDir_args.arg_N = N
	

	args := cgUpdateDir_args.argptr[:]
	cu.LaunchKernel(cgUpdateDir_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("cgUpdateDir")
	}
}

// maps compute capability on PTX code for cgUpdateDir kernel.
var cgUpdateDir_map = map[int]string{ 0: "" ,
61: cgUpdateDir_ptx_61  }

// cgUpdateDir PTX code for various compute capabilities.
const(
  cgUpdateDir_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	cgUpdateDir

.visible .entry cgUpdateDir(
	.param .u64 cgUpdateDir_param_0,
	.param .u64 cgUpdateDir_param_1,
	.param .u64 cgUpdateDir_param_2,
	.param .u64 cgUpdateDir_param_3,
	.param .u64 cgUpdateDir_param_4,
	.param .u64 cgUpdateDir_param_5,
	.param .u64 cgUpdateDir_param_6,
	.param .u64 cgUpdateDir_param_7,
	.param .u64 cgUpdateDir_param_8,
	.param .u64 cgUpdateDir_param_9,
	.param .f32 cgUpdateDir_param_10,
	.param .u64 cgUpdateDir_param_11,
	.param .u64 cgUpdateDir_param_12,
	.param .u64 cgUpdateDir_param_13,
	.param .u64 cgUpdateDir_param_14,
	.param .u32 cgUpdateDir_param_15
)
{
	.reg .pred 	%p<68>;
	.reg .f32 	%f<105>;
	.reg .b32 	%r<168>;
	.reg .f64 	%fd<83>;
	.reg .b64 	%rd<43>;
	// demoted variable
	.shared .align 4 .b8 _ZZ11cgUpdateDirE3smm[128];
	// demoted variable
	.shared .align 4 .b8 _ZZ11cgUpdateDirE3sns[128];
	// demoted variable
	.shared .align 8 .b8 _ZZ11cgUpdateDirE3sep[256];
	// demoted variable
	.shared .align 8 .b8 _ZZ11cgUpdateDirE3sgs[256];

	ld.param.u64 	%rd5, [cgUpdateDir_param_0];
	ld.param.u64 	%rd6, [cgUpdateDir_param_1];
	ld.param.u64 	%rd7, [cgUpdateDir_param_2];
	ld.param.u64 	%rd8, [cgUpdateDir_param_3];
	ld.param.u64 	%rd9, [cgUpdateDir_param_4];
	ld.param.u64 	%rd10, [cgUpdateDir_param_5];
	ld.param.u64 	%rd11, [cgUpdateDir_param_6];
	ld.param.u64 	%rd12, [cgUpdateDir_param_7];
	ld.param.u64 	%rd13, [cgUpdateDir_param_8];
	ld.param.u64 	%rd14, [cgUpdateDir_param_9];
	ld.param.f32 	%f33, [cgUpdateDir_param_10];
	ld.param.u64 	%rd15, [cgUpdateDir_param_11];
	ld.param.u64 	%rd16, [cgUpdateDir_param_12];
	ld.param.u64 	%rd17, [cgUpdateDir_param_13];
	ld.param.u64 	%rd18, [cgUpdateDir_param_14];
	ld.param.u32 	%r5, [cgUpdateDir_param_15];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r6, %nctaid.x;
	mov.u32 	%r7, %ctaid.y;
	mov.u32 	%r8, %ctaid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r3, %r9, %r1, %r2;
	setp.ge.s32 	%p1, %r3, %r5;
	mov.f64 	%fd77, 0d0000000000000000;
	mov.f32 	%f100, 0f00000000;
	mov.f64 	%fd78, %fd77;
	@%p1 bra 	$L__BB0_6;

	cvta.to.global.u64 	%rd19, %rd14;
	cvt.s64.s32 	%rd1, %r3;
	mul.wide.s32 	%rd20, %r3, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.f32 	%f1, [%rd21];
	setp.eq.f32 	%p2, %f1, 0f00000000;
	mov.f32 	%f100, 0f00000000;
	cvta.to.global.u64 	%rd22, %rd5;
	add.s64 	%rd2, %rd22, %rd20;
	cvta.to.global.u64 	%rd23, %rd6;
	add.s64 	%rd3, %rd23, %rd20;
	cvta.to.global.u64 	%rd24, %rd7;
	add.s64 	%rd4, %rd24, %rd20;
	mov.f64 	%fd77, 0d0000000000000000;
	mov.f32 	%f97, %f100;
	mov.f32 	%f98, %f100;
	mov.f32 	%f99, %f100;
	@%p2 bra 	$L__BB0_5;

	cvta.to.global.u64 	%rd25, %rd8;
	shl.b64 	%rd26, %rd1, 2;
	add.s64 	%rd27, %rd25, %rd26;
	ld.global.f32 	%f2, [%rd27];
	mul.f32 	%f93, %f1, %f2;
	cvta.to.global.u64 	%rd28, %rd9;
	add.s64 	%rd29, %rd28, %rd26;
	ld.global.f32 	%f4, [%rd29];
	mul.f32 	%f94, %f1, %f4;
	cvta.to.global.u64 	%rd30, %rd10;
	add.s64 	%rd31, %rd30, %rd26;
	ld.global.f32 	%f6, [%rd31];
	mul.f32 	%f95, %f1, %f6;
	setp.eq.f32 	%p3, %f33, 0f00000000;
	@%p3 bra 	$L__BB0_4;

	ld.global.f32 	%f39, [%rd2];
	fma.rn.f32 	%f93, %f39, %f33, %f93;
	ld.global.f32 	%f40, [%rd3];
	fma.rn.f32 	%f94, %f40, %f33, %f94;
	ld.global.f32 	%f41, [%rd4];
	fma.rn.f32 	%f95, %f41, %f33, %f95;

$L__BB0_4:
	cvta.to.global.u64 	%rd32, %rd11;
	add.s64 	%rd34, %rd32, %rd26;
	ld.global.f32 	%f42, [%rd34];
	cvta.to.global.u64 	%rd35, %rd12;
	add.s64 	%rd36, %rd35, %rd26;
	ld.global.f32 	%f43, [%rd36];
	mul.f32 	%f44, %f94, %f43;
	fma.rn.f32 	%f45, %f93, %f42, %f44;
	cvta.to.global.u64 	%rd37, %rd13;
	add.s64 	%rd38, %rd37, %rd26;
	ld.global.f32 	%f46, [%rd38];
	fma.rn.f32 	%f47, %f95, %f46, %f45;
	mul.f32 	%f48, %f42, %f47;
	sub.f32 	%f97, %f93, %f48;
	mul.f32 	%f49, %f43, %f47;
	sub.f32 	%f98, %f94, %f49;
	mul.f32 	%f50, %f46, %f47;
	sub.f32 	%f99, %f95, %f50;
	mul.f32 	%f51, %f98, %f98;
	fma.rn.f32 	%f52, %f97, %f97, %f51;
	fma.rn.f32 	%f100, %f99, %f99, %f52;
	cvt.f64.f32 	%fd21, %f97;
	cvt.f64.f32 	%fd22, %f98;
	cvt.f64.f32 	%fd23, %f99;
	cvt.f64.f32 	%fd24, %f2;
	cvt.f64.f32 	%fd25, %f4;
	mul.f64 	%fd26, %fd25, %fd22;
	fma.rn.f64 	%fd27, %fd24, %fd21, %fd26;
	cvt.f64.f32 	%fd28, %f6;
	fma.rn.f64 	%fd29, %fd28, %fd23, %fd27;
	cvt.f64.f32 	%fd30, %f1;
	mul.f64 	%fd77, %fd29, %fd30;
	mul.f64 	%fd31, %fd25, %fd25;
	fma.rn.f64 	%fd32, %fd24, %fd24, %fd31;
	fma.rn.f64 	%fd33, %fd28, %fd28, %fd32;
	mul.f64 	%fd34, %fd30, %fd30;
	mul.f64 	%fd78, %fd34, %fd33;

$L__BB0_5:
	st.global.f32 	[%rd2], %f97;
	st.global.f32 	[%rd3], %f98;
	st.global.f32 	[%rd4], %f99;

$L__BB0_6:
	mov.b32 	%r10, %f100;
	mov.u32 	%r11, 2;
	mov.u32 	%r12, 31;
	mov.u32 	%r13, 16;
	mov.u32 	%r14, -1;
	shfl.sync.down.b32 	%r15|%p4, %r10, %r13, %r12, %r14;
	mov.b32 	%f53, %r15;
	max.f32 	%f54, %f100, %f53;
	mov.b32 	%r16, %f54;
	mov.u32 	%r17, 8;
	shfl.sync.down.b32 	%r18|%p5, %r16, %r17, %r12, %r14;
	mov.b32 	%f55, %r18;
	max.f32 	%f56, %f54, %f55;
	mov.b32 	%r19, %f56;
	mov.u32 	%r20, 4;
	shfl.sync.down.b32 	%r21|%p6, %r19, %r20, %r12, %r14;
	mov.b32 	%f57, %r21;
	max.f32 	%f58, %f56, %f57;
	mov.b32 	%r22, %f58;
	shfl.sync.down.b32 	%r23|%p7, %r22, %r11, %r12, %r14;
	mov.b32 	%f59, %r23;
	max.f32 	%f60, %f58, %f59;
	mov.b32 	%r24, %f60;
	mov.u32 	%r25, 1;
	shfl.sync.down.b32 	%r26|%p8, %r24, %r25, %r12, %r14;
	mov.b32 	%f61, %r26;
	max.f32 	%f23, %f60, %f61;
	shfl.sync.down.b32 	%r27|%p9, %r10, %r13, %r12, %r14;
	mov.b32 	%f62, %r27;
	add.f32 	%f63, %f100, %f62;
	mov.b32 	%r28, %f63;
	shfl.sync.down.b32 	%r29|%p10, %r28, %r17, %r12, %r14;
	mov.b32 	%f64, %r29;
	add.f32 	%f65, %f63, %f64;
	mov.b32 	%r30, %f65;
	shfl.sync.down.b32 	%r31|%p11, %r30, %r20, %r12, %r14;
	mov.b32 	%f66, %r31;
	add.f32 	%f67, %f65, %f66;
	mov.b32 	%r32, %f67;
	shfl.sync.down.b32 	%r33|%p12, %r32, %r11, %r12, %r14;
	mov.b32 	%f68, %r33;
	add.f32 	%f69, %f67, %f68;
	mov.b32 	%r34, %f69;
	shfl.sync.down.b32 	%r35|%p13, %r34, %r25, %r12, %r14;
	mov.b32 	%f70, %r35;
	add.f32 	%f24, %f69, %f70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r36, %temp}, %fd77;
	}
	shfl.sync.down.b32 	%r37|%p14, %r36, %r13, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r38}, %fd77;
	}
	shfl.sync.down.b32 	%r39|%p15, %r38, %r13, %r12, %r14;
	mov.b64 	%fd35, {%r37, %r39};
	add.f64 	%fd36, %fd77, %fd35;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r40, %temp}, %fd36;
	}
	shfl.sync.down.b32 	%r41|%p16, %r40, %r17, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r42}, %fd36;
	}
	shfl.sync.down.b32 	%r43|%p17, %r42, %r17, %r12, %r14;
	mov.b64 	%fd37, {%r41, %r43};
	add.f64 	%fd38, %fd36, %fd37;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r44, %temp}, %fd38;
	}
	shfl.sync.down.b32 	%r45|%p18, %r44, %r20, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r46}, %fd38;
	}
	shfl.sync.down.b32 	%r47|%p19, %r46, %r20, %r12, %r14;
	mov.b64 	%fd39, {%r45, %r47};
	add.f64 	%fd40, %fd38, %fd39;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r48, %temp}, %fd40;
	}
	shfl.sync.down.b32 	%r49|%p20, %r48, %r11, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r50}, %fd40;
	}
	shfl.sync.down.b32 	%r51|%p21, %r50, %r11, %r12, %r14;
	mov.b64 	%fd41, {%r49, %r51};
	add.f64 	%fd42, %fd40, %fd41;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r52, %temp}, %fd42;
	}
	shfl.sync.down.b32 	%r53|%p22, %r52, %r25, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r54}, %fd42;
	}
	shfl.sync.down.b32 	%r55|%p23, %r54, %r25, %r12, %r14;
	mov.b64 	%fd43, {%r53, %r55};
	add.f64 	%fd7, %fd42, %fd43;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r56, %temp}, %fd78;
	}
	shfl.sync.down.b32 	%r57|%p24, %r56, %r13, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r58}, %fd78;
	}
	shfl.sync.down.b32 	%r59|%p25, %r58, %r13, %r12, %r14;
	mov.b64 	%fd44, {%r57, %r59};
	add.f64 	%fd45, %fd78, %fd44;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r60, %temp}, %fd45;
	}
	shfl.sync.down.b32 	%r61|%p26, %r60, %r17, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r62}, %fd45;
	}
	shfl.sync.down.b32 	%r63|%p27, %r62, %r17, %r12, %r14;
	mov.b64 	%fd46, {%r61, %r63};
	add.f64 	%fd47, %fd45, %fd46;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r64, %temp}, %fd47;
	}
	shfl.sync.down.b32 	%r65|%p28, %r64, %r20, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r66}, %fd47;
	}
	shfl.sync.down.b32 	%r67|%p29, %r66, %r20, %r12, %r14;
	mov.b64 	%fd48, {%r65, %r67};
	add.f64 	%fd49, %fd47, %fd48;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r68, %temp}, %fd49;
	}
	shfl.sync.down.b32 	%r69|%p30, %r68, %r11, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r70}, %fd49;
	}
	shfl.sync.down.b32 	%r71|%p31, %r70, %r11, %r12, %r14;
	mov.b64 	%fd50, {%r69, %r71};
	add.f64 	%fd51, %fd49, %fd50;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r72, %temp}, %fd51;
	}
	shfl.sync.down.b32 	%r73|%p32, %r72, %r25, %r12, %r14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r74}, %fd51;
	}
	shfl.sync.down.b32 	%r75|%p33, %r74, %r25, %r12, %r14;
	mov.b64 	%fd52, {%r73, %r75};
	add.f64 	%fd8, %fd51, %fd52;
	shr.u32 	%r4, %r2, 5;
	and.b32  	%r76, %r2, 31;
	setp.ne.s32 	%p34, %r76, 0;
	@%p34 bra 	$L__BB0_8;

	shl.b32 	%r77, %r4, 2;
	mov.u32 	%r78, _ZZ11cgUpdateDirE3smm;
	add.s32 	%r79, %r78, %r77;
	st.shared.f32 	[%r79], %f23;
	mov.u32 	%r80, _ZZ11cgUpdateDirE3sns;
	add.s32 	%r81, %r80, %r77;
	st.shared.f32 	[%r81], %f24;
	shl.b32 	%r82, %r4, 3;
	mov.u32 	%r83, _ZZ11cgUpdateDirE3sep;
	add.s32 	%r84, %r83, %r82;
	st.shared.f64 	[%r84], %fd7;
	mov.u32 	%r85, _ZZ11cgUpdateDirE3sgs;
	add.s32 	%r86, %r85, %r82;
	st.shared.f64 	[%r86], %fd8;

$L__BB0_8:
	bar.sync 	0;
	add.s32 	%r87, %r1, 31;
	shr.u32 	%r88, %r87, 5;
	setp.ge.u32 	%p35, %r2, %r88;
	mov.f64 	%fd81, 0d0000000000000000;
	mov.f32 	%f103, 0f00000000;
	mov.f32 	%f104, %f103;
	mov.f64 	%fd82, %fd81;
	@%p35 bra 	$L__BB0_10;

	shl.b32 	%r89, %r2, 2;
	mov.u32 	%r90, _ZZ11cgUpdateDirE3smm;
	add.s32 	%r91, %r90, %r89;
	ld.shared.f32 	%f103, [%r91];
	mov.u32 	%r92, _ZZ11cgUpdateDirE3sns;
	add.s32 	%r93, %r92, %r89;
	ld.shared.f32 	%f104, [%r93];
	shl.b32 	%r94, %r2, 3;
	mov.u32 	%r95, _ZZ11cgUpdateDirE3sep;
	add.s32 	%r96, %r95, %r94;
	ld.shared.f64 	%fd81, [%r96];
	mov.u32 	%r97, _ZZ11cgUpdateDirE3sgs;
	add.s32 	%r98, %r97, %r94;
	ld.shared.f64 	%fd82, [%r98];

$L__BB0_10:
	setp.ne.s32 	%p36, %r4, 0;
	@%p36 bra 	$L__BB0_12;

	mov.b32 	%r99, %f103;
	mov.u32 	%r100, 2;
	mov.u32 	%r101, 31;
	mov.u32 	%r102, 16;
	mov.u32 	%r103, -1;
	shfl.sync.down.b32 	%r104|%p37, %r99, %r102, %r101, %r103;
	mov.b32 	%f73, %r104;
	max.f32 	%f74, %f103, %f73;
	mov.b32 	%r105, %f74;
	mov.u32 	%r106, 8;
	shfl.sync.down.b32 	%r107|%p38, %r105, %r106, %r101, %r103;
	mov.b32 	%f75, %r107;
	max.f32 	%f76, %f74, %f75;
	mov.b32 	%r108, %f76;
	mov.u32 	%r109, 4;
	shfl.sync.down.b32 	%r110|%p39, %r108, %r109, %r101, %r103;
	mov.b32 	%f77, %r110;
	max.f32 	%f78, %f76, %f77;
	mov.b32 	%r111, %f78;
	shfl.sync.down.b32 	%r112|%p40, %r111, %r100, %r101, %r103;
	mov.b32 	%f79, %r112;
	max.f32 	%f80, %f78, %f79;
	mov.b32 	%r113, %f80;
	mov.u32 	%r114, 1;
	shfl.sync.down.b32 	%r115|%p41, %r113, %r114, %r101, %r103;
	mov.b32 	%f81, %r115;
	max.f32 	%f103, %f80, %f81;
	mov.b32 	%r116, %f104;
	shfl.sync.down.b32 	%r117|%p42, %r116, %r102, %r101, %r103;
	mov.b32 	%f82, %r117;
	add.f32 	%f83, %f104, %f82;
	mov.b32 	%r118, %f83;
	shfl.sync.down.b32 	%r119|%p43, %r118, %r106, %r101, %r103;
	mov.b32 	%f84, %r119;
	add.f32 	%f85, %f83, %f84;
	mov.b32 	%r120, %f85;
	shfl.sync.down.b32 	%r121|%p44, %r120, %r109, %r101, %r103;
	mov.b32 	%f86, %r121;
	add.f32 	%f87, %f85, %f86;
	mov.b32 	%r122, %f87;
	shfl.sync.down.b32 	%r123|%p45, %r122, %r100, %r101, %r103;
	mov.b32 	%f88, %r123;
	add.f32 	%f89, %f87, %f88;
	mov.b32 	%r124, %f89;
	shfl.sync.down.b32 	%r125|%p46, %r124, %r114, %r101, %r103;
	mov.b32 	%f90, %r125;
	add.f32 	%f104, %f89, %f90;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r126, %temp}, %fd81;
	}
	shfl.sync.down.b32 	%r127|%p47, %r126, %r102, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r128}, %fd81;
	}
	shfl.sync.down.b32 	%r129|%p48, %r128, %r102, %r101, %r103;
	mov.b64 	%fd55, {%r127, %r129};
	add.f64 	%fd56, %fd81, %fd55;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r130, %temp}, %fd56;
	}
	shfl.sync.down.b32 	%r131|%p49, %r130, %r106, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r132}, %fd56;
	}
	shfl.sync.down.b32 	%r133|%p50, %r132, %r106, %r101, %r103;
	mov.b64 	%fd57, {%r131, %r133};
	add.f64 	%fd58, %fd56, %fd57;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r134, %temp}, %fd58;
	}
	shfl.sync.down.b32 	%r135|%p51, %r134, %r109, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r136}, %fd58;
	}
	shfl.sync.down.b32 	%r137|%p52, %r136, %r109, %r101, %r103;
	mov.b64 	%fd59, {%r135, %r137};
	add.f64 	%fd60, %fd58, %fd59;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r138, %temp}, %fd60;
	}
	shfl.sync.down.b32 	%r139|%p53, %r138, %r100, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r140}, %fd60;
	}
	shfl.sync.down.b32 	%r141|%p54, %r140, %r100, %r101, %r103;
	mov.b64 	%fd61, {%r139, %r141};
	add.f64 	%fd62, %fd60, %fd61;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r142, %temp}, %fd62;
	}
	shfl.sync.down.b32 	%r143|%p55, %r142, %r114, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r144}, %fd62;
	}
	shfl.sync.down.b32 	%r145|%p56, %r144, %r114, %r101, %r103;
	mov.b64 	%fd63, {%r143, %r145};
	add.f64 	%fd81, %fd62, %fd63;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r146, %temp}, %fd82;
	}
	shfl.sync.down.b32 	%r147|%p57, %r146, %r102, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r148}, %fd82;
	}
	shfl.sync.down.b32 	%r149|%p58, %r148, %r102, %r101, %r103;
	mov.b64 	%fd64, {%r147, %r149};
	add.f64 	%fd65, %fd82, %fd64;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r150, %temp}, %fd65;
	}
	shfl.sync.down.b32 	%r151|%p59, %r150, %r106, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r152}, %fd65;
	}
	shfl.sync.down.b32 	%r153|%p60, %r152, %r106, %r101, %r103;
	mov.b64 	%fd66, {%r151, %r153};
	add.f64 	%fd67, %fd65, %fd66;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r154, %temp}, %fd67;
	}
	shfl.sync.down.b32 	%r155|%p61, %r154, %r109, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r156}, %fd67;
	}
	shfl.sync.down.b32 	%r157|%p62, %r156, %r109, %r101, %r103;
	mov.b64 	%fd68, {%r155, %r157};
	add.f64 	%fd69, %fd67, %fd68;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r158, %temp}, %fd69;
	}
	shfl.sync.down.b32 	%r159|%p63, %r158, %r100, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r160}, %fd69;
	}
	shfl.sync.down.b32 	%r161|%p64, %r160, %r100, %r101, %r103;
	mov.b64 	%fd70, {%r159, %r161};
	add.f64 	%fd71, %fd69, %fd70;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r162, %temp}, %fd71;
	}
	shfl.sync.down.b32 	%r163|%p65, %r162, %r114, %r101, %r103;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r164}, %fd71;
	}
	shfl.sync.down.b32 	%r165|%p66, %r164, %r114, %r101, %r103;
	mov.b64 	%fd72, {%r163, %r165};
	add.f64 	%fd82, %fd71, %fd72;

$L__BB0_12:
	setp.ne.s32 	%p67, %r2, 0;
	@%p67 bra 	$L__BB0_14;

	cvta.to.global.u64 	%rd39, %rd15;
	abs.f32 	%f91, %f103;
	mov.b32 	%r166, %f91;
	atom.global.max.u32 	%r167, [%rd39], %r166;
	cvta.to.global.u64 	%rd40, %rd16;
	atom.global.add.f32 	%f92, [%rd40], %f104;
	cvta.to.global.u64 	%rd41, %rd17;
	atom.global.add.f64 	%fd73, [%rd41], %fd81;
	cvta.to.global.u64 	%rd42, %rd18;
	atom.global.add.f64 	%fd74, [%rd42], %fd82;

$L__BB0_14:
	ret;

}

`
 )
