package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_cosh kernel
var unary_cosh_code cu.Function

// Stores the arguments for unary_cosh kernel invocation
type unary_cosh_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_cosh kernel invocation
var unary_cosh_args unary_cosh_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_cosh_args.argptr[0] = unsafe.Pointer(&unary_cosh_args.arg_dst)
	 unary_cosh_args.argptr[1] = unsafe.Pointer(&unary_cosh_args.arg_a)
	 unary_cosh_args.argptr[2] = unsafe.Pointer(&unary_cosh_args.arg_N)
	 }

// Wrapper for unary_cosh CUDA kernel, asynchronous.
func k_unary_cosh_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_cosh")
	}

	unary_cosh_args.Lock()
	defer unary_cosh_args.Unlock()

	if unary_cosh_code == 0{
		unary_cosh_code = fatbinLoad(unary_cosh_map, "unary_cosh")
	}

	 unary_cosh_args.arg_dst = dst
	 unary_cosh_args.arg_a = a
	 unary_cosh_args.arg_N = N
	

	args := unary_cosh_args.argptr[:]
	cu.LaunchKernel(unary_cosh_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_cosh")
	}
}

// maps compute capability on PTX code for unary_cosh kernel.
var unary_cosh_map = map[int]string{ 0: "" ,
61: unary_cosh_ptx_61  }

// unary_cosh PTX code for various compute capabilities.
const(
  unary_cosh_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_cosh

.visible .entry unary_cosh(
	.param .u64 unary_cosh_param_0,
	.param .u64 unary_cosh_param_1,
	.param .u32 unary_cosh_param_2
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<14>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [unary_cosh_param_0];
	ld.param.u64 	%rd2, [unary_cosh_param_1];
	ld.param.u32 	%r2, [unary_cosh_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f2, %f1;
	mov.f32 	%f3, 0f3FB8AA3B;
	mul.rn.f32 	%f4, %f2, %f3;
	cvt.rzi.f32.f32 	%f5, %f4;
	abs.f32 	%f6, %f5;
	setp.gt.f32 	%p2, %f6, 0f42FC0000;
	mov.b32 	%r9, %f5;
	and.b32  	%r10, %r9, -2147483648;
	or.b32  	%r11, %r10, 1123811328;
	mov.b32 	%f7, %r11;
	selp.f32 	%f8, %f7, %f5, %p2;
	mov.f32 	%f9, 0fBF317218;
	fma.rn.f32 	%f10, %f8, %f9, %f2;
	mov.f32 	%f11, 0f3102E308;
	fma.rn.f32 	%f12, %f8, %f11, %f10;
	mul.f32 	%f13, %f12, 0f3FB8AA3B;
	add.f32 	%f14, %f8, 0f4B40007D;
	mov.b32 	%r12, %f14;
	shl.b32 	%r13, %r12, 23;
	mov.b32 	%f15, %r13;
	ex2.approx.ftz.f32 	%f16, %f13;
	mul.f32 	%f17, %f16, %f15;
	mov.f32 	%f18, 0f3E000000;
	div.approx.f32 	%f19, %f18, %f17;
	mov.f32 	%f20, 0f40000000;
	fma.rn.f32 	%f21, %f20, %f17, %f19;
	setp.ge.f32 	%p3, %f2, 0f42B40000;
	selp.f32 	%f22, 0f7F800000, %f21, %p3;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f22;

$L__BB0_2:
	ret;

}

`
 )
