package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_gamma kernel
var unary_gamma_code cu.Function

// Stores the arguments for unary_gamma kernel invocation
type unary_gamma_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_gamma kernel invocation
var unary_gamma_args unary_gamma_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_gamma_args.argptr[0] = unsafe.Pointer(&unary_gamma_args.arg_dst)
	 unary_gamma_args.argptr[1] = unsafe.Pointer(&unary_gamma_args.arg_a)
	 unary_gamma_args.argptr[2] = unsafe.Pointer(&unary_gamma_args.arg_N)
	 }

// Wrapper for unary_gamma CUDA kernel, asynchronous.
func k_unary_gamma_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_gamma")
	}

	unary_gamma_args.Lock()
	defer unary_gamma_args.Unlock()

	if unary_gamma_code == 0{
		unary_gamma_code = fatbinLoad(unary_gamma_map, "unary_gamma")
	}

	 unary_gamma_args.arg_dst = dst
	 unary_gamma_args.arg_a = a
	 unary_gamma_args.arg_N = N
	

	args := unary_gamma_args.argptr[:]
	cu.LaunchKernel(unary_gamma_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_gamma")
	}
}

// maps compute capability on PTX code for unary_gamma kernel.
var unary_gamma_map = map[int]string{ 0: "" ,
61: unary_gamma_ptx_61  }

// unary_gamma PTX code for various compute capabilities.
const(
  unary_gamma_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_gamma

.visible .entry unary_gamma(
	.param .u64 unary_gamma_param_0,
	.param .u64 unary_gamma_param_1,
	.param .u32 unary_gamma_param_2
)
{
	.reg .pred 	%p<21>;
	.reg .f32 	%f<183>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [unary_gamma_param_0];
	ld.param.u64 	%rd3, [unary_gamma_param_1];
	ld.param.u32 	%r4, [unary_gamma_param_2];
	mov.u32 	%r5, %nctaid.x;
	mov.u32 	%r6, %ctaid.y;
	mov.u32 	%r7, %ctaid.x;
	mad.lo.s32 	%r8, %r6, %r5, %r7;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	setp.ge.s32 	%p2, %r1, %r4;
	@%p2 bra 	$L__BB0_16;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.gt.f32 	%p3, %f1, 0f00000000;
	@%p3 bra 	$L__BB0_3;

	cvt.rmi.f32.f32 	%f21, %f1;
	setp.eq.f32 	%p4, %f1, %f21;
	mov.f32 	%f182, 0f00000000;
	@%p4 bra 	$L__BB0_15;

$L__BB0_3:
	abs.f32 	%f2, %f1;
	setp.ltu.f32 	%p5, %f2, 0f3FC00000;
	@%p5 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_4;

$L__BB0_9:
	setp.eq.f32 	%p14, %f1, 0f00000000;
	mov.f32 	%f180, %f1;
	@%p14 bra 	$L__BB0_11;

	cvt.rni.f32.f32 	%f154, %f1;
	sub.f32 	%f180, %f1, %f154;

$L__BB0_11:
	setp.lt.f32 	%p15, %f1, 0fBF000000;
	selp.f32 	%f155, %f1, 0f3F800000, %p15;
	mov.f32 	%f156, 0f3F800000;
	mul.f32 	%f157, %f155, %f180;
	setp.le.f32 	%p16, %f1, 0f3F000000;
	selp.f32 	%f158, %f157, %f155, %p16;
	mov.f32 	%f159, 0f3BE903D7;
	mov.f32 	%f160, 0fBA8C9F66;
	fma.rn.f32 	%f161, %f160, %f180, %f159;
	mov.f32 	%f162, 0fBC1E00B0;
	fma.rn.f32 	%f163, %f161, %f180, %f162;
	mov.f32 	%f164, 0fBD2CC522;
	fma.rn.f32 	%f165, %f163, %f180, %f164;
	mov.f32 	%f166, 0f3E2A89B3;
	fma.rn.f32 	%f167, %f165, %f180, %f166;
	mov.f32 	%f168, 0fBD2C0C05;
	fma.rn.f32 	%f169, %f167, %f180, %f168;
	mov.f32 	%f170, 0fBF27E7A2;
	fma.rn.f32 	%f171, %f169, %f180, %f170;
	mov.f32 	%f172, 0f3F13C468;
	fma.rn.f32 	%f173, %f171, %f180, %f172;
	mov.f32 	%f174, 0f00000000;
	fma.rn.f32 	%f175, %f173, %f158, %f174;
	fma.rn.f32 	%f176, %f175, %f180, %f158;
	div.approx.f32 	%f182, %f156, %f176;
	setp.geu.f32 	%p17, %f1, 0f00000000;
	@%p17 bra 	$L__BB0_15;
	bra.uni 	$L__BB0_12;

$L__BB0_4:
	setp.lt.f32 	%p6, %f1, 0f00000000;
	setp.gt.f32 	%p7, %f2, 0f42246666;
	selp.f32 	%f3, 0f42246666, %f1, %p7;
	abs.f32 	%f4, %f3;
	setp.lt.f32 	%p8, %f4, 0f00800000;
	mul.f32 	%f22, %f4, 0f4B800000;
	selp.f32 	%f23, %f22, %f4, %p8;
	selp.f32 	%f24, 0fC1C00000, 0f00000000, %p8;
	mov.b32 	%r11, %f23;
	add.s32 	%r12, %r11, -1060439283;
	and.b32  	%r13, %r12, -8388608;
	sub.s32 	%r14, %r11, %r13;
	mov.b32 	%f25, %r14;
	cvt.rn.f32.s32 	%f26, %r13;
	mov.f32 	%f27, 0f34000000;
	fma.rn.f32 	%f28, %f26, %f27, %f24;
	add.f32 	%f29, %f25, 0fBF800000;
	add.f32 	%f30, %f25, 0f3F800000;
	mov.f32 	%f31, 0f3F800000;
	rcp.approx.ftz.f32 	%f32, %f30;
	add.f32 	%f33, %f29, %f29;
	mul.f32 	%f34, %f33, %f32;
	mul.f32 	%f35, %f34, %f34;
	sub.f32 	%f36, %f29, %f34;
	add.f32 	%f37, %f36, %f36;
	neg.f32 	%f38, %f34;
	fma.rn.f32 	%f39, %f38, %f29, %f37;
	mul.rn.f32 	%f40, %f32, %f39;
	mov.f32 	%f41, 0f3B52E7DB;
	mov.f32 	%f42, 0f3A2C32E4;
	fma.rn.f32 	%f43, %f42, %f35, %f41;
	mov.f32 	%f44, 0f3C93BB73;
	fma.rn.f32 	%f45, %f43, %f35, %f44;
	mov.f32 	%f46, 0f3DF6384F;
	fma.rn.f32 	%f47, %f45, %f35, %f46;
	mul.rn.f32 	%f48, %f47, %f35;
	mov.f32 	%f49, 0f3FB8AA3B;
	fma.rn.f32 	%f50, %f34, %f49, %f28;
	sub.f32 	%f51, %f28, %f50;
	fma.rn.f32 	%f52, %f34, %f49, %f51;
	fma.rn.f32 	%f53, %f40, %f49, %f52;
	mov.f32 	%f54, 0f32A55E34;
	fma.rn.f32 	%f55, %f34, %f54, %f53;
	fma.rn.f32 	%f56, %f48, %f34, %f55;
	add.rn.f32 	%f57, %f50, %f56;
	neg.f32 	%f58, %f50;
	add.rn.f32 	%f59, %f57, %f58;
	neg.f32 	%f60, %f59;
	add.rn.f32 	%f61, %f56, %f60;
	add.f32 	%f62, %f4, 0fBF000000;
	mul.rn.f32 	%f63, %f57, %f62;
	neg.f32 	%f64, %f63;
	fma.rn.f32 	%f65, %f57, %f62, %f64;
	fma.rn.f32 	%f66, %f61, %f62, %f65;
	mul.rn.f32 	%f67, %f49, %f4;
	neg.f32 	%f68, %f67;
	fma.rn.f32 	%f69, %f49, %f4, %f68;
	mov.f32 	%f70, 0f32A57060;
	fma.rn.f32 	%f71, %f70, %f4, %f69;
	add.rn.f32 	%f72, %f63, %f68;
	add.rn.f32 	%f73, %f72, %f67;
	neg.f32 	%f74, %f73;
	add.rn.f32 	%f75, %f72, %f74;
	add.rn.f32 	%f76, %f63, %f74;
	neg.f32 	%f77, %f75;
	add.rn.f32 	%f78, %f68, %f77;
	add.rn.f32 	%f79, %f76, %f78;
	sub.f32 	%f80, %f66, %f71;
	add.f32 	%f81, %f80, %f79;
	neg.f32 	%f82, %f81;
	setp.gt.f32 	%p9, %f4, 0f42040000;
	selp.f32 	%f83, 0f42400000, 0f80000000, %p9;
	sub.f32 	%f84, %f83, %f72;
	selp.f32 	%f85, %f84, %f72, %p6;
	selp.f32 	%f86, %f82, %f81, %p6;
	cvt.rni.f32.f32 	%f87, %f85;
	sub.f32 	%f88, %f85, %f87;
	add.f32 	%f89, %f88, %f86;
	mov.f32 	%f90, 0f3AAF85ED;
	mov.f32 	%f91, 0f391FCB8E;
	fma.rn.f32 	%f92, %f91, %f89, %f90;
	mov.f32 	%f93, 0f3C1D9856;
	fma.rn.f32 	%f94, %f92, %f89, %f93;
	mov.f32 	%f95, 0f3D6357BB;
	fma.rn.f32 	%f96, %f94, %f89, %f95;
	mov.f32 	%f97, 0f3E75FDEC;
	fma.rn.f32 	%f98, %f96, %f89, %f97;
	mov.f32 	%f99, 0f3F317218;
	fma.rn.f32 	%f100, %f98, %f89, %f99;
	fma.rn.f32 	%f101, %f100, %f89, %f31;
	cvt.rzi.s32.f32 	%r15, %f87;
	setp.gt.f32 	%p10, %f87, 0f00000000;
	selp.b32 	%r16, 0, -2097152000, %p10;
	add.s32 	%r17, %r16, 2130706432;
	mov.b32 	%f102, %r17;
	mul.f32 	%f103, %f101, %f102;
	shl.b32 	%r18, %r15, 23;
	sub.s32 	%r19, %r18, %r16;
	mov.b32 	%f104, %r19;
	mul.f32 	%f105, %f103, %f104;
	mul.f32 	%f5, %f105, 0f40206C99;
	rcp.approx.ftz.f32 	%f106, %f4;
	mov.f32 	%f107, 0fB8543ED8;
	mov.f32 	%f108, 0f388F7971;
	fma.rn.f32 	%f109, %f108, %f106, %f107;
	mov.f32 	%f110, 0fB9DDA6BE;
	fma.rn.f32 	%f111, %f109, %f106, %f110;
	mov.f32 	%f112, 0f3A820ABE;
	fma.rn.f32 	%f113, %f111, %f106, %f112;
	mov.f32 	%f114, 0fB9920AFD;
	fma.rn.f32 	%f115, %f113, %f106, %f114;
	mov.f32 	%f116, 0fBB2F4D64;
	fma.rn.f32 	%f117, %f115, %f106, %f116;
	mov.f32 	%f118, 0f3B638732;
	fma.rn.f32 	%f119, %f117, %f106, %f118;
	mov.f32 	%f120, 0f3DAAAAAC;
	fma.rn.f32 	%f121, %f119, %f106, %f120;
	mul.f32 	%f6, %f106, %f121;
	@%p6 bra 	$L__BB0_6;
	bra.uni 	$L__BB0_5;

$L__BB0_6:
	fma.rn.f32 	%f8, %f6, %f3, %f3;
	add.f32 	%f123, %f4, %f4;
	cvt.rni.f32.f32 	%f124, %f123;
	cvt.rzi.s32.f32 	%r2, %f124;
	mov.f32 	%f125, 0fBF000000;
	fma.rn.f32 	%f9, %f124, %f125, %f4;
	and.b32  	%r3, %r2, 1;
	mul.rn.f32 	%f10, %f9, %f9;
	setp.eq.s32 	%p1, %r3, 0;
	mov.f32 	%f179, 0fBF17ACC9;
	@%p1 bra 	$L__BB0_8;

	mov.f32 	%f126, 0fBFAAD2E0;
	mov.f32 	%f127, 0f3E684E12;
	fma.rn.f32 	%f179, %f127, %f10, %f126;

$L__BB0_8:
	selp.f32 	%f128, 0f40233590, 0f4081E0CF, %p1;
	fma.rn.f32 	%f129, %f179, %f10, %f128;
	selp.f32 	%f130, 0fC0A55DF6, 0fC09DE9E6, %p1;
	fma.rn.f32 	%f131, %f129, %f10, %f130;
	selp.f32 	%f132, 0f00000000, 0f3F800000, %p1;
	mov.f32 	%f133, 0f3F800000;
	mov.f32 	%f134, 0f00000000;
	selp.f32 	%f135, %f9, 0f3F800000, %p1;
	fma.rn.f32 	%f136, %f10, %f135, %f134;
	fma.rn.f32 	%f137, %f131, %f136, %f132;
	mov.f32 	%f138, 0f40490FDB;
	fma.rn.f32 	%f139, %f138, %f9, %f137;
	selp.f32 	%f140, %f139, %f137, %p1;
	and.b32  	%r20, %r2, 2;
	setp.eq.s32 	%p12, %r20, 0;
	sub.f32 	%f141, %f134, %f140;
	selp.f32 	%f142, %f140, %f141, %p12;
	mul.rn.f32 	%f143, %f8, %f142;
	neg.f32 	%f144, %f143;
	fma.rn.f32 	%f145, %f8, %f142, %f144;
	div.approx.f32 	%f146, %f133, %f143;
	mul.f32 	%f147, %f146, %f146;
	mul.f32 	%f148, %f145, %f147;
	mul.f32 	%f149, %f5, %f148;
	neg.f32 	%f150, %f149;
	fma.rn.f32 	%f151, %f5, %f146, %f150;
	mul.f32 	%f152, %f151, 0f3F000000;
	mul.f32 	%f153, %f152, 0f27800000;
	selp.f32 	%f182, %f153, %f152, %p9;

$L__BB0_12:
	mov.f32 	%f17, %f182;
	cvt.rzi.f32.f32 	%f178, %f1;
	setp.eq.f32 	%p18, %f178, %f1;
	mov.f32 	%f182, 0f7FFFFFFF;
	@%p18 bra 	$L__BB0_15;

	setp.geu.f32 	%p19, %f1, 0fC2246666;
	mov.f32 	%f182, %f17;
	@%p19 bra 	$L__BB0_15;

	cvt.rzi.s32.f32 	%r21, %f1;
	and.b32  	%r22, %r21, 1;
	setp.eq.b32 	%p20, %r22, 1;
	selp.f32 	%f182, 0f00000000, %f17, %p20;
	bra.uni 	$L__BB0_15;

$L__BB0_5:
	fma.rn.f32 	%f182, %f6, %f5, %f5;

$L__BB0_15:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f182;

$L__BB0_16:
	ret;

}

`
 )
