package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_heaviside kernel
var unary_heaviside_code cu.Function

// Stores the arguments for unary_heaviside kernel invocation
type unary_heaviside_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_heaviside kernel invocation
var unary_heaviside_args unary_heaviside_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_heaviside_args.argptr[0] = unsafe.Pointer(&unary_heaviside_args.arg_dst)
	 unary_heaviside_args.argptr[1] = unsafe.Pointer(&unary_heaviside_args.arg_a)
	 unary_heaviside_args.argptr[2] = unsafe.Pointer(&unary_heaviside_args.arg_N)
	 }

// Wrapper for unary_heaviside CUDA kernel, asynchronous.
func k_unary_heaviside_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_heaviside")
	}

	unary_heaviside_args.Lock()
	defer unary_heaviside_args.Unlock()

	if unary_heaviside_code == 0{
		unary_heaviside_code = fatbinLoad(unary_heaviside_map, "unary_heaviside")
	}

	 unary_heaviside_args.arg_dst = dst
	 unary_heaviside_args.arg_a = a
	 unary_heaviside_args.arg_N = N
	

	args := unary_heaviside_args.argptr[:]
	cu.LaunchKernel(unary_heaviside_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_heaviside")
	}
}

// maps compute capability on PTX code for unary_heaviside kernel.
var unary_heaviside_map = map[int]string{ 0: "" ,
61: unary_heaviside_ptx_61  }

// unary_heaviside PTX code for various compute capabilities.
const(
  unary_heaviside_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_heaviside

.visible .entry unary_heaviside(
	.param .u64 unary_heaviside_param_0,
	.param .u64 unary_heaviside_param_1,
	.param .u32 unary_heaviside_param_2
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [unary_heaviside_param_0];
	ld.param.u64 	%rd2, [unary_heaviside_param_1];
	ld.param.u32 	%r2, [unary_heaviside_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	setp.gt.f32 	%p2, %f1, 0f00000000;
	setp.lt.f32 	%p3, %f1, 0f00000000;
	selp.f32 	%f2, 0f00000000, 0f3F000000, %p3;
	selp.f32 	%f3, 0f3F800000, %f2, %p2;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f3;

$L__BB0_2:
	ret;

}

`
 )
