package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_log kernel
var unary_log_code cu.Function

// Stores the arguments for unary_log kernel invocation
type unary_log_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_log kernel invocation
var unary_log_args unary_log_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_log_args.argptr[0] = unsafe.Pointer(&unary_log_args.arg_dst)
	 unary_log_args.argptr[1] = unsafe.Pointer(&unary_log_args.arg_a)
	 unary_log_args.argptr[2] = unsafe.Pointer(&unary_log_args.arg_N)
	 }

// Wrapper for unary_log CUDA kernel, asynchronous.
func k_unary_log_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_log")
	}

	unary_log_args.Lock()
	defer unary_log_args.Unlock()

	if unary_log_code == 0{
		unary_log_code = fatbinLoad(unary_log_map, "unary_log")
	}

	 unary_log_args.arg_dst = dst
	 unary_log_args.arg_a = a
	 unary_log_args.arg_N = N
	

	args := unary_log_args.argptr[:]
	cu.LaunchKernel(unary_log_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_log")
	}
}

// maps compute capability on PTX code for unary_log kernel.
var unary_log_map = map[int]string{ 0: "" ,
61: unary_log_ptx_61  }

// unary_log PTX code for various compute capabilities.
const(
  unary_log_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_log

.visible .entry unary_log(
	.param .u64 unary_log_param_0,
	.param .u64 unary_log_param_1,
	.param .u32 unary_log_param_2
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<39>;
	.reg .b32 	%r<13>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [unary_log_param_0];
	ld.param.u64 	%rd3, [unary_log_param_1];
	ld.param.u32 	%r2, [unary_log_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_6;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.leu.f32 	%p2, %f1, 0f00000000;
	mov.f32 	%f38, 0f00000000;
	@%p2 bra 	$L__BB0_5;

	setp.lt.f32 	%p3, %f1, 0f00800000;
	mul.f32 	%f9, %f1, 0f4B000000;
	selp.f32 	%f2, %f9, %f1, %p3;
	selp.f32 	%f10, 0fC1B80000, 0f00000000, %p3;
	mov.b32 	%r9, %f2;
	add.s32 	%r10, %r9, -1059760811;
	and.b32  	%r11, %r10, -8388608;
	sub.s32 	%r12, %r9, %r11;
	mov.b32 	%f11, %r12;
	cvt.rn.f32.s32 	%f12, %r11;
	mov.f32 	%f13, 0f34000000;
	fma.rn.f32 	%f14, %f12, %f13, %f10;
	add.f32 	%f15, %f11, 0fBF800000;
	mov.f32 	%f16, 0f3E1039F6;
	mov.f32 	%f17, 0fBE055027;
	fma.rn.f32 	%f18, %f17, %f15, %f16;
	mov.f32 	%f19, 0fBDF8CDCC;
	fma.rn.f32 	%f20, %f18, %f15, %f19;
	mov.f32 	%f21, 0f3E0F2955;
	fma.rn.f32 	%f22, %f20, %f15, %f21;
	mov.f32 	%f23, 0fBE2AD8B9;
	fma.rn.f32 	%f24, %f22, %f15, %f23;
	mov.f32 	%f25, 0f3E4CED0B;
	fma.rn.f32 	%f26, %f24, %f15, %f25;
	mov.f32 	%f27, 0fBE7FFF22;
	fma.rn.f32 	%f28, %f26, %f15, %f27;
	mov.f32 	%f29, 0f3EAAAA78;
	fma.rn.f32 	%f30, %f28, %f15, %f29;
	mov.f32 	%f31, 0fBF000000;
	fma.rn.f32 	%f32, %f30, %f15, %f31;
	mul.f32 	%f33, %f15, %f32;
	fma.rn.f32 	%f34, %f33, %f15, %f15;
	mov.f32 	%f35, 0f3F317218;
	fma.rn.f32 	%f37, %f14, %f35, %f34;
	setp.lt.u32 	%p4, %r9, 2139095040;
	@%p4 bra 	$L__BB0_4;

	mov.f32 	%f36, 0f7F800000;
	fma.rn.f32 	%f37, %f2, %f36, %f36;

$L__BB0_4:
	setp.eq.f32 	%p5, %f2, 0f00000000;
	selp.f32 	%f38, 0fFF800000, %f37, %p5;

$L__BB0_5:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f38;

$L__BB0_6:
	ret;

}

`
 )
