package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for madd2ptr kernel
var madd2ptr_code cu.Function

// Stores the arguments for madd2ptr kernel invocation
type madd2ptr_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src1 unsafe.Pointer
	 arg_fac1 float32
	 arg_src2 unsafe.Pointer
	 arg_facptr2 unsafe.Pointer
	 arg_N int
	 argptr [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd2ptr kernel invocation
var madd2ptr_args madd2ptr_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 madd2ptr_args.argptr[0] = unsafe.Pointer(&madd2ptr_args.arg_dst)
	 madd2ptr_args.argptr[1] = unsafe.Pointer(&madd2ptr_args.arg_src1)
	 madd2ptr_args.argptr[2] = unsafe.Pointer(&madd2ptr_args.arg_fac1)
	 madd2ptr_args.argptr[3] = unsafe.Pointer(&madd2ptr_args.arg_src2)
	 madd2ptr_args.argptr[4] = unsafe.Pointer(&madd2ptr_args.arg_facptr2)
	 madd2ptr_args.argptr[5] = unsafe.Pointer(&madd2ptr_args.arg_N)
	 }

// Wrapper for madd2ptr CUDA kernel, asynchronous.
func k_madd2ptr_async ( dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, facptr2 unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("madd2ptr")
	}

	madd2ptr_args.Lock()
	defer madd2ptr_args.Unlock()

	if madd2ptr_code == 0{
		madd2ptr_code = fatbinLoad(madd2ptr_map, "madd2ptr")
	}

	 madd2ptr_args.arg_dst = dst
	 madd2ptr_args.arg_src1 = src1
	 madd2ptr_args.arg_fac1 = fac1
	 madd2ptr_args.arg_src2 = src2
	 madd2ptr_args.arg_facptr2 = facptr2
	 madd2ptr_args.arg_N = N
	

	args := madd2ptr_args.argptr[:]
	cu.LaunchKernel(madd2ptr_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("madd2ptr")
	}
}

// maps compute capability on PTX code for madd2ptr kernel.
var madd2ptr_map = map[int]string{ 0: "" ,
61: madd2ptr_ptx_61  }

// madd2ptr PTX code for various compute capabilities.
const(
  madd2ptr_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	madd2ptr

.visible .entry madd2ptr(
	.param .u64 madd2ptr_param_0,
	.param .u64 madd2ptr_param_1,
	.param .f32 madd2ptr_param_2,
	.param .u64 madd2ptr_param_3,
	.param .u64 madd2ptr_param_4,
	.param .u32 madd2ptr_param_5
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<7>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [madd2ptr_param_0];
	ld.param.u64 	%rd2, [madd2ptr_param_1];
	ld.param.f32 	%f1, [madd2ptr_param_2];
	ld.param.u64 	%rd3, [madd2ptr_param_3];
	ld.param.u64 	%rd4, [madd2ptr_param_4];
	ld.param.u32 	%r2, [madd2ptr_param_5];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd5, %rd2;
	mul.wide.s32 	%rd6, %r1, 4;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.nc.f32 	%f2, [%rd7];
	cvta.to.global.u64 	%rd8, %rd3;
	add.s64 	%rd9, %rd8, %rd6;
	ld.global.nc.f32 	%f3, [%rd9];
	cvta.to.global.u64 	%rd10, %rd4;
	ld.global.nc.f32 	%f4, [%rd10];
	mul.f32 	%f5, %f4, %f3;
	fma.rn.f32 	%f6, %f2, %f1, %f5;
	cvta.to.global.u64 	%rd11, %rd1;
	add.s64 	%rd12, %rd11, %rd6;
	st.global.f32 	[%rd12], %f6;

$L__BB0_2:
	ret;

}

`
 )
