package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for minimizeexp kernel
var minimizeexp_code cu.Function

// Stores the arguments for minimizeexp kernel invocation
type minimizeexp_args_t struct{
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_m0x unsafe.Pointer
	 arg_m0y unsafe.Pointer
	 arg_m0z unsafe.Pointer
	 arg_tx unsafe.Pointer
	 arg_ty unsafe.Pointer
	 arg_tz unsafe.Pointer
	 arg_dt float32
	 arg_N int
	 argptr [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for minimizeexp kernel invocation
var minimizeexp_args minimizeexp_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 minimizeexp_args.argptr[0] = unsafe.Pointer(&minimizeexp_args.arg_mx)
	 minimizeexp_args.argptr[1] = unsafe.Pointer(&minimizeexp_args.arg_my)
	 minimizeexp_args.argptr[2] = unsafe.Pointer(&minimizeexp_args.arg_mz)
	 minimizeexp_args.argptr[3] = unsafe.Pointer(&minimizeexp_args.arg_m0x)
	 minimizeexp_args.argptr[4] = unsafe.Pointer(&minimizeexp_args.arg_m0y)
	 minimizeexp_args.argptr[5] = unsafe.Pointer(&minimizeexp_args.arg_m0z)
	 minimizeexp_args.argptr[6] = unsafe.Pointer(&minimizeexp_args.arg_tx)
	 minimizeexp_args.argptr[7] = unsafe.Pointer(&minimizeexp_args.arg_ty)
	 minimizeexp_args.argptr[8] = unsafe.Pointer(&minimizeexp_args.arg_tz)
	 minimizeexp_args.argptr[9] = unsafe.Pointer(&minimizeexp_args.arg_dt)
	 minimizeexp_args.argptr[10] = unsafe.Pointer(&minimizeexp_args.arg_N)
	 }

// Wrapper for minimizeexp CUDA kernel, asynchronous.
func k_minimizeexp_async ( mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, m0x unsafe.Pointer, m0y unsafe.Pointer, m0z unsafe.Pointer, tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, dt float32, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("minimizeexp")
	}

	minimizeexp_args.Lock()
	defer minimizeexp_args.Unlock()

	if minimizeexp_code == 0{
		minimizeexp_code = fatbinLoad(minimizeexp_map, "minimizeexp")
	}

	 minimizeexp_args.arg_mx = mx
	 minimizeexp_args.arg_my = my
	 minimizeexp_args.arg_mz = mz
	 minimizeexp_args.arg_m0x = m0x
	 minimizeexp_args.arg_m0y = m0y
	 minimizeexp_args.arg_m0z = m0z
	 minimizeexp_args.arg_tx = tx
	 minimizeexp_args.arg_ty = ty
	 minimizeexp_args.arg_tz = tz
	 minimizeexp_args.arg_dt = dt
	 minimizeexp_args.arg_N = N
	

	args := minimizeexp_args.argptr[:]
	cu.LaunchKernel(minimizeexp_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("minimizeexp")
	}
}

// maps compute capability on PTX code for minimizeexp kernel.
var minimizeexp_map = map[int]string{ 0: "" ,
61: minimizeexp_ptx_61  }

// minimizeexp PTX code for various compute capabilities.
const(
  minimizeexp_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	minimizeexp
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry minimizeexp(
	.param .u64 minimizeexp_param_0,
	.param .u64 minimizeexp_param_1,
	.param .u64 minimizeexp_param_2,
	.param .u64 minimizeexp_param_3,
	.param .u64 minimizeexp_param_4,
	.param .u64 minimizeexp_param_5,
	.param .u64 minimizeexp_param_6,
	.param .u64 minimizeexp_param_7,
	.param .u64 minimizeexp_param_8,
	.param .f32 minimizeexp_param_9,
	.param .u32 minimizeexp_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<23>;
	.reg .f32 	%f<89>;
	.reg .b32 	%r<113>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<72>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd16, [minimizeexp_param_0];
	ld.param.u64 	%rd17, [minimizeexp_param_1];
	ld.param.u64 	%rd18, [minimizeexp_param_2];
	ld.param.u64 	%rd19, [minimizeexp_param_3];
	ld.param.u64 	%rd20, [minimizeexp_param_4];
	ld.param.u64 	%rd21, [minimizeexp_param_5];
	ld.param.u64 	%rd22, [minimizeexp_param_6];
	ld.param.u64 	%rd23, [minimizeexp_param_7];
	ld.param.u64 	%rd24, [minimizeexp_param_8];
	ld.param.f32 	%f33, [minimizeexp_param_9];
	ld.param.u32 	%r38, [minimizeexp_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r39, %nctaid.x;
	mov.u32 	%r40, %ctaid.y;
	mov.u32 	%r41, %ctaid.x;
	mad.lo.s32 	%r42, %r40, %r39, %r41;
	mov.u32 	%r43, %ntid.x;
	mov.u32 	%r44, %tid.x;
	mad.lo.s32 	%r1, %r42, %r43, %r44;
	setp.ge.s32 	%p1, %r1, %r38;
	@%p1 bra 	$L__BB0_29;

	cvta.to.global.u64 	%rd26, %rd19;
	cvt.s64.s32 	%rd2, %r1;
	mul.wide.s32 	%rd27, %r1, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f1, [%rd28];
	cvta.to.global.u64 	%rd29, %rd20;
	add.s64 	%rd30, %rd29, %rd27;
	ld.global.nc.f32 	%f2, [%rd30];
	cvta.to.global.u64 	%rd31, %rd21;
	add.s64 	%rd32, %rd31, %rd27;
	ld.global.nc.f32 	%f3, [%rd32];
	cvta.to.global.u64 	%rd33, %rd22;
	add.s64 	%rd34, %rd33, %rd27;
	cvta.to.global.u64 	%rd35, %rd23;
	add.s64 	%rd36, %rd35, %rd27;
	cvta.to.global.u64 	%rd37, %rd24;
	add.s64 	%rd38, %rd37, %rd27;
	ld.global.nc.f32 	%f4, [%rd34];
	ld.global.nc.f32 	%f5, [%rd36];
	mul.f32 	%f34, %f5, %f5;
	fma.rn.f32 	%f35, %f4, %f4, %f34;
	ld.global.nc.f32 	%f6, [%rd38];
	fma.rn.f32 	%f36, %f6, %f6, %f35;
	sqrt.rn.f32 	%f37, %f36;
	mul.f32 	%f7, %f37, %f33;
	mul.f32 	%f38, %f7, 0f3F22F983;
	cvt.rni.s32.f32 	%r112, %f38;
	cvt.rn.f32.s32 	%f39, %r112;
	mov.f32 	%f40, 0fBFC90FDA;
	fma.rn.f32 	%f41, %f39, %f40, %f7;
	mov.f32 	%f42, 0fB3A22168;
	fma.rn.f32 	%f43, %f39, %f42, %f41;
	mov.f32 	%f44, 0fA7C234C5;
	fma.rn.f32 	%f85, %f39, %f44, %f43;
	abs.f32 	%f9, %f7;
	setp.ltu.f32 	%p2, %f9, 0f47CE4780;
	add.s64 	%rd3, %rd1, 24;
	mov.u32 	%r108, %r112;
	mov.f32 	%f82, %f85;
	@%p2 bra 	$L__BB0_9;

	setp.eq.f32 	%p3, %f9, 0f7F800000;
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_3;

$L__BB0_8:
	mov.f32 	%f47, 0f00000000;
	mul.rn.f32 	%f82, %f7, %f47;
	mov.u32 	%r108, 0;
	bra.uni 	$L__BB0_9;

$L__BB0_3:
	mov.b32 	%r3, %f7;
	bfe.u32 	%r46, %r3, 23, 8;
	add.s32 	%r4, %r46, -128;
	shl.b32 	%r47, %r3, 8;
	or.b32  	%r5, %r47, -2147483648;
	shr.u32 	%r6, %r4, 5;
	mov.u64 	%rd68, 0;
	mov.u32 	%r105, 0;
	mov.u64 	%rd67, __cudart_i2opi_f;
	mov.u64 	%rd66, %rd1;

$L__BB0_4:
	.pragma "nounroll";
	ld.global.nc.u32 	%r48, [%rd67];
	mad.wide.u32 	%rd41, %r48, %r5, %rd68;
	shr.u64 	%rd68, %rd41, 32;
	st.local.u32 	[%rd66], %rd41;
	add.s64 	%rd67, %rd67, 4;
	add.s64 	%rd66, %rd66, 4;
	add.s32 	%r105, %r105, 1;
	setp.ne.s32 	%p4, %r105, 6;
	@%p4 bra 	$L__BB0_4;

	st.local.u32 	[%rd3], %rd68;
	mov.u32 	%r49, 4;
	sub.s32 	%r9, %r49, %r6;
	mov.u32 	%r50, 6;
	sub.s32 	%r51, %r50, %r6;
	mul.wide.s32 	%rd42, %r51, 4;
	add.s64 	%rd43, %rd1, %rd42;
	ld.local.u32 	%r106, [%rd43];
	ld.local.u32 	%r107, [%rd43+-4];
	and.b32  	%r12, %r4, 31;
	setp.eq.s32 	%p5, %r12, 0;
	@%p5 bra 	$L__BB0_7;

	mov.u32 	%r52, 32;
	sub.s32 	%r53, %r52, %r12;
	shr.u32 	%r54, %r107, %r53;
	shl.b32 	%r55, %r106, %r12;
	add.s32 	%r106, %r54, %r55;
	mul.wide.s32 	%rd44, %r9, 4;
	add.s64 	%rd45, %rd1, %rd44;
	ld.local.u32 	%r56, [%rd45];
	shr.u32 	%r57, %r56, %r53;
	shl.b32 	%r58, %r107, %r12;
	add.s32 	%r107, %r57, %r58;

$L__BB0_7:
	and.b32  	%r59, %r3, -2147483648;
	shr.u32 	%r60, %r107, 30;
	shl.b32 	%r61, %r106, 2;
	or.b32  	%r62, %r60, %r61;
	shr.u32 	%r63, %r62, 31;
	shr.u32 	%r64, %r106, 30;
	add.s32 	%r65, %r63, %r64;
	neg.s32 	%r66, %r65;
	setp.eq.s32 	%p6, %r59, 0;
	selp.b32 	%r108, %r65, %r66, %p6;
	setp.ne.s32 	%p7, %r63, 0;
	xor.b32  	%r67, %r59, -2147483648;
	selp.b32 	%r68, %r67, %r59, %p7;
	selp.b32 	%r69, -1, 0, %p7;
	xor.b32  	%r70, %r62, %r69;
	shl.b32 	%r71, %r107, 2;
	xor.b32  	%r72, %r71, %r69;
	cvt.u64.u32 	%rd46, %r70;
	cvt.u64.u32 	%rd47, %r72;
	bfi.b64 	%rd48, %rd46, %rd47, 32, 32;
	cvt.rn.f64.s64 	%fd1, %rd48;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f45, %fd2;
	setp.eq.s32 	%p8, %r68, 0;
	neg.f32 	%f46, %f45;
	selp.f32 	%f82, %f45, %f46, %p8;

$L__BB0_9:
	add.s32 	%r19, %r108, 1;
	and.b32  	%r20, %r19, 1;
	setp.eq.s32 	%p9, %r20, 0;
	selp.f32 	%f13, %f82, 0f3F800000, %p9;
	mul.rn.f32 	%f14, %f82, %f82;
	mov.f32 	%f83, 0fB94D4153;
	@%p9 bra 	$L__BB0_11;

	mov.f32 	%f49, 0fBAB607ED;
	mov.f32 	%f50, 0f37CBAC00;
	fma.rn.f32 	%f83, %f50, %f14, %f49;

$L__BB0_11:
	selp.f32 	%f51, 0f3C0885E4, 0f3D2AAABB, %p9;
	fma.rn.f32 	%f52, %f83, %f14, %f51;
	selp.f32 	%f53, 0fBE2AAAA8, 0fBEFFFFFF, %p9;
	fma.rn.f32 	%f54, %f52, %f14, %f53;
	mov.f32 	%f55, 0f00000000;
	fma.rn.f32 	%f56, %f14, %f13, %f55;
	fma.rn.f32 	%f84, %f54, %f56, %f13;
	and.b32  	%r74, %r19, 2;
	setp.eq.s32 	%p11, %r74, 0;
	@%p11 bra 	$L__BB0_13;

	mov.f32 	%f58, 0fBF800000;
	fma.rn.f32 	%f84, %f84, %f58, %f55;

$L__BB0_13:
	setp.gt.f32 	%p12, %f9, 0f3A83126F;
	@%p12 bra 	$L__BB0_15;
	bra.uni 	$L__BB0_14;

$L__BB0_15:
	@%p2 bra 	$L__BB0_23;

	setp.eq.f32 	%p14, %f9, 0f7F800000;
	@%p14 bra 	$L__BB0_22;
	bra.uni 	$L__BB0_17;

$L__BB0_22:
	mov.f32 	%f63, 0f00000000;
	mul.rn.f32 	%f85, %f7, %f63;
	mov.u32 	%r112, 0;
	bra.uni 	$L__BB0_23;

$L__BB0_14:
	mul.f32 	%f59, %f7, %f7;
	div.rn.f32 	%f60, %f59, 0fC0C00000;
	add.f32 	%f88, %f60, 0f3F800000;
	bra.uni 	$L__BB0_28;

$L__BB0_17:
	mov.b32 	%r21, %f7;
	bfe.u32 	%r76, %r21, 23, 8;
	add.s32 	%r22, %r76, -128;
	shl.b32 	%r77, %r21, 8;
	or.b32  	%r23, %r77, -2147483648;
	shr.u32 	%r24, %r22, 5;
	mov.u64 	%rd71, 0;
	mov.u32 	%r109, 0;
	mov.u64 	%rd70, __cudart_i2opi_f;
	mov.u64 	%rd69, %rd1;

$L__BB0_18:
	.pragma "nounroll";
	ld.global.nc.u32 	%r78, [%rd70];
	mad.wide.u32 	%rd51, %r78, %r23, %rd71;
	shr.u64 	%rd71, %rd51, 32;
	st.local.u32 	[%rd69], %rd51;
	add.s64 	%rd70, %rd70, 4;
	add.s64 	%rd69, %rd69, 4;
	add.s32 	%r109, %r109, 1;
	setp.ne.s32 	%p15, %r109, 6;
	@%p15 bra 	$L__BB0_18;

	st.local.u32 	[%rd3], %rd71;
	mov.u32 	%r79, 4;
	sub.s32 	%r27, %r79, %r24;
	mov.u32 	%r80, 6;
	sub.s32 	%r81, %r80, %r24;
	mul.wide.s32 	%rd52, %r81, 4;
	add.s64 	%rd53, %rd1, %rd52;
	ld.local.u32 	%r110, [%rd53];
	ld.local.u32 	%r111, [%rd53+-4];
	and.b32  	%r30, %r22, 31;
	setp.eq.s32 	%p16, %r30, 0;
	@%p16 bra 	$L__BB0_21;

	mov.u32 	%r82, 32;
	sub.s32 	%r83, %r82, %r30;
	shr.u32 	%r84, %r111, %r83;
	shl.b32 	%r85, %r110, %r30;
	add.s32 	%r110, %r84, %r85;
	mul.wide.s32 	%rd54, %r27, 4;
	add.s64 	%rd55, %rd1, %rd54;
	ld.local.u32 	%r86, [%rd55];
	shr.u32 	%r87, %r86, %r83;
	shl.b32 	%r88, %r111, %r30;
	add.s32 	%r111, %r87, %r88;

$L__BB0_21:
	and.b32  	%r89, %r21, -2147483648;
	shr.u32 	%r90, %r111, 30;
	shl.b32 	%r91, %r110, 2;
	or.b32  	%r92, %r90, %r91;
	shr.u32 	%r93, %r92, 31;
	shr.u32 	%r94, %r110, 30;
	add.s32 	%r95, %r93, %r94;
	neg.s32 	%r96, %r95;
	setp.eq.s32 	%p17, %r89, 0;
	selp.b32 	%r112, %r95, %r96, %p17;
	setp.ne.s32 	%p18, %r93, 0;
	xor.b32  	%r97, %r89, -2147483648;
	selp.b32 	%r98, %r97, %r89, %p18;
	selp.b32 	%r99, -1, 0, %p18;
	xor.b32  	%r100, %r92, %r99;
	shl.b32 	%r101, %r111, 2;
	xor.b32  	%r102, %r101, %r99;
	cvt.u64.u32 	%rd56, %r100;
	cvt.u64.u32 	%rd57, %r102;
	bfi.b64 	%rd58, %rd56, %rd57, 32, 32;
	cvt.rn.f64.s64 	%fd3, %rd58;
	mul.f64 	%fd4, %fd3, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f61, %fd4;
	setp.eq.s32 	%p19, %r98, 0;
	neg.f32 	%f62, %f61;
	selp.f32 	%f85, %f61, %f62, %p19;

$L__BB0_23:
	and.b32  	%r37, %r112, 1;
	setp.eq.s32 	%p20, %r37, 0;
	selp.f32 	%f24, %f85, 0f3F800000, %p20;
	mul.rn.f32 	%f25, %f85, %f85;
	mov.f32 	%f86, 0fB94D4153;
	@%p20 bra 	$L__BB0_25;

	mov.f32 	%f65, 0fBAB607ED;
	mov.f32 	%f66, 0f37CBAC00;
	fma.rn.f32 	%f86, %f66, %f25, %f65;

$L__BB0_25:
	selp.f32 	%f67, 0f3C0885E4, 0f3D2AAABB, %p20;
	fma.rn.f32 	%f68, %f86, %f25, %f67;
	selp.f32 	%f69, 0fBE2AAAA8, 0fBEFFFFFF, %p20;
	fma.rn.f32 	%f70, %f68, %f25, %f69;
	mov.f32 	%f71, 0f00000000;
	fma.rn.f32 	%f72, %f25, %f24, %f71;
	fma.rn.f32 	%f87, %f70, %f72, %f24;
	and.b32  	%r104, %r112, 2;
	setp.eq.s32 	%p22, %r104, 0;
	@%p22 bra 	$L__BB0_27;

	mov.f32 	%f74, 0fBF800000;
	fma.rn.f32 	%f87, %f87, %f74, %f71;

$L__BB0_27:
	div.rn.f32 	%f88, %f87, %f7;

$L__BB0_28:
	mul.f32 	%f75, %f88, %f33;
	mul.f32 	%f76, %f4, %f75;
	mul.f32 	%f77, %f5, %f75;
	mul.f32 	%f78, %f6, %f75;
	fma.rn.f32 	%f79, %f1, %f84, %f76;
	fma.rn.f32 	%f80, %f2, %f84, %f77;
	fma.rn.f32 	%f81, %f3, %f84, %f78;
	cvta.to.global.u64 	%rd59, %rd16;
	shl.b64 	%rd60, %rd2, 2;
	add.s64 	%rd61, %rd59, %rd60;
	st.global.f32 	[%rd61], %f79;
	cvta.to.global.u64 	%rd62, %rd17;
	add.s64 	%rd63, %rd62, %rd60;
	st.global.f32 	[%rd63], %f80;
	cvta.to.global.u64 	%rd64, %rd18;
	add.s64 	%rd65, %rd64, %rd60;
	st.global.f32 	[%rd65], %f81;

$L__BB0_29:
	ret;

}

`
 )
