package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for pw_mod kernel
var pw_mod_code cu.Function

// Stores the arguments for pw_mod kernel invocation
type pw_mod_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_b unsafe.Pointer
	 arg_N int
	 argptr [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for pw_mod kernel invocation
var pw_mod_args pw_mod_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 pw_mod_args.argptr[0] = unsafe.Pointer(&pw_mod_args.arg_dst)
	 pw_mod_args.argptr[1] = unsafe.Pointer(&pw_mod_args.arg_a)
	 pw_mod_args.argptr[2] = unsafe.Pointer(&pw_mod_args.arg_b)
	 pw_mod_args.argptr[3] = unsafe.Pointer(&pw_mod_args.arg_N)
	 }

// Wrapper for pw_mod CUDA kernel, asynchronous.
func k_pw_mod_async ( dst unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("pw_mod")
	}

	pw_mod_args.Lock()
	defer pw_mod_args.Unlock()

	if pw_mod_code == 0{
		pw_mod_code = fatbinLoad(pw_mod_map, "pw_mod")
	}

	 pw_mod_args.arg_dst = dst
	 pw_mod_args.arg_a = a
	 pw_mod_args.arg_b = b
	 pw_mod_args.arg_N = N
	

	args := pw_mod_args.argptr[:]
	cu.LaunchKernel(pw_mod_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("pw_mod")
	}
}

// maps compute capability on PTX code for pw_mod kernel.
var pw_mod_map = map[int]string{ 0: "" ,
61: pw_mod_ptx_61  }

// pw_mod PTX code for various compute capabilities.
const(
  pw_mod_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	pw_mod

.visible .entry pw_mod(
	.param .u64 pw_mod_param_0,
	.param .u64 pw_mod_param_1,
	.param .u64 pw_mod_param_2,
	.param .u32 pw_mod_param_3
)
{
	.reg .pred 	%p<17>;
	.reg .f32 	%f<47>;
	.reg .b32 	%r<37>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [pw_mod_param_0];
	ld.param.u64 	%rd3, [pw_mod_param_1];
	ld.param.u64 	%rd4, [pw_mod_param_2];
	ld.param.u32 	%r10, [pw_mod_param_3];
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %nctaid.x;
	mov.u32 	%r13, %ctaid.x;
	mad.lo.s32 	%r14, %r11, %r12, %r13;
	mov.u32 	%r15, %ntid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r14, %r15, %r16;
	setp.ge.s32 	%p1, %r1, %r10;
	@%p1 bra 	$L__BB0_14;

	cvta.to.global.u64 	%rd5, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd6, %r1, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvta.to.global.u64 	%rd8, %rd4;
	add.s64 	%rd9, %rd8, %rd6;
	ld.global.nc.f32 	%f20, [%rd9];
	abs.f32 	%f1, %f20;
	ld.global.nc.f32 	%f2, [%rd7];
	abs.f32 	%f46, %f2;
	setp.lt.f32 	%p2, %f46, %f1;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f4, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f46, %f4;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r2, %f46;
	and.b32  	%r20, %r2, 8388607;
	or.b32  	%r35, %r20, 1065353216;
	mov.b32 	%r3, %f4;
	mov.b32 	%f45, %r35;
	add.s32 	%r22, %r3, -192937984;
	and.b32  	%r23, %r22, -8388608;
	sub.s32 	%r24, %r2, %r23;
	and.b32  	%r36, %r24, -8388608;
	setp.eq.s32 	%p9, %r36, 0;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r25, %r3, 8388607;
	or.b32  	%r26, %r25, 1065353216;
	mov.b32 	%f29, %r26;
	rcp.approx.ftz.f32 	%f14, %f29;
	neg.f32 	%f15, %f29;

$L__BB0_11:
	min.u32 	%r28, %r36, 192937984;
	add.s32 	%r29, %r28, %r35;
	mov.b32 	%f30, %r29;
	mov.f32 	%f31, 0f80000000;
	fma.rn.f32 	%f32, %f30, %f14, %f31;
	fma.rn.f32 	%f33, %f15, %f32, %f30;
	fma.rn.f32 	%f34, %f33, %f14, %f32;
	fma.rn.f32 	%f35, %f15, %f34, %f30;
	fma.rz.f32 	%f36, %f35, %f14, %f34;
	cvt.rzi.f32.f32 	%f37, %f36;
	fma.rn.f32 	%f45, %f15, %f37, %f30;
	sub.s32 	%r36, %r36, %r28;
	mov.b32 	%r35, %f45;
	setp.ne.s32 	%p10, %r36, 0;
	setp.ne.s32 	%p11, %r35, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	and.b32  	%r30, %r3, -8388608;
	mov.b32 	%f38, %r30;
	setp.gt.u32 	%p13, %r2, 2139095039;
	setp.leu.f32 	%p14, %f1, 0f00000000;
	or.pred  	%p15, %p14, %p13;
	selp.f32 	%f39, 0f7FFFFFFF, %f38, %p15;
	mul.f32 	%f40, %f45, 0f34000000;
	mul.f32 	%f46, %f39, %f40;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f21, %f46, %f1;
	cvt.rzi.f32.f32 	%f44, %f21;
	neg.f32 	%f6, %f1;
	fma.rn.f32 	%f7, %f6, %f44, %f46;
	mov.b32 	%r17, %f7;
	mov.b32 	%r18, %f1;
	setp.lt.u32 	%p4, %r17, %r18;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r17, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f27, %f44, 0fBF800000;
	add.f32 	%f28, %f27, 0fBF800000;
	setp.lt.f32 	%p8, %f7, %f6;
	selp.f32 	%f44, %f28, %f27, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f44, %f44, 0f3F800000;
	add.f32 	%f22, %f1, %f1;
	setp.ltu.f32 	%p6, %f7, %f22;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f23, %f44, 0f3F800000;
	mov.f32 	%f24, 0fC0400000;
	fma.rn.f32 	%f25, %f24, %f1, %f7;
	setp.ge.f32 	%p7, %f25, 0f00000000;
	add.f32 	%f26, %f23, 0f3F800000;
	selp.f32 	%f44, %f26, %f23, %p7;

$L__BB0_8:
	fma.rn.f32 	%f46, %f6, %f44, %f46;

$L__BB0_13:
	abs.f32 	%f41, %f46;
	setp.gtu.f32 	%p16, %f41, 0f7F800000;
	mov.b32 	%r31, %f2;
	and.b32  	%r32, %r31, -2147483648;
	mov.b32 	%r33, %f46;
	or.b32  	%r34, %r32, %r33;
	mov.b32 	%f42, %r34;
	selp.f32 	%f43, %f46, %f42, %p16;
	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f43;

$L__BB0_14:
	ret;

}

`
 )
