package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for parallel_transport kernel
var parallel_transport_code cu.Function

// Stores the arguments for parallel_transport kernel invocation
type parallel_transport_args_t struct{
	 arg_outx unsafe.Pointer
	 arg_outy unsafe.Pointer
	 arg_outz unsafe.Pointer
	 arg_m0x unsafe.Pointer
	 arg_m0y unsafe.Pointer
	 arg_m0z unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_k0x unsafe.Pointer
	 arg_k0y unsafe.Pointer
	 arg_k0z unsafe.Pointer
	 arg_N int
	 argptr [13]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for parallel_transport kernel invocation
var parallel_transport_args parallel_transport_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 parallel_transport_args.argptr[0] = unsafe.Pointer(&parallel_transport_args.arg_outx)
	 parallel_transport_args.argptr[1] = unsafe.Pointer(&parallel_transport_args.arg_outy)
	 parallel_transport_args.argptr[2] = unsafe.Pointer(&parallel_transport_args.arg_outz)
	 parallel_transport_args.argptr[3] = unsafe.Pointer(&parallel_transport_args.arg_m0x)
	 parallel_transport_args.argptr[4] = unsafe.Pointer(&parallel_transport_args.arg_m0y)
	 parallel_transport_args.argptr[5] = unsafe.Pointer(&parallel_transport_args.arg_m0z)
	 parallel_transport_args.argptr[6] = unsafe.Pointer(&parallel_transport_args.arg_mx)
	 parallel_transport_args.argptr[7] = unsafe.Pointer(&parallel_transport_args.arg_my)
	 parallel_transport_args.argptr[8] = unsafe.Pointer(&parallel_transport_args.arg_mz)
	 parallel_transport_args.argptr[9] = unsafe.Pointer(&parallel_transport_args.arg_k0x)
	 parallel_transport_args.argptr[10] = unsafe.Pointer(&parallel_transport_args.arg_k0y)
	 parallel_transport_args.argptr[11] = unsafe.Pointer(&parallel_transport_args.arg_k0z)
	 parallel_transport_args.argptr[12] = unsafe.Pointer(&parallel_transport_args.arg_N)
	 }

// Wrapper for parallel_transport CUDA kernel, asynchronous.
func k_parallel_transport_async ( outx unsafe.Pointer, outy unsafe.Pointer, outz unsafe.Pointer, m0x unsafe.Pointer, m0y unsafe.Pointer, m0z unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, k0x unsafe.Pointer, k0y unsafe.Pointer, k0z unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("parallel_transport")
	}

	parallel_transport_args.Lock()
	defer parallel_transport_args.Unlock()

	if parallel_transport_code == 0{
		parallel_transport_code = fatbinLoad(parallel_transport_map, "parallel_transport")
	}

	 parallel_transport_args.arg_outx = outx
	 parallel_transport_args.arg_outy = outy
	 parallel_transport_args.arg_outz = outz
	 parallel_transport_args.arg_m0x = m0x
	 parallel_transport_args.arg_m0y = m0y
	 parallel_transport_args.arg_m0z = m0z
	 parallel_transport_args.arg_mx = mx
	 parallel_transport_args.arg_my = my
	 parallel_transport_args.arg_mz = mz
	 parallel_transport_args.arg_k0x = k0x
	 parallel_transport_args.arg_k0y = k0y
	 parallel_transport_args.arg_k0z = k0z
	 parallel_transport_args.arg_N = N
	

	args := parallel_transport_args.argptr[:]
	cu.LaunchKernel(parallel_transport_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("parallel_transport")
	}
}

// maps compute capability on PTX code for parallel_transport kernel.
var parallel_transport_map = map[int]string{ 0: "" ,
61: parallel_transport_ptx_61  }

// parallel_transport PTX code for various compute capabilities.
const(
  parallel_transport_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	parallel_transport

.visible .entry parallel_transport(
	.param .u64 parallel_transport_param_0,
	.param .u64 parallel_transport_param_1,
	.param .u64 parallel_transport_param_2,
	.param .u64 parallel_transport_param_3,
	.param .u64 parallel_transport_param_4,
	.param .u64 parallel_transport_param_5,
	.param .u64 parallel_transport_param_6,
	.param .u64 parallel_transport_param_7,
	.param .u64 parallel_transport_param_8,
	.param .u64 parallel_transport_param_9,
	.param .u64 parallel_transport_param_10,
	.param .u64 parallel_transport_param_11,
	.param .u32 parallel_transport_param_12
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<36>;
	.reg .b32 	%r<16>;
	.reg .b64 	%rd<39>;


	ld.param.u64 	%rd1, [parallel_transport_param_0];
	ld.param.u64 	%rd2, [parallel_transport_param_1];
	ld.param.u64 	%rd3, [parallel_transport_param_2];
	ld.param.u64 	%rd4, [parallel_transport_param_3];
	ld.param.u64 	%rd5, [parallel_transport_param_4];
	ld.param.u64 	%rd6, [parallel_transport_param_5];
	ld.param.u64 	%rd7, [parallel_transport_param_6];
	ld.param.u64 	%rd8, [parallel_transport_param_7];
	ld.param.u64 	%rd9, [parallel_transport_param_8];
	ld.param.u64 	%rd10, [parallel_transport_param_9];
	ld.param.u64 	%rd11, [parallel_transport_param_10];
	ld.param.u64 	%rd12, [parallel_transport_param_11];
	ld.param.u32 	%r2, [parallel_transport_param_12];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_5;

	cvta.to.global.u64 	%rd13, %rd4;
	mul.wide.s32 	%rd14, %r1, 4;
	add.s64 	%rd15, %rd13, %rd14;
	cvta.to.global.u64 	%rd16, %rd5;
	add.s64 	%rd17, %rd16, %rd14;
	cvta.to.global.u64 	%rd18, %rd6;
	add.s64 	%rd19, %rd18, %rd14;
	cvta.to.global.u64 	%rd20, %rd7;
	add.s64 	%rd21, %rd20, %rd14;
	cvta.to.global.u64 	%rd22, %rd8;
	add.s64 	%rd23, %rd22, %rd14;
	cvta.to.global.u64 	%rd24, %rd9;
	add.s64 	%rd25, %rd24, %rd14;
	cvta.to.global.u64 	%rd26, %rd10;
	add.s64 	%rd27, %rd26, %rd14;
	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd29, %rd28, %rd14;
	cvta.to.global.u64 	%rd30, %rd12;
	add.s64 	%rd31, %rd30, %rd14;
	ld.global.f32 	%f1, [%rd21];
	ld.global.f32 	%f2, [%rd15];
	ld.global.f32 	%f3, [%rd23];
	ld.global.f32 	%f4, [%rd17];
	mul.f32 	%f21, %f4, %f3;
	fma.rn.f32 	%f22, %f2, %f1, %f21;
	ld.global.f32 	%f5, [%rd25];
	ld.global.f32 	%f6, [%rd19];
	fma.rn.f32 	%f23, %f6, %f5, %f22;
	ld.global.f32 	%f7, [%rd27];
	ld.global.f32 	%f8, [%rd29];
	mul.f32 	%f24, %f3, %f8;
	fma.rn.f32 	%f25, %f1, %f7, %f24;
	ld.global.f32 	%f9, [%rd31];
	fma.rn.f32 	%f10, %f5, %f9, %f25;
	add.f32 	%f11, %f23, 0f3F800000;
	setp.gt.f32 	%p2, %f11, 0f33D6BF95;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	div.rn.f32 	%f26, %f10, %f11;
	add.f32 	%f27, %f2, %f1;
	mul.f32 	%f35, %f27, %f26;
	add.f32 	%f28, %f4, %f3;
	mul.f32 	%f34, %f28, %f26;
	add.f32 	%f29, %f6, %f5;
	mul.f32 	%f33, %f29, %f26;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	mul.f32 	%f35, %f1, %f10;
	mul.f32 	%f34, %f3, %f10;
	mul.f32 	%f33, %f5, %f10;

$L__BB0_4:
	cvta.to.global.u64 	%rd32, %rd1;
	add.s64 	%rd34, %rd32, %rd14;
	sub.f32 	%f30, %f7, %f35;
	st.global.f32 	[%rd34], %f30;
	cvta.to.global.u64 	%rd35, %rd2;
	add.s64 	%rd36, %rd35, %rd14;
	sub.f32 	%f31, %f8, %f34;
	st.global.f32 	[%rd36], %f31;
	cvta.to.global.u64 	%rd37, %rd3;
	add.s64 	%rd38, %rd37, %rd14;
	sub.f32 	%f32, %f9, %f33;
	st.global.f32 	[%rd38], %f32;

$L__BB0_5:
	ret;

}

`
 )
