package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for pw_pow kernel
var pw_pow_code cu.Function

// Stores the arguments for pw_pow kernel invocation
type pw_pow_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_b unsafe.Pointer
	 arg_N int
	 argptr [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for pw_pow kernel invocation
var pw_pow_args pw_pow_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 pw_pow_args.argptr[0] = unsafe.Pointer(&pw_pow_args.arg_dst)
	 pw_pow_args.argptr[1] = unsafe.Pointer(&pw_pow_args.arg_a)
	 pw_pow_args.argptr[2] = unsafe.Pointer(&pw_pow_args.arg_b)
	 pw_pow_args.argptr[3] = unsafe.Pointer(&pw_pow_args.arg_N)
	 }

// Wrapper for pw_pow CUDA kernel, asynchronous.
func k_pw_pow_async ( dst unsafe.Pointer, a unsafe.Pointer, b unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("pw_pow")
	}

	pw_pow_args.Lock()
	defer pw_pow_args.Unlock()

	if pw_pow_code == 0{
		pw_pow_code = fatbinLoad(pw_pow_map, "pw_pow")
	}

	 pw_pow_args.arg_dst = dst
	 pw_pow_args.arg_a = a
	 pw_pow_args.arg_b = b
	 pw_pow_args.arg_N = N
	

	args := pw_pow_args.argptr[:]
	cu.LaunchKernel(pw_pow_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("pw_pow")
	}
}

// maps compute capability on PTX code for pw_pow kernel.
var pw_pow_map = map[int]string{ 0: "" ,
61: pw_pow_ptx_61  }

// pw_pow PTX code for various compute capabilities.
const(
  pw_pow_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	pw_pow

.visible .entry pw_pow(
	.param .u64 pw_pow_param_0,
	.param .u64 pw_pow_param_1,
	.param .u64 pw_pow_param_2,
	.param .u32 pw_pow_param_3
)
{
	.reg .pred 	%p<40>;
	.reg .f32 	%f<174>;
	.reg .b32 	%r<37>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd3, [pw_pow_param_0];
	ld.param.u64 	%rd4, [pw_pow_param_1];
	ld.param.u64 	%rd5, [pw_pow_param_2];
	ld.param.u32 	%r2, [pw_pow_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_20;

	cvta.to.global.u64 	%rd6, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	setp.lt.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd9, %rd5;
	add.s64 	%rd2, %rd9, %rd7;
	mov.f32 	%f172, 0f3F800000;
	@%p2 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_2;

$L__BB0_9:
	neg.f32 	%f8, %f1;
	ld.global.nc.f32 	%f9, [%rd2];
	mul.f32 	%f96, %f9, 0f3F000000;
	cvt.rzi.f32.f32 	%f97, %f96;
	add.f32 	%f98, %f97, %f97;
	sub.f32 	%f99, %f9, %f98;
	abs.f32 	%f10, %f99;
	abs.f32 	%f11, %f8;
	setp.lt.f32 	%p20, %f11, 0f00800000;
	mul.f32 	%f100, %f11, 0f4B800000;
	selp.f32 	%f101, %f100, %f11, %p20;
	selp.f32 	%f102, 0fC1C00000, 0f00000000, %p20;
	mov.b32 	%r23, %f101;
	add.s32 	%r24, %r23, -1060439283;
	and.b32  	%r25, %r24, -8388608;
	sub.s32 	%r26, %r23, %r25;
	mov.b32 	%f103, %r26;
	cvt.rn.f32.s32 	%f104, %r25;
	mov.f32 	%f105, 0f34000000;
	fma.rn.f32 	%f106, %f104, %f105, %f102;
	add.f32 	%f107, %f103, 0fBF800000;
	add.f32 	%f108, %f103, 0f3F800000;
	mov.f32 	%f95, 0f3F800000;
	rcp.approx.ftz.f32 	%f109, %f108;
	add.f32 	%f110, %f107, %f107;
	mul.f32 	%f111, %f110, %f109;
	mul.f32 	%f112, %f111, %f111;
	sub.f32 	%f113, %f107, %f111;
	add.f32 	%f114, %f113, %f113;
	neg.f32 	%f115, %f111;
	fma.rn.f32 	%f116, %f115, %f107, %f114;
	mul.rn.f32 	%f117, %f109, %f116;
	mov.f32 	%f118, 0f3B52E7DB;
	mov.f32 	%f119, 0f3A2C32E4;
	fma.rn.f32 	%f120, %f119, %f112, %f118;
	mov.f32 	%f121, 0f3C93BB73;
	fma.rn.f32 	%f122, %f120, %f112, %f121;
	mov.f32 	%f123, 0f3DF6384F;
	fma.rn.f32 	%f124, %f122, %f112, %f123;
	mul.rn.f32 	%f125, %f124, %f112;
	mov.f32 	%f126, 0f3FB8AA3B;
	fma.rn.f32 	%f127, %f111, %f126, %f106;
	sub.f32 	%f128, %f106, %f127;
	fma.rn.f32 	%f129, %f111, %f126, %f128;
	fma.rn.f32 	%f130, %f117, %f126, %f129;
	mov.f32 	%f131, 0f32A55E34;
	fma.rn.f32 	%f132, %f111, %f131, %f130;
	mul.f32 	%f133, %f125, 0f40400000;
	fma.rn.f32 	%f134, %f133, %f117, %f132;
	fma.rn.f32 	%f135, %f125, %f111, %f134;
	add.rn.f32 	%f136, %f127, %f135;
	neg.f32 	%f137, %f127;
	add.rn.f32 	%f138, %f136, %f137;
	neg.f32 	%f139, %f138;
	add.rn.f32 	%f140, %f135, %f139;
	mul.rn.f32 	%f141, %f136, %f9;
	neg.f32 	%f142, %f141;
	fma.rn.f32 	%f143, %f136, %f9, %f142;
	fma.rn.f32 	%f144, %f140, %f9, %f143;
	cvt.rni.f32.f32 	%f145, %f141;
	sub.f32 	%f146, %f141, %f145;
	add.f32 	%f147, %f144, %f146;
	mov.f32 	%f148, 0f3AAF85ED;
	mov.f32 	%f149, 0f391FCB8E;
	fma.rn.f32 	%f150, %f149, %f147, %f148;
	mov.f32 	%f151, 0f3C1D9856;
	fma.rn.f32 	%f152, %f150, %f147, %f151;
	mov.f32 	%f153, 0f3D6357BB;
	fma.rn.f32 	%f154, %f152, %f147, %f153;
	mov.f32 	%f155, 0f3E75FDEC;
	fma.rn.f32 	%f156, %f154, %f147, %f155;
	mov.f32 	%f157, 0f3F317218;
	fma.rn.f32 	%f158, %f156, %f147, %f157;
	fma.rn.f32 	%f159, %f158, %f147, %f95;
	cvt.rzi.s32.f32 	%r27, %f145;
	setp.gt.f32 	%p21, %f145, 0f00000000;
	selp.b32 	%r28, 0, -2097152000, %p21;
	add.s32 	%r29, %r28, 2130706432;
	mov.b32 	%f160, %r29;
	mul.f32 	%f161, %f159, %f160;
	shl.b32 	%r30, %r27, 23;
	sub.s32 	%r31, %r30, %r28;
	mov.b32 	%f162, %r31;
	mul.f32 	%f163, %f161, %f162;
	abs.f32 	%f164, %f141;
	setp.gt.f32 	%p22, %f164, 0f43180000;
	setp.lt.f32 	%p23, %f141, 0f00000000;
	selp.f32 	%f165, 0f00000000, 0f7F800000, %p23;
	selp.f32 	%f12, %f165, %f163, %p22;
	setp.eq.f32 	%p24, %f9, 0f00000000;
	setp.eq.f32 	%p25, %f1, 0fBF800000;
	or.pred  	%p26, %p25, %p24;
	@%p26 bra 	$L__BB0_18;

	setp.gtu.f32 	%p27, %f11, 0f7F800000;
	@%p27 bra 	$L__BB0_17;

	abs.f32 	%f13, %f9;
	setp.gtu.f32 	%p28, %f13, 0f7F800000;
	@%p28 bra 	$L__BB0_17;
	bra.uni 	$L__BB0_12;

$L__BB0_17:
	add.rn.f32 	%f172, %f8, %f9;

$L__BB0_18:
	neg.f32 	%f173, %f172;
	bra.uni 	$L__BB0_19;

$L__BB0_2:
	ld.global.nc.f32 	%f2, [%rd2];
	abs.f32 	%f3, %f1;
	setp.eq.f32 	%p3, %f2, 0f00000000;
	setp.eq.f32 	%p4, %f1, 0f3F800000;
	mov.f32 	%f173, 0f3F800000;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_19;

	setp.gtu.f32 	%p6, %f3, 0f7F800000;
	@%p6 bra 	$L__BB0_8;

	abs.f32 	%f4, %f2;
	setp.gtu.f32 	%p7, %f4, 0f7F800000;
	@%p7 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_5;

$L__BB0_8:
	add.rn.f32 	%f173, %f1, %f2;

$L__BB0_19:
	cvta.to.global.u64 	%rd10, %rd3;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f173;

$L__BB0_20:
	ret;

$L__BB0_12:
	setp.eq.f32 	%p29, %f1, 0f80000000;
	setp.eq.f32 	%p30, %f11, 0f7F800000;
	or.pred  	%p31, %p29, %p30;
	@%p31 bra 	$L__BB0_16;
	bra.uni 	$L__BB0_13;

$L__BB0_16:
	setp.eq.f32 	%p38, %f10, 0f3F800000;
	sub.f32 	%f170, %f8, %f1;
	mov.b32 	%r32, %f170;
	xor.b32  	%r33, %r32, 2139095040;
	setp.lt.f32 	%p39, %f9, 0f00000000;
	selp.b32 	%r34, %r33, %r32, %p39;
	and.b32  	%r35, %r34, 2147483647;
	selp.b32 	%r36, %r34, %r35, %p38;
	mov.b32 	%f172, %r36;
	bra.uni 	$L__BB0_18;

$L__BB0_5:
	setp.eq.f32 	%p8, %f1, 0f00000000;
	setp.eq.f32 	%p9, %f3, 0f7F800000;
	or.pred  	%p10, %p8, %p9;
	@%p10 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_6;

$L__BB0_7:
	mul.f32 	%f89, %f2, 0f3F000000;
	cvt.rzi.f32.f32 	%f90, %f89;
	add.f32 	%f91, %f90, %f90;
	sub.f32 	%f92, %f2, %f91;
	abs.f32 	%f93, %f92;
	setp.eq.f32 	%p18, %f93, 0f3F800000;
	add.f32 	%f94, %f1, %f1;
	mov.b32 	%r18, %f94;
	xor.b32  	%r19, %r18, 2139095040;
	setp.lt.f32 	%p19, %f2, 0f00000000;
	selp.b32 	%r20, %r19, %r18, %p19;
	and.b32  	%r21, %r20, 2147483647;
	selp.b32 	%r22, %r20, %r21, %p18;
	mov.b32 	%f173, %r22;
	bra.uni 	$L__BB0_19;

$L__BB0_13:
	setp.eq.f32 	%p32, %f1, 0f3F800000;
	setp.eq.f32 	%p33, %f13, 0f7F800000;
	and.pred  	%p34, %p32, %p33;
	@%p34 bra 	$L__BB0_18;

	setp.leu.f32 	%p35, %f1, 0f80000000;
	mov.f32 	%f172, %f12;
	@%p35 bra 	$L__BB0_18;

	setp.eq.f32 	%p36, %f10, 0f3F800000;
	neg.f32 	%f167, %f12;
	selp.f32 	%f168, %f167, %f12, %p36;
	cvt.rmi.f32.f32 	%f169, %f9;
	setp.neu.f32 	%p37, %f169, %f9;
	selp.f32 	%f172, 0f7FFFFFFF, %f168, %p37;
	bra.uni 	$L__BB0_18;

$L__BB0_6:
	setp.lt.f32 	%p11, %f3, 0f00800000;
	mul.f32 	%f21, %f3, 0f4B800000;
	selp.f32 	%f22, %f21, %f3, %p11;
	mov.b32 	%r9, %f22;
	add.s32 	%r10, %r9, -1060439283;
	and.b32  	%r11, %r10, -8388608;
	sub.s32 	%r12, %r9, %r11;
	mov.b32 	%f23, %r12;
	selp.f32 	%f24, 0fC1C00000, 0f00000000, %p11;
	cvt.rn.f32.s32 	%f25, %r11;
	mov.f32 	%f26, 0f34000000;
	fma.rn.f32 	%f27, %f25, %f26, %f24;
	add.f32 	%f28, %f23, 0fBF800000;
	add.f32 	%f29, %f23, 0f3F800000;
	mov.f32 	%f30, 0f3F800000;
	rcp.approx.ftz.f32 	%f31, %f29;
	add.f32 	%f32, %f28, %f28;
	mul.f32 	%f33, %f32, %f31;
	mul.f32 	%f34, %f33, %f33;
	sub.f32 	%f35, %f28, %f33;
	add.f32 	%f36, %f35, %f35;
	neg.f32 	%f37, %f33;
	fma.rn.f32 	%f38, %f37, %f28, %f36;
	mul.rn.f32 	%f39, %f31, %f38;
	mov.f32 	%f40, 0f3B52E7DB;
	mov.f32 	%f41, 0f3A2C32E4;
	fma.rn.f32 	%f42, %f41, %f34, %f40;
	mov.f32 	%f43, 0f3C93BB73;
	fma.rn.f32 	%f44, %f42, %f34, %f43;
	mov.f32 	%f45, 0f3DF6384F;
	fma.rn.f32 	%f46, %f44, %f34, %f45;
	mul.rn.f32 	%f47, %f46, %f34;
	mov.f32 	%f48, 0f3FB8AA3B;
	fma.rn.f32 	%f49, %f33, %f48, %f27;
	sub.f32 	%f50, %f27, %f49;
	fma.rn.f32 	%f51, %f33, %f48, %f50;
	fma.rn.f32 	%f52, %f39, %f48, %f51;
	mov.f32 	%f53, 0f32A55E34;
	fma.rn.f32 	%f54, %f33, %f53, %f52;
	mul.f32 	%f55, %f47, 0f40400000;
	fma.rn.f32 	%f56, %f55, %f39, %f54;
	fma.rn.f32 	%f57, %f47, %f33, %f56;
	add.rn.f32 	%f58, %f49, %f57;
	mul.rn.f32 	%f59, %f58, %f2;
	cvt.rni.f32.f32 	%f60, %f59;
	neg.f32 	%f61, %f49;
	add.rn.f32 	%f62, %f58, %f61;
	neg.f32 	%f63, %f62;
	add.rn.f32 	%f64, %f57, %f63;
	neg.f32 	%f65, %f59;
	fma.rn.f32 	%f66, %f58, %f2, %f65;
	fma.rn.f32 	%f67, %f64, %f2, %f66;
	sub.f32 	%f68, %f59, %f60;
	add.f32 	%f69, %f67, %f68;
	setp.gt.f32 	%p12, %f60, 0f00000000;
	selp.b32 	%r13, 0, -2097152000, %p12;
	setp.eq.f32 	%p13, %f1, 0fBF800000;
	setp.eq.f32 	%p14, %f4, 0f7F800000;
	and.pred  	%p15, %p13, %p14;
	mov.f32 	%f70, 0f3AAF85ED;
	mov.f32 	%f71, 0f391FCB8E;
	fma.rn.f32 	%f72, %f71, %f69, %f70;
	mov.f32 	%f73, 0f3C1D9856;
	fma.rn.f32 	%f74, %f72, %f69, %f73;
	mov.f32 	%f75, 0f3D6357BB;
	fma.rn.f32 	%f76, %f74, %f69, %f75;
	mov.f32 	%f77, 0f3E75FDEC;
	fma.rn.f32 	%f78, %f76, %f69, %f77;
	mov.f32 	%f79, 0f3F317218;
	fma.rn.f32 	%f80, %f78, %f69, %f79;
	fma.rn.f32 	%f81, %f80, %f69, %f30;
	add.s32 	%r14, %r13, 2130706432;
	mov.b32 	%f82, %r14;
	mul.f32 	%f83, %f81, %f82;
	cvt.rzi.s32.f32 	%r15, %f60;
	shl.b32 	%r16, %r15, 23;
	sub.s32 	%r17, %r16, %r13;
	mov.b32 	%f84, %r17;
	mul.f32 	%f85, %f83, %f84;
	abs.f32 	%f86, %f59;
	setp.gt.f32 	%p16, %f86, 0f43180000;
	setp.lt.f32 	%p17, %f59, 0f00000000;
	selp.f32 	%f87, 0f00000000, 0f7F800000, %p17;
	selp.f32 	%f88, %f87, %f85, %p16;
	selp.f32 	%f173, 0f3F800000, %f88, %p15;
	bra.uni 	$L__BB0_19;

}

`
 )
