package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for precond_step kernel
var precond_step_code cu.Function

// Stores the arguments for precond_step kernel invocation
type precond_step_args_t struct{
	 arg_px unsafe.Pointer
	 arg_py unsafe.Pointer
	 arg_pz unsafe.Pointer
	 arg_avg unsafe.Pointer
	 arg_kx unsafe.Pointer
	 arg_ky unsafe.Pointer
	 arg_kz unsafe.Pointer
	 arg_decay float32
	 arg_eps float32
	 arg_N int
	 argptr [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for precond_step kernel invocation
var precond_step_args precond_step_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 precond_step_args.argptr[0] = unsafe.Pointer(&precond_step_args.arg_px)
	 precond_step_args.argptr[1] = unsafe.Pointer(&precond_step_args.arg_py)
	 precond_step_args.argptr[2] = unsafe.Pointer(&precond_step_args.arg_pz)
	 precond_step_args.argptr[3] = unsafe.Pointer(&precond_step_args.arg_avg)
	 precond_step_args.argptr[4] = unsafe.Pointer(&precond_step_args.arg_kx)
	 precond_step_args.argptr[5] = unsafe.Pointer(&precond_step_args.arg_ky)
	 precond_step_args.argptr[6] = unsafe.Pointer(&precond_step_args.arg_kz)
	 precond_step_args.argptr[7] = unsafe.Pointer(&precond_step_args.arg_decay)
	 precond_step_args.argptr[8] = unsafe.Pointer(&precond_step_args.arg_eps)
	 precond_step_args.argptr[9] = unsafe.Pointer(&precond_step_args.arg_N)
	 }

// Wrapper for precond_step CUDA kernel, asynchronous.
func k_precond_step_async ( px unsafe.Pointer, py unsafe.Pointer, pz unsafe.Pointer, avg unsafe.Pointer, kx unsafe.Pointer, ky unsafe.Pointer, kz unsafe.Pointer, decay float32, eps float32, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("precond_step")
	}

	precond_step_args.Lock()
	defer precond_step_args.Unlock()

	if precond_step_code == 0{
		precond_step_code = fatbinLoad(precond_step_map, "precond_step")
	}

	 precond_step_args.arg_px = px
	 precond_step_args.arg_py = py
	 precond_step_args.arg_pz = pz
	 precond_step_args.arg_avg = avg
	 precond_step_args.arg_kx = kx
	 precond_step_args.arg_ky = ky
	 precond_step_args.arg_kz = kz
	 precond_step_args.arg_decay = decay
	 precond_step_args.arg_eps = eps
	 precond_step_args.arg_N = N
	

	args := precond_step_args.argptr[:]
	cu.LaunchKernel(precond_step_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("precond_step")
	}
}

// maps compute capability on PTX code for precond_step kernel.
var precond_step_map = map[int]string{ 0: "" ,
61: precond_step_ptx_61  }

// precond_step PTX code for various compute capabilities.
const(
  precond_step_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	precond_step

.visible .entry precond_step(
	.param .u64 precond_step_param_0,
	.param .u64 precond_step_param_1,
	.param .u64 precond_step_param_2,
	.param .u64 precond_step_param_3,
	.param .u64 precond_step_param_4,
	.param .u64 precond_step_param_5,
	.param .u64 precond_step_param_6,
	.param .f32 precond_step_param_7,
	.param .f32 precond_step_param_8,
	.param .u32 precond_step_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<20>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<23>;


	ld.param.u64 	%rd1, [precond_step_param_0];
	ld.param.u64 	%rd2, [precond_step_param_1];
	ld.param.u64 	%rd3, [precond_step_param_2];
	ld.param.u64 	%rd4, [precond_step_param_3];
	ld.param.u64 	%rd5, [precond_step_param_4];
	ld.param.u64 	%rd6, [precond_step_param_5];
	ld.param.u64 	%rd7, [precond_step_param_6];
	ld.param.f32 	%f1, [precond_step_param_7];
	ld.param.f32 	%f2, [precond_step_param_8];
	ld.param.u32 	%r2, [precond_step_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd8, %rd5;
	mul.wide.s32 	%rd9, %r1, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	cvta.to.global.u64 	%rd11, %rd6;
	add.s64 	%rd12, %rd11, %rd9;
	ld.global.nc.f32 	%f4, [%rd12];
	mul.f32 	%f5, %f4, %f4;
	fma.rn.f32 	%f6, %f3, %f3, %f5;
	cvta.to.global.u64 	%rd13, %rd7;
	add.s64 	%rd14, %rd13, %rd9;
	ld.global.nc.f32 	%f7, [%rd14];
	fma.rn.f32 	%f8, %f7, %f7, %f6;
	cvta.to.global.u64 	%rd15, %rd4;
	add.s64 	%rd16, %rd15, %rd9;
	ld.global.f32 	%f9, [%rd16];
	mov.f32 	%f10, 0f3F800000;
	sub.f32 	%f11, %f10, %f1;
	mul.f32 	%f12, %f11, %f8;
	fma.rn.f32 	%f13, %f9, %f1, %f12;
	st.global.f32 	[%rd16], %f13;
	sqrt.rn.f32 	%f14, %f13;
	add.f32 	%f15, %f14, %f2;
	rcp.rn.f32 	%f16, %f15;
	mul.f32 	%f17, %f3, %f16;
	cvta.to.global.u64 	%rd17, %rd1;
	add.s64 	%rd18, %rd17, %rd9;
	st.global.f32 	[%rd18], %f17;
	mul.f32 	%f18, %f16, %f4;
	cvta.to.global.u64 	%rd19, %rd2;
	add.s64 	%rd20, %rd19, %rd9;
	st.global.f32 	[%rd20], %f18;
	mul.f32 	%f19, %f16, %f7;
	cvta.to.global.u64 	%rd21, %rd3;
	add.s64 	%rd22, %rd21, %rd9;
	st.global.f32 	[%rd22], %f19;

$L__BB0_2:
	ret;

}

`
 )
