package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for project_tangent kernel
var project_tangent_code cu.Function

// Stores the arguments for project_tangent kernel invocation
type project_tangent_args_t struct{
	 arg_vx unsafe.Pointer
	 arg_vy unsafe.Pointer
	 arg_vz unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_N int
	 argptr [7]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for project_tangent kernel invocation
var project_tangent_args project_tangent_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 project_tangent_args.argptr[0] = unsafe.Pointer(&project_tangent_args.arg_vx)
	 project_tangent_args.argptr[1] = unsafe.Pointer(&project_tangent_args.arg_vy)
	 project_tangent_args.argptr[2] = unsafe.Pointer(&project_tangent_args.arg_vz)
	 project_tangent_args.argptr[3] = unsafe.Pointer(&project_tangent_args.arg_mx)
	 project_tangent_args.argptr[4] = unsafe.Pointer(&project_tangent_args.arg_my)
	 project_tangent_args.argptr[5] = unsafe.Pointer(&project_tangent_args.arg_mz)
	 project_tangent_args.argptr[6] = unsafe.Pointer(&project_tangent_args.arg_N)
	 }

// Wrapper for project_tangent CUDA kernel, asynchronous.
func k_project_tangent_async ( vx unsafe.Pointer, vy unsafe.Pointer, vz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("project_tangent")
	}

	project_tangent_args.Lock()
	defer project_tangent_args.Unlock()

	if project_tangent_code == 0{
		project_tangent_code = fatbinLoad(project_tangent_map, "project_tangent")
	}

	 project_tangent_args.arg_vx = vx
	 project_tangent_args.arg_vy = vy
	 project_tangent_args.arg_vz = vz
	 project_tangent_args.arg_mx = mx
	 project_tangent_args.arg_my = my
	 project_tangent_args.arg_mz = mz
	 project_tangent_args.arg_N = N
	

	args := project_tangent_args.argptr[:]
	cu.LaunchKernel(project_tangent_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("project_tangent")
	}
}

// maps compute capability on PTX code for project_tangent kernel.
var project_tangent_map = map[int]string{ 0: "" ,
61: project_tangent_ptx_61  }

// project_tangent PTX code for various compute capabilities.
const(
  project_tangent_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	project_tangent

.visible .entry project_tangent(
	.param .u64 project_tangent_param_0,
	.param .u64 project_tangent_param_1,
	.param .u64 project_tangent_param_2,
	.param .u64 project_tangent_param_3,
	.param .u64 project_tangent_param_4,
	.param .u64 project_tangent_param_5,
	.param .u32 project_tangent_param_6
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<16>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [project_tangent_param_0];
	ld.param.u64 	%rd2, [project_tangent_param_1];
	ld.param.u64 	%rd3, [project_tangent_param_2];
	ld.param.u64 	%rd4, [project_tangent_param_3];
	ld.param.u64 	%rd5, [project_tangent_param_4];
	ld.param.u64 	%rd6, [project_tangent_param_5];
	ld.param.u32 	%r2, [project_tangent_param_6];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd1;
	mul.wide.s32 	%rd8, %r1, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd2;
	add.s64 	%rd11, %rd10, %rd8;
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd8;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd8;
	cvta.to.global.u64 	%rd16, %rd5;
	add.s64 	%rd17, %rd16, %rd8;
	cvta.to.global.u64 	%rd18, %rd6;
	add.s64 	%rd19, %rd18, %rd8;
	ld.global.nc.f32 	%f1, [%rd15];
	ld.global.f32 	%f2, [%rd9];
	ld.global.nc.f32 	%f3, [%rd17];
	ld.global.f32 	%f4, [%rd11];
	mul.f32 	%f5, %f4, %f3;
	fma.rn.f32 	%f6, %f2, %f1, %f5;
	ld.global.nc.f32 	%f7, [%rd19];
	ld.global.f32 	%f8, [%rd13];
	fma.rn.f32 	%f9, %f8, %f7, %f6;
	mul.f32 	%f10, %f1, %f9;
	mul.f32 	%f11, %f3, %f9;
	mul.f32 	%f12, %f7, %f9;
	sub.f32 	%f13, %f2, %f10;
	sub.f32 	%f14, %f4, %f11;
	sub.f32 	%f15, %f8, %f12;
	st.global.f32 	[%rd9], %f13;
	st.global.f32 	[%rd11], %f14;
	st.global.f32 	[%rd13], %f15;

$L__BB0_2:
	ret;

}

`
 )
