package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qabs kernel
var Qabs_code cu.Function

// Stores the arguments for Qabs kernel invocation
type Qabs_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qabs kernel invocation
var Qabs_args Qabs_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qabs_args.argptr[0] = unsafe.Pointer(&Qabs_args.arg_dst)
	 Qabs_args.argptr[1] = unsafe.Pointer(&Qabs_args.arg_src)
	 Qabs_args.argptr[2] = unsafe.Pointer(&Qabs_args.arg_N)
	 }

// Wrapper for Qabs CUDA kernel, asynchronous.
func k_Qabs_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qabs")
	}

	Qabs_args.Lock()
	defer Qabs_args.Unlock()

	if Qabs_code == 0{
		Qabs_code = fatbinLoad(Qabs_map, "Qabs")
	}

	 Qabs_args.arg_dst = dst
	 Qabs_args.arg_src = src
	 Qabs_args.arg_N = N
	

	args := Qabs_args.argptr[:]
	cu.LaunchKernel(Qabs_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qabs")
	}
}

// maps compute capability on PTX code for Qabs kernel.
var Qabs_map = map[int]string{ 0: "" ,
61: Qabs_ptx_61  }

// Qabs PTX code for various compute capabilities.
const(
  Qabs_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qabs

.visible .entry Qabs(
	.param .u64 Qabs_param_0,
	.param .u64 Qabs_param_1,
	.param .u32 Qabs_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [Qabs_param_0];
	ld.param.u64 	%rd2, [Qabs_param_1];
	ld.param.u32 	%r2, [Qabs_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f2, %f1;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f2;

$L__BB0_2:
	ret;

}

`
 )
