package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qacosh kernel
var Qacosh_code cu.Function

// Stores the arguments for Qacosh kernel invocation
type Qacosh_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qacosh kernel invocation
var Qacosh_args Qacosh_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qacosh_args.argptr[0] = unsafe.Pointer(&Qacosh_args.arg_dst)
	 Qacosh_args.argptr[1] = unsafe.Pointer(&Qacosh_args.arg_src)
	 Qacosh_args.argptr[2] = unsafe.Pointer(&Qacosh_args.arg_N)
	 }

// Wrapper for Qacosh CUDA kernel, asynchronous.
func k_Qacosh_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qacosh")
	}

	Qacosh_args.Lock()
	defer Qacosh_args.Unlock()

	if Qacosh_code == 0{
		Qacosh_code = fatbinLoad(Qacosh_map, "Qacosh")
	}

	 Qacosh_args.arg_dst = dst
	 Qacosh_args.arg_src = src
	 Qacosh_args.arg_N = N
	

	args := Qacosh_args.argptr[:]
	cu.LaunchKernel(Qacosh_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qacosh")
	}
}

// maps compute capability on PTX code for Qacosh kernel.
var Qacosh_map = map[int]string{ 0: "" ,
61: Qacosh_ptx_61  }

// Qacosh PTX code for various compute capabilities.
const(
  Qacosh_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qacosh

.visible .entry Qacosh(
	.param .u64 Qacosh_param_0,
	.param .u64 Qacosh_param_1,
	.param .u32 Qacosh_param_2
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<80>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd2, [Qacosh_param_0];
	ld.param.u64 	%rd3, [Qacosh_param_1];
	ld.param.u32 	%r3, [Qacosh_param_2];
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ctaid.x;
	mad.lo.s32 	%r7, %r5, %r4, %r6;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	setp.ge.s32 	%p1, %r1, %r3;
	@%p1 bra 	$L__BB0_12;

	cvta.to.global.u64 	%rd4, %rd3;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.ltu.f32 	%p2, %f1, 0f3F800000;
	cvta.to.global.u64 	%rd7, %rd2;
	add.s64 	%rd1, %rd7, %rd5;
	@%p2 bra 	$L__BB0_11;
	bra.uni 	$L__BB0_2;

$L__BB0_11:
	mov.u32 	%r21, 0;
	st.global.u32 	[%rd1], %r21;
	bra.uni 	$L__BB0_12;

$L__BB0_2:
	add.f32 	%f2, %f1, 0fBF800000;
	mov.b32 	%r10, %f2;
	setp.gt.u32 	%p3, %r10, 1258291200;
	@%p3 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_3;

$L__BB0_7:
	setp.lt.f32 	%p7, %f2, 0f00800000;
	mul.f32 	%f48, %f2, 0f4B000000;
	selp.f32 	%f8, %f48, %f2, %p7;
	selp.f32 	%f49, 0fC1B80000, 0f00000000, %p7;
	mov.b32 	%r17, %f8;
	add.s32 	%r18, %r17, -1059760811;
	and.b32  	%r19, %r18, -8388608;
	sub.s32 	%r20, %r17, %r19;
	mov.b32 	%f50, %r20;
	cvt.rn.f32.s32 	%f51, %r19;
	mov.f32 	%f52, 0f34000000;
	fma.rn.f32 	%f53, %f51, %f52, %f49;
	add.f32 	%f54, %f50, 0fBF800000;
	mov.f32 	%f55, 0f3E1039F6;
	mov.f32 	%f56, 0fBE055027;
	fma.rn.f32 	%f57, %f56, %f54, %f55;
	mov.f32 	%f58, 0fBDF8CDCC;
	fma.rn.f32 	%f59, %f57, %f54, %f58;
	mov.f32 	%f60, 0f3E0F2955;
	fma.rn.f32 	%f61, %f59, %f54, %f60;
	mov.f32 	%f62, 0fBE2AD8B9;
	fma.rn.f32 	%f63, %f61, %f54, %f62;
	mov.f32 	%f64, 0f3E4CED0B;
	fma.rn.f32 	%f65, %f63, %f54, %f64;
	mov.f32 	%f66, 0fBE7FFF22;
	fma.rn.f32 	%f67, %f65, %f54, %f66;
	mov.f32 	%f68, 0f3EAAAA78;
	fma.rn.f32 	%f69, %f67, %f54, %f68;
	mov.f32 	%f70, 0fBF000000;
	fma.rn.f32 	%f71, %f69, %f54, %f70;
	mul.f32 	%f72, %f54, %f71;
	fma.rn.f32 	%f73, %f72, %f54, %f54;
	mov.f32 	%f74, 0f3F317218;
	fma.rn.f32 	%f78, %f53, %f74, %f73;
	setp.lt.u32 	%p8, %r17, 2139095040;
	@%p8 bra 	$L__BB0_9;

	mov.f32 	%f75, 0f7F800000;
	fma.rn.f32 	%f78, %f8, %f75, %f75;

$L__BB0_9:
	add.f32 	%f76, %f78, 0f3F317218;
	setp.eq.f32 	%p9, %f8, 0f00000000;
	selp.f32 	%f79, 0fFF800000, %f76, %p9;
	bra.uni 	$L__BB0_10;

$L__BB0_3:
	mul.rz.f32 	%f14, %f1, %f2;
	add.rn.f32 	%f15, %f14, %f2;
	sqrt.rn.f32 	%f16, %f15;
	add.f32 	%f3, %f2, %f16;
	mov.f32 	%f17, 0f3F800000;
	add.rz.f32 	%f18, %f3, %f17;
	mov.b32 	%r11, %f18;
	add.s32 	%r12, %r11, -1061158912;
	and.b32  	%r13, %r12, -8388608;
	mov.b32 	%r2, %f3;
	sub.s32 	%r14, %r2, %r13;
	mov.b32 	%f19, %r14;
	mov.u32 	%r15, 1082130432;
	sub.s32 	%r16, %r15, %r13;
	mov.b32 	%f20, %r16;
	mov.f32 	%f21, 0fBF800000;
	mov.f32 	%f22, 0f3E800000;
	fma.rn.f32 	%f23, %f22, %f20, %f21;
	add.f32 	%f24, %f23, %f19;
	cvt.rn.f32.s32 	%f25, %r13;
	mul.f32 	%f26, %f25, 0f34000000;
	mov.f32 	%f27, 0f3DD80012;
	mov.f32 	%f28, 0fBD39BF78;
	fma.rn.f32 	%f29, %f28, %f24, %f27;
	mov.f32 	%f30, 0fBE0778E0;
	fma.rn.f32 	%f31, %f29, %f24, %f30;
	mov.f32 	%f32, 0f3E146475;
	fma.rn.f32 	%f33, %f31, %f24, %f32;
	mov.f32 	%f34, 0fBE2A68DD;
	fma.rn.f32 	%f35, %f33, %f24, %f34;
	mov.f32 	%f36, 0f3E4CAF9E;
	fma.rn.f32 	%f37, %f35, %f24, %f36;
	mov.f32 	%f38, 0fBE800042;
	fma.rn.f32 	%f39, %f37, %f24, %f38;
	mov.f32 	%f40, 0f3EAAAAE6;
	fma.rn.f32 	%f41, %f39, %f24, %f40;
	mov.f32 	%f42, 0fBF000000;
	fma.rn.f32 	%f43, %f41, %f24, %f42;
	mul.f32 	%f44, %f24, %f43;
	fma.rn.f32 	%f45, %f44, %f24, %f24;
	mov.f32 	%f46, 0f3F317218;
	fma.rn.f32 	%f79, %f26, %f46, %f45;
	setp.lt.u32 	%p4, %r2, 2139095040;
	@%p4 bra 	$L__BB0_10;

	setp.lt.s32 	%p5, %r2, -1082130431;
	@%p5 bra 	$L__BB0_6;

	mov.f32 	%f47, 0f7F800000;
	fma.rn.f32 	%f79, %f3, %f47, %f47;

$L__BB0_6:
	setp.eq.f32 	%p6, %f3, 0f00000000;
	selp.f32 	%f79, 0f80000000, %f79, %p6;

$L__BB0_10:
	st.global.f32 	[%rd1], %f79;

$L__BB0_12:
	ret;

}

`
 )
