package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qasin kernel
var Qasin_code cu.Function

// Stores the arguments for Qasin kernel invocation
type Qasin_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qasin kernel invocation
var Qasin_args Qasin_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qasin_args.argptr[0] = unsafe.Pointer(&Qasin_args.arg_dst)
	 Qasin_args.argptr[1] = unsafe.Pointer(&Qasin_args.arg_src)
	 Qasin_args.argptr[2] = unsafe.Pointer(&Qasin_args.arg_N)
	 }

// Wrapper for Qasin CUDA kernel, asynchronous.
func k_Qasin_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qasin")
	}

	Qasin_args.Lock()
	defer Qasin_args.Unlock()

	if Qasin_code == 0{
		Qasin_code = fatbinLoad(Qasin_map, "Qasin")
	}

	 Qasin_args.arg_dst = dst
	 Qasin_args.arg_src = src
	 Qasin_args.arg_N = N
	

	args := Qasin_args.argptr[:]
	cu.LaunchKernel(Qasin_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qasin")
	}
}

// maps compute capability on PTX code for Qasin kernel.
var Qasin_map = map[int]string{ 0: "" ,
61: Qasin_ptx_61  }

// Qasin PTX code for various compute capabilities.
const(
  Qasin_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qasin

.visible .entry Qasin(
	.param .u64 Qasin_param_0,
	.param .u64 Qasin_param_1,
	.param .u32 Qasin_param_2
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<33>;
	.reg .b32 	%r<14>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd2, [Qasin_param_0];
	ld.param.u64 	%rd3, [Qasin_param_1];
	ld.param.u32 	%r2, [Qasin_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd4, %rd3;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.ge.f32 	%p2, %f1, 0fBF800000;
	setp.le.f32 	%p3, %f1, 0f3F800000;
	and.pred  	%p4, %p2, %p3;
	cvta.to.global.u64 	%rd7, %rd2;
	add.s64 	%rd1, %rd7, %rd5;
	@%p4 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	abs.f32 	%f2, %f1;
	neg.f32 	%f3, %f2;
	mov.f32 	%f4, 0f3F000000;
	fma.rn.f32 	%f5, %f4, %f3, %f4;
	rsqrt.approx.ftz.f32 	%f6, %f5;
	mul.f32 	%f7, %f5, %f6;
	mul.f32 	%f8, %f6, 0f3F000000;
	neg.f32 	%f9, %f7;
	fma.rn.f32 	%f10, %f9, %f8, %f4;
	fma.rn.f32 	%f11, %f7, %f10, %f7;
	setp.eq.f32 	%p5, %f2, 0f3F800000;
	selp.f32 	%f12, 0f00000000, %f11, %p5;
	setp.gt.f32 	%p6, %f2, 0f3F0F5C29;
	selp.f32 	%f13, %f12, %f2, %p6;
	mul.f32 	%f14, %f13, %f13;
	mov.f32 	%f15, 0f3C99CA97;
	mov.f32 	%f16, 0f3D4DD2F7;
	fma.rn.f32 	%f17, %f16, %f14, %f15;
	mov.f32 	%f18, 0f3D3F90E8;
	fma.rn.f32 	%f19, %f17, %f14, %f18;
	mov.f32 	%f20, 0f3D993CCF;
	fma.rn.f32 	%f21, %f19, %f14, %f20;
	mov.f32 	%f22, 0f3E2AAC04;
	fma.rn.f32 	%f23, %f21, %f14, %f22;
	mul.f32 	%f24, %f14, %f23;
	fma.rn.f32 	%f25, %f24, %f13, %f13;
	mul.f32 	%f26, %f25, 0fC0000000;
	mov.f32 	%f27, 0f3FD774EB;
	mov.f32 	%f28, 0f3F6EE581;
	fma.rn.f32 	%f29, %f28, %f27, %f26;
	selp.f32 	%f30, %f29, %f25, %p6;
	setp.le.f32 	%p7, %f30, 0f7F800000;
	mov.b32 	%r10, %f30;
	mov.b32 	%r11, %f1;
	and.b32  	%r12, %r11, -2147483648;
	or.b32  	%r13, %r12, %r10;
	mov.b32 	%f31, %r13;
	selp.f32 	%f32, %f31, %f30, %p7;
	st.global.f32 	[%rd1], %f32;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	mov.u32 	%r9, 0;
	st.global.u32 	[%rd1], %r9;

$L__BB0_4:
	ret;

}

`
 )
