package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qatanh kernel
var Qatanh_code cu.Function

// Stores the arguments for Qatanh kernel invocation
type Qatanh_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qatanh kernel invocation
var Qatanh_args Qatanh_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qatanh_args.argptr[0] = unsafe.Pointer(&Qatanh_args.arg_dst)
	 Qatanh_args.argptr[1] = unsafe.Pointer(&Qatanh_args.arg_src)
	 Qatanh_args.argptr[2] = unsafe.Pointer(&Qatanh_args.arg_N)
	 }

// Wrapper for Qatanh CUDA kernel, asynchronous.
func k_Qatanh_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qatanh")
	}

	Qatanh_args.Lock()
	defer Qatanh_args.Unlock()

	if Qatanh_code == 0{
		Qatanh_code = fatbinLoad(Qatanh_map, "Qatanh")
	}

	 Qatanh_args.arg_dst = dst
	 Qatanh_args.arg_src = src
	 Qatanh_args.arg_N = N
	

	args := Qatanh_args.argptr[:]
	cu.LaunchKernel(Qatanh_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qatanh")
	}
}

// maps compute capability on PTX code for Qatanh kernel.
var Qatanh_map = map[int]string{ 0: "" ,
61: Qatanh_ptx_61  }

// Qatanh PTX code for various compute capabilities.
const(
  Qatanh_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qatanh

.visible .entry Qatanh(
	.param .u64 Qatanh_param_0,
	.param .u64 Qatanh_param_1,
	.param .u32 Qatanh_param_2
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<50>;
	.reg .b32 	%r<28>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd2, [Qatanh_param_0];
	ld.param.u64 	%rd3, [Qatanh_param_1];
	ld.param.u32 	%r3, [Qatanh_param_2];
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ctaid.x;
	mad.lo.s32 	%r7, %r5, %r4, %r6;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	setp.ge.s32 	%p1, %r1, %r3;
	@%p1 bra 	$L__BB0_8;

	cvta.to.global.u64 	%rd4, %rd3;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.gt.f32 	%p2, %f1, 0fBF800000;
	setp.lt.f32 	%p3, %f1, 0f3F800000;
	and.pred  	%p4, %p2, %p3;
	cvta.to.global.u64 	%rd7, %rd2;
	add.s64 	%rd1, %rd7, %rd5;
	@%p4 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	abs.f32 	%f8, %f1;
	mov.f32 	%f9, 0f3F800000;
	sub.f32 	%f10, %f9, %f8;
	rcp.approx.ftz.f32 	%f11, %f10;
	add.f32 	%f12, %f11, %f11;
	mul.f32 	%f13, %f8, %f12;
	setp.gt.f32 	%p5, %f8, 0f7E800000;
	selp.f32 	%f2, 0fC0000000, %f13, %p5;
	add.rz.f32 	%f14, %f2, %f9;
	mov.b32 	%r11, %f14;
	add.s32 	%r12, %r11, -1061158912;
	and.b32  	%r13, %r12, -8388608;
	mov.b32 	%r2, %f2;
	sub.s32 	%r14, %r2, %r13;
	mov.b32 	%f15, %r14;
	mov.u32 	%r15, 1082130432;
	sub.s32 	%r16, %r15, %r13;
	mov.b32 	%f16, %r16;
	mov.f32 	%f17, 0fBF800000;
	mov.f32 	%f18, 0f3E800000;
	fma.rn.f32 	%f19, %f18, %f16, %f17;
	add.f32 	%f20, %f19, %f15;
	cvt.rn.f32.s32 	%f21, %r13;
	mul.f32 	%f22, %f21, 0f34000000;
	mov.f32 	%f23, 0f3DD80012;
	mov.f32 	%f24, 0fBD39BF78;
	fma.rn.f32 	%f25, %f24, %f20, %f23;
	mov.f32 	%f26, 0fBE0778E0;
	fma.rn.f32 	%f27, %f25, %f20, %f26;
	mov.f32 	%f28, 0f3E146475;
	fma.rn.f32 	%f29, %f27, %f20, %f28;
	mov.f32 	%f30, 0fBE2A68DD;
	fma.rn.f32 	%f31, %f29, %f20, %f30;
	mov.f32 	%f32, 0f3E4CAF9E;
	fma.rn.f32 	%f33, %f31, %f20, %f32;
	mov.f32 	%f34, 0fBE800042;
	fma.rn.f32 	%f35, %f33, %f20, %f34;
	mov.f32 	%f36, 0f3EAAAAE6;
	fma.rn.f32 	%f37, %f35, %f20, %f36;
	mov.f32 	%f38, 0fBF000000;
	fma.rn.f32 	%f39, %f37, %f20, %f38;
	mul.f32 	%f40, %f20, %f39;
	fma.rn.f32 	%f41, %f40, %f20, %f20;
	mov.f32 	%f42, 0f3F317218;
	fma.rn.f32 	%f48, %f22, %f42, %f41;
	setp.lt.u32 	%p6, %r2, 2139095040;
	@%p6 bra 	$L__BB0_7;

	setp.lt.s32 	%p7, %r2, -1082130431;
	@%p7 bra 	$L__BB0_6;

	mov.f32 	%f43, 0f7F800000;
	fma.rn.f32 	%f48, %f2, %f43, %f43;

$L__BB0_6:
	setp.eq.f32 	%p8, %f2, 0f00000000;
	selp.f32 	%f48, 0f80000000, %f48, %p8;

$L__BB0_7:
	mul.f32 	%f44, %f48, 0f3F000000;
	abs.f32 	%f45, %f44;
	setp.le.f32 	%p9, %f45, 0f7F800000;
	mov.b32 	%r17, %f44;
	mov.b32 	%r18, %f1;
	and.b32  	%r19, %r18, -2147483648;
	or.b32  	%r20, %r19, %r17;
	mov.b32 	%f46, %r20;
	selp.f32 	%f47, %f46, %f44, %p9;
	st.global.f32 	[%rd1], %f47;
	bra.uni 	$L__BB0_8;

$L__BB0_2:
	mov.u32 	%r10, 0;
	st.global.u32 	[%rd1], %r10;

$L__BB0_8:
	ret;

}

`
 )
