package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qerfc kernel
var Qerfc_code cu.Function

// Stores the arguments for Qerfc kernel invocation
type Qerfc_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qerfc kernel invocation
var Qerfc_args Qerfc_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qerfc_args.argptr[0] = unsafe.Pointer(&Qerfc_args.arg_dst)
	 Qerfc_args.argptr[1] = unsafe.Pointer(&Qerfc_args.arg_src)
	 Qerfc_args.argptr[2] = unsafe.Pointer(&Qerfc_args.arg_N)
	 }

// Wrapper for Qerfc CUDA kernel, asynchronous.
func k_Qerfc_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qerfc")
	}

	Qerfc_args.Lock()
	defer Qerfc_args.Unlock()

	if Qerfc_code == 0{
		Qerfc_code = fatbinLoad(Qerfc_map, "Qerfc")
	}

	 Qerfc_args.arg_dst = dst
	 Qerfc_args.arg_src = src
	 Qerfc_args.arg_N = N
	

	args := Qerfc_args.argptr[:]
	cu.LaunchKernel(Qerfc_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qerfc")
	}
}

// maps compute capability on PTX code for Qerfc kernel.
var Qerfc_map = map[int]string{ 0: "" ,
61: Qerfc_ptx_61  }

// Qerfc PTX code for various compute capabilities.
const(
  Qerfc_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qerfc

.visible .entry Qerfc(
	.param .u64 Qerfc_param_0,
	.param .u64 Qerfc_param_1,
	.param .u32 Qerfc_param_2
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<67>;
	.reg .b32 	%r<14>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [Qerfc_param_0];
	ld.param.u64 	%rd2, [Qerfc_param_1];
	ld.param.u32 	%r2, [Qerfc_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	abs.f32 	%f2, %f1;
	add.f32 	%f3, %f2, 0fC0800000;
	mov.f32 	%f4, 0fC0800000;
	add.f32 	%f5, %f2, 0f40800000;
	rcp.approx.ftz.f32 	%f6, %f5;
	mul.rn.f32 	%f7, %f3, %f6;
	add.f32 	%f8, %f7, 0f3F800000;
	mov.f32 	%f9, 0f3F800000;
	fma.rn.f32 	%f10, %f4, %f8, %f2;
	neg.f32 	%f11, %f7;
	fma.rn.f32 	%f12, %f11, %f2, %f10;
	fma.rn.f32 	%f13, %f6, %f12, %f7;
	mov.f32 	%f14, 0f3BE6E05B;
	mov.f32 	%f15, 0f3A69A091;
	fma.rn.f32 	%f16, %f15, %f13, %f14;
	mov.f32 	%f17, 0fBC81FB4B;
	fma.rn.f32 	%f18, %f16, %f13, %f17;
	mov.f32 	%f19, 0f3D15373B;
	fma.rn.f32 	%f20, %f18, %f13, %f19;
	mov.f32 	%f21, 0fBD887C5A;
	fma.rn.f32 	%f22, %f20, %f13, %f21;
	mov.f32 	%f23, 0f3DC021D5;
	fma.rn.f32 	%f24, %f22, %f13, %f23;
	mov.f32 	%f25, 0fBDCED424;
	fma.rn.f32 	%f26, %f24, %f13, %f25;
	mov.f32 	%f27, 0f3D8B74DE;
	fma.rn.f32 	%f28, %f26, %f13, %f27;
	mov.f32 	%f29, 0f3C7BF170;
	fma.rn.f32 	%f30, %f28, %f13, %f29;
	mov.f32 	%f31, 0fBE0EF8D4;
	fma.rn.f32 	%f32, %f30, %f13, %f31;
	mov.f32 	%f33, 0f3F9DD2C9;
	fma.rn.f32 	%f34, %f32, %f13, %f33;
	mov.f32 	%f35, 0f40000000;
	fma.rn.f32 	%f36, %f35, %f2, %f9;
	rcp.approx.ftz.f32 	%f37, %f36;
	mul.rn.f32 	%f38, %f34, %f37;
	mul.f32 	%f39, %f38, 0fC0000000;
	fma.rn.f32 	%f40, %f2, %f39, %f34;
	sub.f32 	%f41, %f40, %f38;
	fma.rn.f32 	%f42, %f41, %f37, %f38;
	mul.f32 	%f43, %f2, %f2;
	neg.f32 	%f44, %f43;
	mov.f32 	%f45, 0f3FB8AA3B;
	mul.rn.f32 	%f46, %f44, %f45;
	cvt.rzi.f32.f32 	%f47, %f46;
	abs.f32 	%f48, %f47;
	setp.gt.f32 	%p2, %f48, 0f42FC0000;
	mov.b32 	%r9, %f47;
	and.b32  	%r10, %r9, -2147483648;
	or.b32  	%r11, %r10, 1123811328;
	mov.b32 	%f49, %r11;
	selp.f32 	%f50, %f49, %f47, %p2;
	mov.f32 	%f51, 0fBF317218;
	fma.rn.f32 	%f52, %f50, %f51, %f44;
	mov.f32 	%f53, 0f3102E308;
	fma.rn.f32 	%f54, %f50, %f53, %f52;
	mul.f32 	%f55, %f54, 0f3FB8AA3B;
	add.f32 	%f56, %f50, 0f4B40007F;
	mov.b32 	%r12, %f56;
	shl.b32 	%r13, %r12, 23;
	mov.b32 	%f57, %r13;
	ex2.approx.ftz.f32 	%f58, %f55;
	mul.f32 	%f59, %f58, %f57;
	neg.f32 	%f60, %f2;
	fma.rn.f32 	%f61, %f60, %f2, %f43;
	fma.rn.f32 	%f62, %f59, %f61, %f59;
	mul.f32 	%f63, %f42, %f62;
	setp.gt.f32 	%p3, %f2, 0f4120E148;
	selp.f32 	%f64, 0f00000000, %f63, %p3;
	setp.lt.f32 	%p4, %f1, 0f00000000;
	sub.f32 	%f65, %f35, %f64;
	selp.f32 	%f66, %f65, %f64, %p4;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f66;

$L__BB0_2:
	ret;

}

`
 )
