package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qerf kernel
var Qerf_code cu.Function

// Stores the arguments for Qerf kernel invocation
type Qerf_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qerf kernel invocation
var Qerf_args Qerf_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qerf_args.argptr[0] = unsafe.Pointer(&Qerf_args.arg_dst)
	 Qerf_args.argptr[1] = unsafe.Pointer(&Qerf_args.arg_src)
	 Qerf_args.argptr[2] = unsafe.Pointer(&Qerf_args.arg_N)
	 }

// Wrapper for Qerf CUDA kernel, asynchronous.
func k_Qerf_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qerf")
	}

	Qerf_args.Lock()
	defer Qerf_args.Unlock()

	if Qerf_code == 0{
		Qerf_code = fatbinLoad(Qerf_map, "Qerf")
	}

	 Qerf_args.arg_dst = dst
	 Qerf_args.arg_src = src
	 Qerf_args.arg_N = N
	

	args := Qerf_args.argptr[:]
	cu.LaunchKernel(Qerf_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qerf")
	}
}

// maps compute capability on PTX code for Qerf kernel.
var Qerf_map = map[int]string{ 0: "" ,
61: Qerf_ptx_61  }

// Qerf PTX code for various compute capabilities.
const(
  Qerf_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qerf

.visible .entry Qerf(
	.param .u64 Qerf_param_0,
	.param .u64 Qerf_param_1,
	.param .u32 Qerf_param_2
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<27>;
	.reg .b32 	%r<13>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [Qerf_param_0];
	ld.param.u64 	%rd3, [Qerf_param_1];
	ld.param.u32 	%r2, [Qerf_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	abs.f32 	%f5, %f1;
	setp.ltu.f32 	%p2, %f5, 0f3F8060FE;
	setp.ge.f32 	%p3, %f5, 0f3F8060FE;
	mul.f32 	%f6, %f1, %f1;
	selp.f32 	%f7, %f5, %f6, %p3;
	selp.f32 	%f8, 0f38EB4C3A, 0f38B1E96A, %p3;
	selp.f32 	%f9, 0fBAAE005B, 0fBA574D20, %p3;
	fma.rn.f32 	%f10, %f8, %f7, %f9;
	selp.f32 	%f11, 0f3C09919F, 0f3BAAD5EA, %p3;
	fma.rn.f32 	%f12, %f10, %f7, %f11;
	selp.f32 	%f13, 0fBD24D99A, 0fBCDC1BE7, %p3;
	fma.rn.f32 	%f14, %f12, %f7, %f13;
	selp.f32 	%f15, 0f3E235519, 0f3DE718AF, %p3;
	fma.rn.f32 	%f16, %f14, %f7, %f15;
	selp.f32 	%f17, 0f3F69B4F9, 0fBEC093AC, %p3;
	fma.rn.f32 	%f18, %f16, %f7, %f17;
	selp.f32 	%f19, 0f3F210A14, 0f3E0375D3, %p3;
	fma.rn.f32 	%f20, %f18, %f7, %f19;
	neg.f32 	%f21, %f5;
	selp.f32 	%f22, %f21, %f1, %p3;
	fma.rn.f32 	%f26, %f20, %f22, %f22;
	@%p2 bra 	$L__BB0_3;

	ex2.approx.ftz.f32 	%f23, %f26;
	mov.f32 	%f24, 0f3F800000;
	sub.f32 	%f25, %f24, %f23;
	mov.b32 	%r9, %f25;
	mov.b32 	%r10, %f1;
	and.b32  	%r11, %r10, -2147483648;
	or.b32  	%r12, %r11, %r9;
	mov.b32 	%f26, %r12;

$L__BB0_3:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f26;

$L__BB0_4:
	ret;

}

`
 )
