package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qexp kernel
var Qexp_code cu.Function

// Stores the arguments for Qexp kernel invocation
type Qexp_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qexp kernel invocation
var Qexp_args Qexp_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qexp_args.argptr[0] = unsafe.Pointer(&Qexp_args.arg_dst)
	 Qexp_args.argptr[1] = unsafe.Pointer(&Qexp_args.arg_src)
	 Qexp_args.argptr[2] = unsafe.Pointer(&Qexp_args.arg_N)
	 }

// Wrapper for Qexp CUDA kernel, asynchronous.
func k_Qexp_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qexp")
	}

	Qexp_args.Lock()
	defer Qexp_args.Unlock()

	if Qexp_code == 0{
		Qexp_code = fatbinLoad(Qexp_map, "Qexp")
	}

	 Qexp_args.arg_dst = dst
	 Qexp_args.arg_src = src
	 Qexp_args.arg_N = N
	

	args := Qexp_args.argptr[:]
	cu.LaunchKernel(Qexp_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qexp")
	}
}

// maps compute capability on PTX code for Qexp kernel.
var Qexp_map = map[int]string{ 0: "" ,
61: Qexp_ptx_61  }

// Qexp PTX code for various compute capabilities.
const(
  Qexp_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qexp

.visible .entry Qexp(
	.param .u64 Qexp_param_0,
	.param .u64 Qexp_param_1,
	.param .u32 Qexp_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<18>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [Qexp_param_0];
	ld.param.u64 	%rd2, [Qexp_param_1];
	ld.param.u32 	%r2, [Qexp_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	mov.f32 	%f2, 0f3F000000;
	mov.f32 	%f3, 0f3BBB989D;
	fma.rn.f32 	%f4, %f1, %f3, %f2;
	cvt.sat.f32.f32 	%f5, %f4;
	mov.f32 	%f6, 0f4B400001;
	mov.f32 	%f7, 0f437C0000;
	fma.rm.f32 	%f8, %f5, %f7, %f6;
	add.f32 	%f9, %f8, 0fCB40007F;
	neg.f32 	%f10, %f9;
	mov.f32 	%f11, 0f3FB8AA3B;
	fma.rn.f32 	%f12, %f1, %f11, %f10;
	mov.f32 	%f13, 0f32A57060;
	fma.rn.f32 	%f14, %f1, %f13, %f12;
	mov.b32 	%r9, %f8;
	shl.b32 	%r10, %r9, 23;
	mov.b32 	%f15, %r10;
	ex2.approx.ftz.f32 	%f16, %f14;
	mul.f32 	%f17, %f16, %f15;
	cvta.to.global.u64 	%rd6, %rd1;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f17;

$L__BB0_2:
	ret;

}

`
 )
