package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qheaviside kernel
var Qheaviside_code cu.Function

// Stores the arguments for Qheaviside kernel invocation
type Qheaviside_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qheaviside kernel invocation
var Qheaviside_args Qheaviside_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qheaviside_args.argptr[0] = unsafe.Pointer(&Qheaviside_args.arg_dst)
	 Qheaviside_args.argptr[1] = unsafe.Pointer(&Qheaviside_args.arg_src)
	 Qheaviside_args.argptr[2] = unsafe.Pointer(&Qheaviside_args.arg_N)
	 }

// Wrapper for Qheaviside CUDA kernel, asynchronous.
func k_Qheaviside_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qheaviside")
	}

	Qheaviside_args.Lock()
	defer Qheaviside_args.Unlock()

	if Qheaviside_code == 0{
		Qheaviside_code = fatbinLoad(Qheaviside_map, "Qheaviside")
	}

	 Qheaviside_args.arg_dst = dst
	 Qheaviside_args.arg_src = src
	 Qheaviside_args.arg_N = N
	

	args := Qheaviside_args.argptr[:]
	cu.LaunchKernel(Qheaviside_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qheaviside")
	}
}

// maps compute capability on PTX code for Qheaviside kernel.
var Qheaviside_map = map[int]string{ 0: "" ,
61: Qheaviside_ptx_61  }

// Qheaviside PTX code for various compute capabilities.
const(
  Qheaviside_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qheaviside

.visible .entry Qheaviside(
	.param .u64 Qheaviside_param_0,
	.param .u64 Qheaviside_param_1,
	.param .u32 Qheaviside_param_2
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd2, [Qheaviside_param_0];
	ld.param.u64 	%rd3, [Qheaviside_param_1];
	ld.param.u32 	%r2, [Qheaviside_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_6;

	cvta.to.global.u64 	%rd4, %rd3;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.gt.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd7, %rd2;
	add.s64 	%rd1, %rd7, %rd5;
	@%p2 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_2;

$L__BB0_5:
	mov.u32 	%r11, 1065353216;
	st.global.u32 	[%rd1], %r11;
	bra.uni 	$L__BB0_6;

$L__BB0_2:
	setp.lt.f32 	%p3, %f1, 0f00000000;
	@%p3 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_3;

$L__BB0_4:
	mov.u32 	%r10, 0;
	st.global.u32 	[%rd1], %r10;
	bra.uni 	$L__BB0_6;

$L__BB0_3:
	mov.u32 	%r9, 1056964608;
	st.global.u32 	[%rd1], %r9;

$L__BB0_6:
	ret;

}

`
 )
