package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qlog kernel
var Qlog_code cu.Function

// Stores the arguments for Qlog kernel invocation
type Qlog_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qlog kernel invocation
var Qlog_args Qlog_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qlog_args.argptr[0] = unsafe.Pointer(&Qlog_args.arg_dst)
	 Qlog_args.argptr[1] = unsafe.Pointer(&Qlog_args.arg_src)
	 Qlog_args.argptr[2] = unsafe.Pointer(&Qlog_args.arg_N)
	 }

// Wrapper for Qlog CUDA kernel, asynchronous.
func k_Qlog_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qlog")
	}

	Qlog_args.Lock()
	defer Qlog_args.Unlock()

	if Qlog_code == 0{
		Qlog_code = fatbinLoad(Qlog_map, "Qlog")
	}

	 Qlog_args.arg_dst = dst
	 Qlog_args.arg_src = src
	 Qlog_args.arg_N = N
	

	args := Qlog_args.argptr[:]
	cu.LaunchKernel(Qlog_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qlog")
	}
}

// maps compute capability on PTX code for Qlog kernel.
var Qlog_map = map[int]string{ 0: "" ,
61: Qlog_ptx_61  }

// Qlog PTX code for various compute capabilities.
const(
  Qlog_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qlog

.visible .entry Qlog(
	.param .u64 Qlog_param_0,
	.param .u64 Qlog_param_1,
	.param .u32 Qlog_param_2
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<36>;
	.reg .b32 	%r<14>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd2, [Qlog_param_0];
	ld.param.u64 	%rd3, [Qlog_param_1];
	ld.param.u32 	%r2, [Qlog_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_6;

	cvta.to.global.u64 	%rd4, %rd3;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.gt.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd7, %rd2;
	add.s64 	%rd1, %rd7, %rd5;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	setp.lt.f32 	%p3, %f1, 0f00800000;
	mul.f32 	%f6, %f1, 0f4B000000;
	selp.f32 	%f2, %f6, %f1, %p3;
	selp.f32 	%f7, 0fC1B80000, 0f00000000, %p3;
	mov.b32 	%r10, %f2;
	add.s32 	%r11, %r10, -1059760811;
	and.b32  	%r12, %r11, -8388608;
	sub.s32 	%r13, %r10, %r12;
	mov.b32 	%f8, %r13;
	cvt.rn.f32.s32 	%f9, %r12;
	mov.f32 	%f10, 0f34000000;
	fma.rn.f32 	%f11, %f9, %f10, %f7;
	add.f32 	%f12, %f8, 0fBF800000;
	mov.f32 	%f13, 0f3E1039F6;
	mov.f32 	%f14, 0fBE055027;
	fma.rn.f32 	%f15, %f14, %f12, %f13;
	mov.f32 	%f16, 0fBDF8CDCC;
	fma.rn.f32 	%f17, %f15, %f12, %f16;
	mov.f32 	%f18, 0f3E0F2955;
	fma.rn.f32 	%f19, %f17, %f12, %f18;
	mov.f32 	%f20, 0fBE2AD8B9;
	fma.rn.f32 	%f21, %f19, %f12, %f20;
	mov.f32 	%f22, 0f3E4CED0B;
	fma.rn.f32 	%f23, %f21, %f12, %f22;
	mov.f32 	%f24, 0fBE7FFF22;
	fma.rn.f32 	%f25, %f23, %f12, %f24;
	mov.f32 	%f26, 0f3EAAAA78;
	fma.rn.f32 	%f27, %f25, %f12, %f26;
	mov.f32 	%f28, 0fBF000000;
	fma.rn.f32 	%f29, %f27, %f12, %f28;
	mul.f32 	%f30, %f12, %f29;
	fma.rn.f32 	%f31, %f30, %f12, %f12;
	mov.f32 	%f32, 0f3F317218;
	fma.rn.f32 	%f35, %f11, %f32, %f31;
	setp.lt.u32 	%p4, %r10, 2139095040;
	@%p4 bra 	$L__BB0_5;

	mov.f32 	%f33, 0f7F800000;
	fma.rn.f32 	%f35, %f2, %f33, %f33;

$L__BB0_5:
	setp.eq.f32 	%p5, %f2, 0f00000000;
	selp.f32 	%f34, 0fFF800000, %f35, %p5;
	st.global.f32 	[%rd1], %f34;
	bra.uni 	$L__BB0_6;

$L__BB0_2:
	mov.u32 	%r9, 0;
	st.global.u32 	[%rd1], %r9;

$L__BB0_6:
	ret;

}

`
 )
