package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qmod kernel
var Qmod_code cu.Function

// Stores the arguments for Qmod kernel invocation
type Qmod_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src1 unsafe.Pointer
	 arg_src2 unsafe.Pointer
	 arg_N int
	 argptr [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qmod kernel invocation
var Qmod_args Qmod_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qmod_args.argptr[0] = unsafe.Pointer(&Qmod_args.arg_dst)
	 Qmod_args.argptr[1] = unsafe.Pointer(&Qmod_args.arg_src1)
	 Qmod_args.argptr[2] = unsafe.Pointer(&Qmod_args.arg_src2)
	 Qmod_args.argptr[3] = unsafe.Pointer(&Qmod_args.arg_N)
	 }

// Wrapper for Qmod CUDA kernel, asynchronous.
func k_Qmod_async ( dst unsafe.Pointer, src1 unsafe.Pointer, src2 unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qmod")
	}

	Qmod_args.Lock()
	defer Qmod_args.Unlock()

	if Qmod_code == 0{
		Qmod_code = fatbinLoad(Qmod_map, "Qmod")
	}

	 Qmod_args.arg_dst = dst
	 Qmod_args.arg_src1 = src1
	 Qmod_args.arg_src2 = src2
	 Qmod_args.arg_N = N
	

	args := Qmod_args.argptr[:]
	cu.LaunchKernel(Qmod_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qmod")
	}
}

// maps compute capability on PTX code for Qmod kernel.
var Qmod_map = map[int]string{ 0: "" ,
61: Qmod_ptx_61  }

// Qmod PTX code for various compute capabilities.
const(
  Qmod_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qmod

.visible .entry Qmod(
	.param .u64 Qmod_param_0,
	.param .u64 Qmod_param_1,
	.param .u64 Qmod_param_2,
	.param .u32 Qmod_param_3
)
{
	.reg .pred 	%p<18>;
	.reg .f32 	%f<47>;
	.reg .b32 	%r<37>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd3, [Qmod_param_0];
	ld.param.u64 	%rd4, [Qmod_param_1];
	ld.param.u64 	%rd5, [Qmod_param_2];
	ld.param.u32 	%r11, [Qmod_param_3];
	mov.u32 	%r12, %nctaid.x;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %ctaid.x;
	mad.lo.s32 	%r15, %r13, %r12, %r14;
	mov.u32 	%r16, %ntid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r1, %r15, %r16, %r17;
	setp.ge.s32 	%p1, %r1, %r11;
	@%p1 bra 	$L__BB0_16;

	cvta.to.global.u64 	%rd6, %rd5;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd2, %rd9, %rd7;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	cvta.to.global.u64 	%rd10, %rd4;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.nc.f32 	%f2, [%rd12];
	abs.f32 	%f46, %f2;
	abs.f32 	%f4, %f1;
	setp.lt.f32 	%p3, %f46, %f4;
	@%p3 bra 	$L__BB0_15;

	mul.f32 	%f5, %f4, 0f4B000000;
	setp.gtu.f32 	%p4, %f46, %f5;
	@%p4 bra 	$L__BB0_11;
	bra.uni 	$L__BB0_5;

$L__BB0_11:
	mov.b32 	%r3, %f46;
	and.b32  	%r20, %r3, 8388607;
	or.b32  	%r35, %r20, 1065353216;
	mov.b32 	%r4, %f5;
	mov.b32 	%f45, %r35;
	add.s32 	%r22, %r4, -192937984;
	and.b32  	%r23, %r22, -8388608;
	sub.s32 	%r24, %r3, %r23;
	and.b32  	%r36, %r24, -8388608;
	setp.eq.s32 	%p10, %r36, 0;
	@%p10 bra 	$L__BB0_14;

	and.b32  	%r25, %r4, 8388607;
	or.b32  	%r26, %r25, 1065353216;
	mov.b32 	%f29, %r26;
	rcp.approx.ftz.f32 	%f15, %f29;
	neg.f32 	%f16, %f29;

$L__BB0_13:
	min.u32 	%r28, %r36, 192937984;
	add.s32 	%r29, %r28, %r35;
	mov.b32 	%f30, %r29;
	mov.f32 	%f31, 0f80000000;
	fma.rn.f32 	%f32, %f30, %f15, %f31;
	fma.rn.f32 	%f33, %f16, %f32, %f30;
	fma.rn.f32 	%f34, %f33, %f15, %f32;
	fma.rn.f32 	%f35, %f16, %f34, %f30;
	fma.rz.f32 	%f36, %f35, %f15, %f34;
	cvt.rzi.f32.f32 	%f37, %f36;
	fma.rn.f32 	%f45, %f16, %f37, %f30;
	sub.s32 	%r36, %r36, %r28;
	mov.b32 	%r35, %f45;
	setp.ne.s32 	%p11, %r36, 0;
	setp.ne.s32 	%p12, %r35, 0;
	and.pred  	%p13, %p11, %p12;
	@%p13 bra 	$L__BB0_13;

$L__BB0_14:
	and.b32  	%r30, %r4, -8388608;
	mov.b32 	%f38, %r30;
	setp.gt.u32 	%p14, %r3, 2139095039;
	setp.leu.f32 	%p15, %f4, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	selp.f32 	%f39, 0f7FFFFFFF, %f38, %p16;
	mul.f32 	%f40, %f45, 0f34000000;
	mul.f32 	%f46, %f39, %f40;
	bra.uni 	$L__BB0_15;

$L__BB0_2:
	mov.u32 	%r18, 0;
	st.global.u32 	[%rd2], %r18;
	bra.uni 	$L__BB0_16;

$L__BB0_5:
	div.approx.f32 	%f21, %f46, %f4;
	cvt.rzi.f32.f32 	%f44, %f21;
	neg.f32 	%f7, %f4;
	fma.rn.f32 	%f8, %f7, %f44, %f46;
	mov.b32 	%r2, %f8;
	mov.b32 	%r19, %f4;
	setp.lt.u32 	%p5, %r2, %r19;
	@%p5 bra 	$L__BB0_10;

	setp.gt.u32 	%p6, %r2, -2147483648;
	@%p6 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_7;

$L__BB0_9:
	add.f32 	%f27, %f44, 0fBF800000;
	add.f32 	%f28, %f27, 0fBF800000;
	setp.lt.f32 	%p9, %f8, %f7;
	selp.f32 	%f44, %f28, %f27, %p9;
	bra.uni 	$L__BB0_10;

$L__BB0_7:
	add.f32 	%f44, %f44, 0f3F800000;
	add.f32 	%f22, %f4, %f4;
	setp.ltu.f32 	%p7, %f8, %f22;
	@%p7 bra 	$L__BB0_10;

	add.f32 	%f23, %f44, 0f3F800000;
	mov.f32 	%f24, 0fC0400000;
	fma.rn.f32 	%f25, %f24, %f4, %f8;
	setp.ge.f32 	%p8, %f25, 0f00000000;
	add.f32 	%f26, %f23, 0f3F800000;
	selp.f32 	%f44, %f26, %f23, %p8;

$L__BB0_10:
	fma.rn.f32 	%f46, %f7, %f44, %f46;

$L__BB0_15:
	abs.f32 	%f41, %f46;
	setp.gtu.f32 	%p17, %f41, 0f7F800000;
	mov.b32 	%r31, %f2;
	and.b32  	%r32, %r31, -2147483648;
	mov.b32 	%r33, %f46;
	or.b32  	%r34, %r32, %r33;
	mov.b32 	%f42, %r34;
	selp.f32 	%f43, %f46, %f42, %p17;
	st.global.f32 	[%rd2], %f43;

$L__BB0_16:
	ret;

}

`
 )
