package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qpow kernel
var Qpow_code cu.Function

// Stores the arguments for Qpow kernel invocation
type Qpow_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src1 unsafe.Pointer
	 arg_src2 unsafe.Pointer
	 arg_N int
	 argptr [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qpow kernel invocation
var Qpow_args Qpow_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qpow_args.argptr[0] = unsafe.Pointer(&Qpow_args.arg_dst)
	 Qpow_args.argptr[1] = unsafe.Pointer(&Qpow_args.arg_src1)
	 Qpow_args.argptr[2] = unsafe.Pointer(&Qpow_args.arg_src2)
	 Qpow_args.argptr[3] = unsafe.Pointer(&Qpow_args.arg_N)
	 }

// Wrapper for Qpow CUDA kernel, asynchronous.
func k_Qpow_async ( dst unsafe.Pointer, src1 unsafe.Pointer, src2 unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qpow")
	}

	Qpow_args.Lock()
	defer Qpow_args.Unlock()

	if Qpow_code == 0{
		Qpow_code = fatbinLoad(Qpow_map, "Qpow")
	}

	 Qpow_args.arg_dst = dst
	 Qpow_args.arg_src1 = src1
	 Qpow_args.arg_src2 = src2
	 Qpow_args.arg_N = N
	

	args := Qpow_args.argptr[:]
	cu.LaunchKernel(Qpow_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qpow")
	}
}

// maps compute capability on PTX code for Qpow kernel.
var Qpow_map = map[int]string{ 0: "" ,
61: Qpow_ptx_61  }

// Qpow PTX code for various compute capabilities.
const(
  Qpow_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qpow

.visible .entry Qpow(
	.param .u64 Qpow_param_0,
	.param .u64 Qpow_param_1,
	.param .u64 Qpow_param_2,
	.param .u32 Qpow_param_3
)
{
	.reg .pred 	%p<49>;
	.reg .f32 	%f<177>;
	.reg .b32 	%r<38>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd2, [Qpow_param_0];
	ld.param.u64 	%rd3, [Qpow_param_1];
	ld.param.u64 	%rd4, [Qpow_param_2];
	ld.param.u32 	%r2, [Qpow_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_23;

	cvta.to.global.u64 	%rd5, %rd3;
	mul.wide.s32 	%rd6, %r1, 4;
	add.s64 	%rd7, %rd5, %rd6;
	cvta.to.global.u64 	%rd8, %rd4;
	add.s64 	%rd9, %rd8, %rd6;
	ld.global.nc.f32 	%f1, [%rd7];
	setp.eq.f32 	%p2, %f1, 0f00000000;
	ld.global.nc.f32 	%f2, [%rd9];
	setp.lt.f32 	%p3, %f2, 0f00000000;
	and.pred  	%p4, %p2, %p3;
	cvta.to.global.u64 	%rd10, %rd2;
	add.s64 	%rd1, %rd10, %rd6;
	@%p4 bra 	$L__BB0_22;
	bra.uni 	$L__BB0_2;

$L__BB0_22:
	mov.u32 	%r37, 0;
	st.global.u32 	[%rd1], %r37;
	bra.uni 	$L__BB0_23;

$L__BB0_2:
	cvt.rmi.f32.f32 	%f3, %f2;
	sub.f32 	%f22, %f2, %f3;
	abs.f32 	%f23, %f22;
	setp.geu.f32 	%p5, %f23, 0f358637BD;
	setp.lt.f32 	%p6, %f1, 0f00000000;
	and.pred  	%p7, %p6, %p5;
	mov.f32 	%f176, 0f3F800000;
	@%p7 bra 	$L__BB0_12;
	bra.uni 	$L__BB0_3;

$L__BB0_12:
	abs.f32 	%f13, %f1;
	mul.f32 	%f99, %f2, 0f3F000000;
	cvt.rzi.f32.f32 	%f100, %f99;
	add.f32 	%f101, %f100, %f100;
	sub.f32 	%f102, %f2, %f101;
	abs.f32 	%f14, %f102;
	abs.f32 	%f15, %f13;
	setp.lt.f32 	%p29, %f15, 0f00800000;
	mul.f32 	%f103, %f15, 0f4B800000;
	selp.f32 	%f104, %f103, %f15, %p29;
	selp.f32 	%f105, 0fC1C00000, 0f00000000, %p29;
	mov.b32 	%r23, %f104;
	add.s32 	%r24, %r23, -1060439283;
	and.b32  	%r25, %r24, -8388608;
	sub.s32 	%r26, %r23, %r25;
	mov.b32 	%f106, %r26;
	cvt.rn.f32.s32 	%f107, %r25;
	mov.f32 	%f108, 0f34000000;
	fma.rn.f32 	%f109, %f107, %f108, %f105;
	add.f32 	%f110, %f106, 0fBF800000;
	add.f32 	%f111, %f106, 0f3F800000;
	mov.f32 	%f98, 0f3F800000;
	rcp.approx.ftz.f32 	%f112, %f111;
	add.f32 	%f113, %f110, %f110;
	mul.f32 	%f114, %f113, %f112;
	mul.f32 	%f115, %f114, %f114;
	sub.f32 	%f116, %f110, %f114;
	add.f32 	%f117, %f116, %f116;
	neg.f32 	%f118, %f114;
	fma.rn.f32 	%f119, %f118, %f110, %f117;
	mul.rn.f32 	%f120, %f112, %f119;
	mov.f32 	%f121, 0f3B52E7DB;
	mov.f32 	%f122, 0f3A2C32E4;
	fma.rn.f32 	%f123, %f122, %f115, %f121;
	mov.f32 	%f124, 0f3C93BB73;
	fma.rn.f32 	%f125, %f123, %f115, %f124;
	mov.f32 	%f126, 0f3DF6384F;
	fma.rn.f32 	%f127, %f125, %f115, %f126;
	mul.rn.f32 	%f128, %f127, %f115;
	mov.f32 	%f129, 0f3FB8AA3B;
	fma.rn.f32 	%f130, %f114, %f129, %f109;
	sub.f32 	%f131, %f109, %f130;
	fma.rn.f32 	%f132, %f114, %f129, %f131;
	fma.rn.f32 	%f133, %f120, %f129, %f132;
	mov.f32 	%f134, 0f32A55E34;
	fma.rn.f32 	%f135, %f114, %f134, %f133;
	mul.f32 	%f136, %f128, 0f40400000;
	fma.rn.f32 	%f137, %f136, %f120, %f135;
	fma.rn.f32 	%f138, %f128, %f114, %f137;
	add.rn.f32 	%f139, %f130, %f138;
	neg.f32 	%f140, %f130;
	add.rn.f32 	%f141, %f139, %f140;
	neg.f32 	%f142, %f141;
	add.rn.f32 	%f143, %f138, %f142;
	mul.rn.f32 	%f144, %f139, %f2;
	neg.f32 	%f145, %f144;
	fma.rn.f32 	%f146, %f139, %f2, %f145;
	fma.rn.f32 	%f147, %f143, %f2, %f146;
	cvt.rni.f32.f32 	%f148, %f144;
	sub.f32 	%f149, %f144, %f148;
	add.f32 	%f150, %f147, %f149;
	mov.f32 	%f151, 0f3AAF85ED;
	mov.f32 	%f152, 0f391FCB8E;
	fma.rn.f32 	%f153, %f152, %f150, %f151;
	mov.f32 	%f154, 0f3C1D9856;
	fma.rn.f32 	%f155, %f153, %f150, %f154;
	mov.f32 	%f156, 0f3D6357BB;
	fma.rn.f32 	%f157, %f155, %f150, %f156;
	mov.f32 	%f158, 0f3E75FDEC;
	fma.rn.f32 	%f159, %f157, %f150, %f158;
	mov.f32 	%f160, 0f3F317218;
	fma.rn.f32 	%f161, %f159, %f150, %f160;
	fma.rn.f32 	%f162, %f161, %f150, %f98;
	cvt.rzi.s32.f32 	%r27, %f148;
	setp.gt.f32 	%p30, %f148, 0f00000000;
	selp.b32 	%r28, 0, -2097152000, %p30;
	add.s32 	%r29, %r28, 2130706432;
	mov.b32 	%f163, %r29;
	mul.f32 	%f164, %f162, %f163;
	shl.b32 	%r30, %r27, 23;
	sub.s32 	%r31, %r30, %r28;
	mov.b32 	%f165, %r31;
	mul.f32 	%f166, %f164, %f165;
	abs.f32 	%f167, %f144;
	setp.gt.f32 	%p31, %f167, 0f43180000;
	setp.lt.f32 	%p32, %f144, 0f00000000;
	selp.f32 	%f168, 0f00000000, 0f7F800000, %p32;
	selp.f32 	%f16, %f168, %f166, %p31;
	setp.eq.f32 	%p33, %f13, 0f3F800000;
	setp.eq.f32 	%p34, %f2, 0f00000000;
	or.pred  	%p35, %p34, %p33;
	@%p35 bra 	$L__BB0_21;

	setp.gtu.f32 	%p36, %f15, 0f7F800000;
	@%p36 bra 	$L__BB0_20;

	abs.f32 	%f17, %f2;
	setp.gtu.f32 	%p37, %f17, 0f7F800000;
	@%p37 bra 	$L__BB0_20;
	bra.uni 	$L__BB0_15;

$L__BB0_20:
	add.rn.f32 	%f176, %f13, %f2;

$L__BB0_21:
	neg.f32 	%f173, %f176;
	st.global.f32 	[%rd1], %f173;
	bra.uni 	$L__BB0_23;

$L__BB0_3:
	mul.f32 	%f25, %f2, 0f3F000000;
	cvt.rzi.f32.f32 	%f26, %f25;
	add.f32 	%f27, %f26, %f26;
	sub.f32 	%f28, %f2, %f27;
	abs.f32 	%f4, %f28;
	abs.f32 	%f5, %f1;
	setp.lt.f32 	%p8, %f5, 0f00800000;
	mul.f32 	%f29, %f5, 0f4B800000;
	selp.f32 	%f30, %f29, %f5, %p8;
	selp.f32 	%f31, 0fC1C00000, 0f00000000, %p8;
	mov.b32 	%r9, %f30;
	add.s32 	%r10, %r9, -1060439283;
	and.b32  	%r11, %r10, -8388608;
	sub.s32 	%r12, %r9, %r11;
	mov.b32 	%f32, %r12;
	cvt.rn.f32.s32 	%f33, %r11;
	mov.f32 	%f34, 0f34000000;
	fma.rn.f32 	%f35, %f33, %f34, %f31;
	add.f32 	%f36, %f32, 0fBF800000;
	add.f32 	%f37, %f32, 0f3F800000;
	mov.f32 	%f175, 0f3F800000;
	rcp.approx.ftz.f32 	%f38, %f37;
	add.f32 	%f39, %f36, %f36;
	mul.f32 	%f40, %f39, %f38;
	mul.f32 	%f41, %f40, %f40;
	sub.f32 	%f42, %f36, %f40;
	add.f32 	%f43, %f42, %f42;
	neg.f32 	%f44, %f40;
	fma.rn.f32 	%f45, %f44, %f36, %f43;
	mul.rn.f32 	%f46, %f38, %f45;
	mov.f32 	%f47, 0f3B52E7DB;
	mov.f32 	%f48, 0f3A2C32E4;
	fma.rn.f32 	%f49, %f48, %f41, %f47;
	mov.f32 	%f50, 0f3C93BB73;
	fma.rn.f32 	%f51, %f49, %f41, %f50;
	mov.f32 	%f52, 0f3DF6384F;
	fma.rn.f32 	%f53, %f51, %f41, %f52;
	mul.rn.f32 	%f54, %f53, %f41;
	mov.f32 	%f55, 0f3FB8AA3B;
	fma.rn.f32 	%f56, %f40, %f55, %f35;
	sub.f32 	%f57, %f35, %f56;
	fma.rn.f32 	%f58, %f40, %f55, %f57;
	fma.rn.f32 	%f59, %f46, %f55, %f58;
	mov.f32 	%f60, 0f32A55E34;
	fma.rn.f32 	%f61, %f40, %f60, %f59;
	mul.f32 	%f62, %f54, 0f40400000;
	fma.rn.f32 	%f63, %f62, %f46, %f61;
	fma.rn.f32 	%f64, %f54, %f40, %f63;
	add.rn.f32 	%f65, %f56, %f64;
	neg.f32 	%f66, %f56;
	add.rn.f32 	%f67, %f65, %f66;
	neg.f32 	%f68, %f67;
	add.rn.f32 	%f69, %f64, %f68;
	mul.rn.f32 	%f70, %f65, %f2;
	neg.f32 	%f71, %f70;
	fma.rn.f32 	%f72, %f65, %f2, %f71;
	fma.rn.f32 	%f73, %f69, %f2, %f72;
	cvt.rni.f32.f32 	%f74, %f70;
	sub.f32 	%f75, %f70, %f74;
	add.f32 	%f76, %f73, %f75;
	mov.f32 	%f77, 0f3AAF85ED;
	mov.f32 	%f78, 0f391FCB8E;
	fma.rn.f32 	%f79, %f78, %f76, %f77;
	mov.f32 	%f80, 0f3C1D9856;
	fma.rn.f32 	%f81, %f79, %f76, %f80;
	mov.f32 	%f82, 0f3D6357BB;
	fma.rn.f32 	%f83, %f81, %f76, %f82;
	mov.f32 	%f84, 0f3E75FDEC;
	fma.rn.f32 	%f85, %f83, %f76, %f84;
	mov.f32 	%f86, 0f3F317218;
	fma.rn.f32 	%f87, %f85, %f76, %f86;
	fma.rn.f32 	%f88, %f87, %f76, %f175;
	cvt.rzi.s32.f32 	%r13, %f74;
	setp.gt.f32 	%p9, %f74, 0f00000000;
	selp.b32 	%r14, 0, -2097152000, %p9;
	add.s32 	%r15, %r14, 2130706432;
	mov.b32 	%f89, %r15;
	mul.f32 	%f90, %f88, %f89;
	shl.b32 	%r16, %r13, 23;
	sub.s32 	%r17, %r16, %r14;
	mov.b32 	%f91, %r17;
	mul.f32 	%f92, %f90, %f91;
	abs.f32 	%f93, %f70;
	setp.gt.f32 	%p10, %f93, 0f43180000;
	setp.lt.f32 	%p11, %f70, 0f00000000;
	selp.f32 	%f94, 0f00000000, 0f7F800000, %p11;
	selp.f32 	%f6, %f94, %f92, %p10;
	setp.eq.f32 	%p12, %f2, 0f00000000;
	setp.eq.f32 	%p13, %f1, 0f3F800000;
	or.pred  	%p14, %p13, %p12;
	@%p14 bra 	$L__BB0_11;

	setp.gtu.f32 	%p15, %f5, 0f7F800000;
	@%p15 bra 	$L__BB0_10;

	abs.f32 	%f7, %f2;
	setp.gtu.f32 	%p16, %f7, 0f7F800000;
	@%p16 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_6;

$L__BB0_10:
	add.rn.f32 	%f175, %f1, %f2;

$L__BB0_11:
	st.global.f32 	[%rd1], %f175;

$L__BB0_23:
	ret;

$L__BB0_15:
	setp.eq.f32 	%p38, %f13, 0f00000000;
	setp.eq.f32 	%p39, %f15, 0f7F800000;
	or.pred  	%p40, %p38, %p39;
	@%p40 bra 	$L__BB0_19;
	bra.uni 	$L__BB0_16;

$L__BB0_19:
	setp.eq.f32 	%p47, %f14, 0f3F800000;
	add.f32 	%f172, %f13, %f13;
	mov.b32 	%r32, %f172;
	xor.b32  	%r33, %r32, 2139095040;
	selp.b32 	%r34, %r33, %r32, %p3;
	and.b32  	%r35, %r34, 2147483647;
	selp.b32 	%r36, %r34, %r35, %p47;
	mov.b32 	%f176, %r36;
	bra.uni 	$L__BB0_21;

$L__BB0_6:
	setp.eq.f32 	%p18, %f5, 0f7F800000;
	or.pred  	%p19, %p2, %p18;
	@%p19 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_7;

$L__BB0_9:
	setp.eq.f32 	%p27, %f4, 0f3F800000;
	add.f32 	%f97, %f1, %f1;
	mov.b32 	%r18, %f97;
	xor.b32  	%r19, %r18, 2139095040;
	selp.b32 	%r20, %r19, %r18, %p3;
	and.b32  	%r21, %r20, 2147483647;
	selp.b32 	%r22, %r20, %r21, %p27;
	mov.b32 	%f175, %r22;
	bra.uni 	$L__BB0_11;

$L__BB0_16:
	setp.eq.f32 	%p41, %f13, 0fBF800000;
	setp.eq.f32 	%p42, %f17, 0f7F800000;
	and.pred  	%p43, %p41, %p42;
	@%p43 bra 	$L__BB0_21;

	setp.geu.f32 	%p44, %f13, 0f00000000;
	mov.f32 	%f176, %f16;
	@%p44 bra 	$L__BB0_21;

	setp.eq.f32 	%p45, %f14, 0f3F800000;
	neg.f32 	%f170, %f16;
	selp.f32 	%f171, %f170, %f16, %p45;
	setp.neu.f32 	%p46, %f3, %f2;
	selp.f32 	%f176, 0f7FFFFFFF, %f171, %p46;
	bra.uni 	$L__BB0_21;

$L__BB0_7:
	setp.eq.f32 	%p20, %f7, 0f7F800000;
	setp.eq.f32 	%p21, %f1, 0fBF800000;
	and.pred  	%p22, %p21, %p20;
	setp.geu.f32 	%p23, %f1, 0f00000000;
	or.pred  	%p24, %p22, %p23;
	selp.f32 	%f175, 0f3F800000, %f6, %p22;
	@%p24 bra 	$L__BB0_11;

	setp.eq.f32 	%p25, %f4, 0f3F800000;
	neg.f32 	%f95, %f6;
	selp.f32 	%f96, %f95, %f6, %p25;
	setp.neu.f32 	%p26, %f3, %f2;
	selp.f32 	%f175, 0f7FFFFFFF, %f96, %p26;
	bra.uni 	$L__BB0_11;

}

`
 )
