package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qsinh kernel
var Qsinh_code cu.Function

// Stores the arguments for Qsinh kernel invocation
type Qsinh_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qsinh kernel invocation
var Qsinh_args Qsinh_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qsinh_args.argptr[0] = unsafe.Pointer(&Qsinh_args.arg_dst)
	 Qsinh_args.argptr[1] = unsafe.Pointer(&Qsinh_args.arg_src)
	 Qsinh_args.argptr[2] = unsafe.Pointer(&Qsinh_args.arg_N)
	 }

// Wrapper for Qsinh CUDA kernel, asynchronous.
func k_Qsinh_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qsinh")
	}

	Qsinh_args.Lock()
	defer Qsinh_args.Unlock()

	if Qsinh_code == 0{
		Qsinh_code = fatbinLoad(Qsinh_map, "Qsinh")
	}

	 Qsinh_args.arg_dst = dst
	 Qsinh_args.arg_src = src
	 Qsinh_args.arg_N = N
	

	args := Qsinh_args.argptr[:]
	cu.LaunchKernel(Qsinh_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qsinh")
	}
}

// maps compute capability on PTX code for Qsinh kernel.
var Qsinh_map = map[int]string{ 0: "" ,
61: Qsinh_ptx_61  }

// Qsinh PTX code for various compute capabilities.
const(
  Qsinh_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qsinh

.visible .entry Qsinh(
	.param .u64 Qsinh_param_0,
	.param .u64 Qsinh_param_1,
	.param .u32 Qsinh_param_2
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<37>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [Qsinh_param_0];
	ld.param.u64 	%rd3, [Qsinh_param_1];
	ld.param.u32 	%r2, [Qsinh_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_5;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	abs.f32 	%f2, %f1;
	setp.ltu.f32 	%p2, %f2, 0f3F800000;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	mul.f32 	%f27, %f1, %f1;
	mov.f32 	%f28, 0f394FFF49;
	mov.f32 	%f29, 0f363D0ADA;
	fma.rn.f32 	%f30, %f29, %f27, %f28;
	mov.f32 	%f31, 0f3C08889A;
	fma.rn.f32 	%f32, %f30, %f27, %f31;
	mov.f32 	%f33, 0f3E2AAAAB;
	fma.rn.f32 	%f34, %f32, %f27, %f33;
	mul.f32 	%f35, %f27, %f34;
	fma.rn.f32 	%f36, %f35, %f1, %f1;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	mov.f32 	%f6, 0f3FB8AA3B;
	mul.rn.f32 	%f7, %f2, %f6;
	cvt.rzi.f32.f32 	%f8, %f7;
	abs.f32 	%f9, %f8;
	setp.gt.f32 	%p3, %f9, 0f42FC0000;
	mov.b32 	%r9, %f8;
	and.b32  	%r10, %r9, -2147483648;
	or.b32  	%r11, %r10, 1123811328;
	mov.b32 	%f10, %r11;
	selp.f32 	%f11, %f10, %f8, %p3;
	mov.f32 	%f12, 0fBF317218;
	fma.rn.f32 	%f13, %f11, %f12, %f2;
	mov.f32 	%f14, 0f3102E308;
	fma.rn.f32 	%f15, %f11, %f14, %f13;
	mul.f32 	%f16, %f15, 0f3FB8AA3B;
	add.f32 	%f17, %f11, 0f4B40007D;
	mov.b32 	%r12, %f17;
	shl.b32 	%r13, %r12, 23;
	mov.b32 	%f18, %r13;
	ex2.approx.ftz.f32 	%f19, %f16;
	mul.f32 	%f20, %f19, %f18;
	mov.f32 	%f21, 0f3E000000;
	div.approx.f32 	%f22, %f21, %f20;
	neg.f32 	%f23, %f22;
	mov.f32 	%f24, 0f40000000;
	fma.rn.f32 	%f25, %f24, %f20, %f23;
	setp.ge.f32 	%p4, %f2, 0f42B40000;
	selp.f32 	%f26, 0f7F800000, %f25, %p4;
	mov.b32 	%r14, %f26;
	mov.b32 	%r15, %f1;
	and.b32  	%r16, %r15, -2147483648;
	or.b32  	%r17, %r16, %r14;
	mov.b32 	%f36, %r17;

$L__BB0_4:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f36;

$L__BB0_5:
	ret;

}

`
 )
