package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qsinc kernel
var Qsinc_code cu.Function

// Stores the arguments for Qsinc kernel invocation
type Qsinc_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qsinc kernel invocation
var Qsinc_args Qsinc_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qsinc_args.argptr[0] = unsafe.Pointer(&Qsinc_args.arg_dst)
	 Qsinc_args.argptr[1] = unsafe.Pointer(&Qsinc_args.arg_src)
	 Qsinc_args.argptr[2] = unsafe.Pointer(&Qsinc_args.arg_N)
	 }

// Wrapper for Qsinc CUDA kernel, asynchronous.
func k_Qsinc_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qsinc")
	}

	Qsinc_args.Lock()
	defer Qsinc_args.Unlock()

	if Qsinc_code == 0{
		Qsinc_code = fatbinLoad(Qsinc_map, "Qsinc")
	}

	 Qsinc_args.arg_dst = dst
	 Qsinc_args.arg_src = src
	 Qsinc_args.arg_N = N
	

	args := Qsinc_args.argptr[:]
	cu.LaunchKernel(Qsinc_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qsinc")
	}
}

// maps compute capability on PTX code for Qsinc kernel.
var Qsinc_map = map[int]string{ 0: "" ,
61: Qsinc_ptx_61  }

// Qsinc PTX code for various compute capabilities.
const(
  Qsinc_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qsinc
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry Qsinc(
	.param .u64 Qsinc_param_0,
	.param .u64 Qsinc_param_1,
	.param .u32 Qsinc_param_2
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<13>;
	.reg .f32 	%f<39>;
	.reg .b32 	%r<62>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<29>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd9, [Qsinc_param_0];
	ld.param.u64 	%rd10, [Qsinc_param_1];
	ld.param.u32 	%r20, [Qsinc_param_2];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r21, %nctaid.x;
	mov.u32 	%r22, %ctaid.y;
	mov.u32 	%r23, %ctaid.x;
	mad.lo.s32 	%r24, %r22, %r21, %r23;
	mov.u32 	%r25, %ntid.x;
	mov.u32 	%r26, %tid.x;
	mad.lo.s32 	%r1, %r24, %r25, %r26;
	setp.ge.s32 	%p1, %r1, %r20;
	@%p1 bra 	$L__BB0_16;

	cvta.to.global.u64 	%rd12, %rd10;
	mul.wide.s32 	%rd13, %r1, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.nc.f32 	%f1, [%rd14];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	cvta.to.global.u64 	%rd15, %rd9;
	add.s64 	%rd2, %rd15, %rd13;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	mul.f32 	%f14, %f1, 0f3F22F983;
	cvt.rni.s32.f32 	%r61, %f14;
	cvt.rn.f32.s32 	%f15, %r61;
	mov.f32 	%f16, 0fBFC90FDA;
	fma.rn.f32 	%f17, %f15, %f16, %f1;
	mov.f32 	%f18, 0fB3A22168;
	fma.rn.f32 	%f19, %f15, %f18, %f17;
	mov.f32 	%f20, 0fA7C234C5;
	fma.rn.f32 	%f36, %f15, %f20, %f19;
	abs.f32 	%f3, %f1;
	setp.ltu.f32 	%p3, %f3, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f3, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f23, 0f00000000;
	mul.rn.f32 	%f36, %f1, %f23;
	mov.u32 	%r61, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_2:
	mov.u32 	%r27, 1065353216;
	st.global.u32 	[%rd2], %r27;
	bra.uni 	$L__BB0_16;

$L__BB0_5:
	mov.b32 	%r3, %f1;
	bfe.u32 	%r29, %r3, 23, 8;
	add.s32 	%r4, %r29, -128;
	shl.b32 	%r30, %r3, 8;
	or.b32  	%r5, %r30, -2147483648;
	shr.u32 	%r6, %r4, 5;
	mov.u64 	%rd28, 0;
	mov.u32 	%r58, 0;
	mov.u64 	%rd27, __cudart_i2opi_f;
	mov.u64 	%rd26, %rd1;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r31, [%rd27];
	mad.wide.u32 	%rd18, %r31, %r5, %rd28;
	shr.u64 	%rd28, %rd18, 32;
	st.local.u32 	[%rd26], %rd18;
	add.s64 	%rd27, %rd27, 4;
	add.s64 	%rd26, %rd26, 4;
	add.s32 	%r58, %r58, 1;
	setp.ne.s32 	%p5, %r58, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd28;
	mov.u32 	%r32, 4;
	sub.s32 	%r9, %r32, %r6;
	mov.u32 	%r33, 6;
	sub.s32 	%r34, %r33, %r6;
	mul.wide.s32 	%rd19, %r34, 4;
	add.s64 	%rd20, %rd1, %rd19;
	ld.local.u32 	%r59, [%rd20];
	ld.local.u32 	%r60, [%rd20+-4];
	and.b32  	%r12, %r4, 31;
	setp.eq.s32 	%p6, %r12, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r35, 32;
	sub.s32 	%r36, %r35, %r12;
	shr.u32 	%r37, %r60, %r36;
	shl.b32 	%r38, %r59, %r12;
	add.s32 	%r59, %r37, %r38;
	mul.wide.s32 	%rd21, %r9, 4;
	add.s64 	%rd22, %rd1, %rd21;
	ld.local.u32 	%r39, [%rd22];
	shr.u32 	%r40, %r39, %r36;
	shl.b32 	%r41, %r60, %r12;
	add.s32 	%r60, %r40, %r41;

$L__BB0_9:
	and.b32  	%r42, %r3, -2147483648;
	shr.u32 	%r43, %r60, 30;
	shl.b32 	%r44, %r59, 2;
	or.b32  	%r45, %r43, %r44;
	shr.u32 	%r46, %r45, 31;
	shr.u32 	%r47, %r59, 30;
	add.s32 	%r48, %r46, %r47;
	neg.s32 	%r49, %r48;
	setp.eq.s32 	%p7, %r42, 0;
	selp.b32 	%r61, %r48, %r49, %p7;
	setp.ne.s32 	%p8, %r46, 0;
	xor.b32  	%r50, %r42, -2147483648;
	selp.b32 	%r51, %r50, %r42, %p8;
	selp.b32 	%r52, -1, 0, %p8;
	xor.b32  	%r53, %r45, %r52;
	shl.b32 	%r54, %r60, 2;
	xor.b32  	%r55, %r54, %r52;
	cvt.u64.u32 	%rd23, %r53;
	cvt.u64.u32 	%rd24, %r55;
	bfi.b64 	%rd25, %rd23, %rd24, 32, 32;
	cvt.rn.f64.s64 	%fd1, %rd25;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f21, %fd2;
	setp.eq.s32 	%p9, %r51, 0;
	neg.f32 	%f22, %f21;
	selp.f32 	%f36, %f21, %f22, %p9;

$L__BB0_11:
	and.b32  	%r19, %r61, 1;
	setp.eq.s32 	%p10, %r19, 0;
	selp.f32 	%f7, %f36, 0f3F800000, %p10;
	mul.rn.f32 	%f8, %f36, %f36;
	mov.f32 	%f37, 0fB94D4153;
	@%p10 bra 	$L__BB0_13;

	mov.f32 	%f25, 0fBAB607ED;
	mov.f32 	%f26, 0f37CBAC00;
	fma.rn.f32 	%f37, %f26, %f8, %f25;

$L__BB0_13:
	selp.f32 	%f27, 0f3C0885E4, 0f3D2AAABB, %p10;
	fma.rn.f32 	%f28, %f37, %f8, %f27;
	selp.f32 	%f29, 0fBE2AAAA8, 0fBEFFFFFF, %p10;
	fma.rn.f32 	%f30, %f28, %f8, %f29;
	mov.f32 	%f31, 0f00000000;
	fma.rn.f32 	%f32, %f8, %f7, %f31;
	fma.rn.f32 	%f38, %f30, %f32, %f7;
	and.b32  	%r57, %r61, 2;
	setp.eq.s32 	%p12, %r57, 0;
	@%p12 bra 	$L__BB0_15;

	mov.f32 	%f34, 0fBF800000;
	fma.rn.f32 	%f38, %f38, %f34, %f31;

$L__BB0_15:
	div.rn.f32 	%f35, %f38, %f1;
	st.global.f32 	[%rd2], %f35;

$L__BB0_16:
	ret;

}

`
 )
