package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_sqrt kernel
var unary_sqrt_code cu.Function

// Stores the arguments for unary_sqrt kernel invocation
type unary_sqrt_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_sqrt kernel invocation
var unary_sqrt_args unary_sqrt_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_sqrt_args.argptr[0] = unsafe.Pointer(&unary_sqrt_args.arg_dst)
	 unary_sqrt_args.argptr[1] = unsafe.Pointer(&unary_sqrt_args.arg_a)
	 unary_sqrt_args.argptr[2] = unsafe.Pointer(&unary_sqrt_args.arg_N)
	 }

// Wrapper for unary_sqrt CUDA kernel, asynchronous.
func k_unary_sqrt_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_sqrt")
	}

	unary_sqrt_args.Lock()
	defer unary_sqrt_args.Unlock()

	if unary_sqrt_code == 0{
		unary_sqrt_code = fatbinLoad(unary_sqrt_map, "unary_sqrt")
	}

	 unary_sqrt_args.arg_dst = dst
	 unary_sqrt_args.arg_a = a
	 unary_sqrt_args.arg_N = N
	

	args := unary_sqrt_args.argptr[:]
	cu.LaunchKernel(unary_sqrt_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_sqrt")
	}
}

// maps compute capability on PTX code for unary_sqrt kernel.
var unary_sqrt_map = map[int]string{ 0: "" ,
61: unary_sqrt_ptx_61  }

// unary_sqrt PTX code for various compute capabilities.
const(
  unary_sqrt_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_sqrt

.visible .entry unary_sqrt(
	.param .u64 unary_sqrt_param_0,
	.param .u64 unary_sqrt_param_1,
	.param .u32 unary_sqrt_param_2
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [unary_sqrt_param_0];
	ld.param.u64 	%rd3, [unary_sqrt_param_1];
	ld.param.u32 	%r2, [unary_sqrt_param_2];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	setp.ltu.f32 	%p2, %f1, 0f00000000;
	mov.f32 	%f5, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	sqrt.rn.f32 	%f5, %f1;

$L__BB0_3:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f5;

$L__BB0_4:
	ret;

}

`
 )
