package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for Qtan kernel
var Qtan_code cu.Function

// Stores the arguments for Qtan kernel invocation
type Qtan_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_src unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for Qtan kernel invocation
var Qtan_args Qtan_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 Qtan_args.argptr[0] = unsafe.Pointer(&Qtan_args.arg_dst)
	 Qtan_args.argptr[1] = unsafe.Pointer(&Qtan_args.arg_src)
	 Qtan_args.argptr[2] = unsafe.Pointer(&Qtan_args.arg_N)
	 }

// Wrapper for Qtan CUDA kernel, asynchronous.
func k_Qtan_async ( dst unsafe.Pointer, src unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("Qtan")
	}

	Qtan_args.Lock()
	defer Qtan_args.Unlock()

	if Qtan_code == 0{
		Qtan_code = fatbinLoad(Qtan_map, "Qtan")
	}

	 Qtan_args.arg_dst = dst
	 Qtan_args.arg_src = src
	 Qtan_args.arg_N = N
	

	args := Qtan_args.argptr[:]
	cu.LaunchKernel(Qtan_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("Qtan")
	}
}

// maps compute capability on PTX code for Qtan kernel.
var Qtan_map = map[int]string{ 0: "" ,
61: Qtan_ptx_61  }

// Qtan PTX code for various compute capabilities.
const(
  Qtan_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	Qtan
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry Qtan(
	.param .u64 Qtan_param_0,
	.param .u64 Qtan_param_1,
	.param .u32 Qtan_param_2
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<22>;
	.reg .f32 	%f<65>;
	.reg .b32 	%r<113>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<51>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd17, [Qtan_param_0];
	ld.param.u64 	%rd18, [Qtan_param_1];
	ld.param.u32 	%r37, [Qtan_param_2];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r38, %nctaid.x;
	mov.u32 	%r39, %ctaid.y;
	mov.u32 	%r40, %ctaid.x;
	mad.lo.s32 	%r41, %r39, %r38, %r40;
	mov.u32 	%r42, %ntid.x;
	mov.u32 	%r43, %tid.x;
	mad.lo.s32 	%r1, %r41, %r42, %r43;
	setp.ge.s32 	%p1, %r1, %r37;
	@%p1 bra 	$L__BB0_24;

	cvta.to.global.u64 	%rd20, %rd18;
	cvt.s64.s32 	%rd2, %r1;
	mul.wide.s32 	%rd21, %r1, 4;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.nc.f32 	%f1, [%rd22];
	mul.f32 	%f17, %f1, 0f3F22F983;
	cvt.rni.s32.f32 	%r112, %f17;
	cvt.rn.f32.s32 	%f18, %r112;
	mov.f32 	%f19, 0fBFC90FDA;
	fma.rn.f32 	%f20, %f18, %f19, %f1;
	mov.f32 	%f21, 0fB3A22168;
	fma.rn.f32 	%f22, %f18, %f21, %f20;
	mov.f32 	%f23, 0fA7C234C5;
	fma.rn.f32 	%f64, %f18, %f23, %f22;
	abs.f32 	%f3, %f1;
	setp.ltu.f32 	%p2, %f3, 0f47CE4780;
	add.s64 	%rd3, %rd1, 24;
	mov.u32 	%r108, %r112;
	mov.f32 	%f61, %f64;
	@%p2 bra 	$L__BB0_9;

	setp.eq.f32 	%p3, %f3, 0f7F800000;
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_3;

$L__BB0_8:
	mov.f32 	%f26, 0f00000000;
	mul.rn.f32 	%f61, %f1, %f26;
	mov.u32 	%r108, 0;
	bra.uni 	$L__BB0_9;

$L__BB0_3:
	mov.b32 	%r3, %f1;
	bfe.u32 	%r45, %r3, 23, 8;
	add.s32 	%r4, %r45, -128;
	shl.b32 	%r46, %r3, 8;
	or.b32  	%r5, %r46, -2147483648;
	shr.u32 	%r6, %r4, 5;
	mov.u64 	%rd47, 0;
	mov.u32 	%r105, 0;
	mov.u64 	%rd46, __cudart_i2opi_f;
	mov.u64 	%rd45, %rd1;

$L__BB0_4:
	.pragma "nounroll";
	ld.global.nc.u32 	%r47, [%rd46];
	mad.wide.u32 	%rd25, %r47, %r5, %rd47;
	shr.u64 	%rd47, %rd25, 32;
	st.local.u32 	[%rd45], %rd25;
	add.s64 	%rd46, %rd46, 4;
	add.s64 	%rd45, %rd45, 4;
	add.s32 	%r105, %r105, 1;
	setp.ne.s32 	%p4, %r105, 6;
	@%p4 bra 	$L__BB0_4;

	st.local.u32 	[%rd3], %rd47;
	mov.u32 	%r48, 4;
	sub.s32 	%r9, %r48, %r6;
	mov.u32 	%r49, 6;
	sub.s32 	%r50, %r49, %r6;
	mul.wide.s32 	%rd26, %r50, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.local.u32 	%r106, [%rd27];
	ld.local.u32 	%r107, [%rd27+-4];
	and.b32  	%r12, %r4, 31;
	setp.eq.s32 	%p5, %r12, 0;
	@%p5 bra 	$L__BB0_7;

	mov.u32 	%r51, 32;
	sub.s32 	%r52, %r51, %r12;
	shr.u32 	%r53, %r107, %r52;
	shl.b32 	%r54, %r106, %r12;
	add.s32 	%r106, %r53, %r54;
	mul.wide.s32 	%rd28, %r9, 4;
	add.s64 	%rd29, %rd1, %rd28;
	ld.local.u32 	%r55, [%rd29];
	shr.u32 	%r56, %r55, %r52;
	shl.b32 	%r57, %r107, %r12;
	add.s32 	%r107, %r56, %r57;

$L__BB0_7:
	and.b32  	%r58, %r3, -2147483648;
	shr.u32 	%r59, %r107, 30;
	shl.b32 	%r60, %r106, 2;
	or.b32  	%r61, %r59, %r60;
	shr.u32 	%r62, %r61, 31;
	shr.u32 	%r63, %r106, 30;
	add.s32 	%r64, %r62, %r63;
	neg.s32 	%r65, %r64;
	setp.eq.s32 	%p6, %r58, 0;
	selp.b32 	%r108, %r64, %r65, %p6;
	setp.ne.s32 	%p7, %r62, 0;
	xor.b32  	%r66, %r58, -2147483648;
	selp.b32 	%r67, %r66, %r58, %p7;
	selp.b32 	%r68, -1, 0, %p7;
	xor.b32  	%r69, %r61, %r68;
	shl.b32 	%r70, %r107, 2;
	xor.b32  	%r71, %r70, %r68;
	cvt.u64.u32 	%rd30, %r69;
	cvt.u64.u32 	%rd31, %r71;
	bfi.b64 	%rd32, %rd30, %rd31, 32, 32;
	cvt.rn.f64.s64 	%fd1, %rd32;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f24, %fd2;
	setp.eq.s32 	%p8, %r67, 0;
	neg.f32 	%f25, %f24;
	selp.f32 	%f61, %f24, %f25, %p8;

$L__BB0_9:
	add.s32 	%r19, %r108, 1;
	and.b32  	%r20, %r19, 1;
	setp.eq.s32 	%p9, %r20, 0;
	selp.f32 	%f7, %f61, 0f3F800000, %p9;
	mul.rn.f32 	%f8, %f61, %f61;
	mov.f32 	%f62, 0fB94D4153;
	@%p9 bra 	$L__BB0_11;

	mov.f32 	%f28, 0fBAB607ED;
	mov.f32 	%f29, 0f37CBAC00;
	fma.rn.f32 	%f62, %f29, %f8, %f28;

$L__BB0_11:
	selp.f32 	%f30, 0f3C0885E4, 0f3D2AAABB, %p9;
	fma.rn.f32 	%f31, %f62, %f8, %f30;
	selp.f32 	%f32, 0fBE2AAAA8, 0fBEFFFFFF, %p9;
	fma.rn.f32 	%f33, %f31, %f8, %f32;
	mov.f32 	%f34, 0f00000000;
	fma.rn.f32 	%f35, %f8, %f7, %f34;
	fma.rn.f32 	%f63, %f33, %f35, %f7;
	and.b32  	%r73, %r19, 2;
	setp.eq.s32 	%p11, %r73, 0;
	@%p11 bra 	$L__BB0_13;

	mov.f32 	%f37, 0fBF800000;
	fma.rn.f32 	%f63, %f63, %f37, %f34;

$L__BB0_13:
	abs.f32 	%f38, %f63;
	setp.gt.f32 	%p12, %f38, 0f33D6BF95;
	cvta.to.global.u64 	%rd33, %rd17;
	shl.b64 	%rd34, %rd2, 2;
	add.s64 	%rd10, %rd33, %rd34;
	@%p12 bra 	$L__BB0_15;
	bra.uni 	$L__BB0_14;

$L__BB0_15:
	@%p2 bra 	$L__BB0_23;

	setp.eq.f32 	%p14, %f3, 0f7F800000;
	@%p14 bra 	$L__BB0_22;
	bra.uni 	$L__BB0_17;

$L__BB0_22:
	mov.f32 	%f41, 0f00000000;
	mul.rn.f32 	%f64, %f1, %f41;
	mov.u32 	%r112, 0;
	bra.uni 	$L__BB0_23;

$L__BB0_14:
	mov.u32 	%r74, 0;
	st.global.u32 	[%rd10], %r74;
	bra.uni 	$L__BB0_24;

$L__BB0_17:
	mov.b32 	%r21, %f1;
	bfe.u32 	%r76, %r21, 23, 8;
	add.s32 	%r22, %r76, -128;
	shl.b32 	%r77, %r21, 8;
	or.b32  	%r23, %r77, -2147483648;
	shr.u32 	%r24, %r22, 5;
	mov.u64 	%rd50, 0;
	mov.u32 	%r109, 0;
	mov.u64 	%rd49, __cudart_i2opi_f;
	mov.u64 	%rd48, %rd1;

$L__BB0_18:
	.pragma "nounroll";
	ld.global.nc.u32 	%r78, [%rd49];
	mad.wide.u32 	%rd37, %r78, %r23, %rd50;
	shr.u64 	%rd50, %rd37, 32;
	st.local.u32 	[%rd48], %rd37;
	add.s64 	%rd49, %rd49, 4;
	add.s64 	%rd48, %rd48, 4;
	add.s32 	%r109, %r109, 1;
	setp.ne.s32 	%p15, %r109, 6;
	@%p15 bra 	$L__BB0_18;

	st.local.u32 	[%rd3], %rd50;
	mov.u32 	%r79, 4;
	sub.s32 	%r27, %r79, %r24;
	mov.u32 	%r80, 6;
	sub.s32 	%r81, %r80, %r24;
	mul.wide.s32 	%rd38, %r81, 4;
	add.s64 	%rd39, %rd1, %rd38;
	ld.local.u32 	%r110, [%rd39];
	ld.local.u32 	%r111, [%rd39+-4];
	and.b32  	%r30, %r22, 31;
	setp.eq.s32 	%p16, %r30, 0;
	@%p16 bra 	$L__BB0_21;

	mov.u32 	%r82, 32;
	sub.s32 	%r83, %r82, %r30;
	shr.u32 	%r84, %r111, %r83;
	shl.b32 	%r85, %r110, %r30;
	add.s32 	%r110, %r84, %r85;
	mul.wide.s32 	%rd40, %r27, 4;
	add.s64 	%rd41, %rd1, %rd40;
	ld.local.u32 	%r86, [%rd41];
	shr.u32 	%r87, %r86, %r83;
	shl.b32 	%r88, %r111, %r30;
	add.s32 	%r111, %r87, %r88;

$L__BB0_21:
	and.b32  	%r89, %r21, -2147483648;
	shr.u32 	%r90, %r111, 30;
	shl.b32 	%r91, %r110, 2;
	or.b32  	%r92, %r90, %r91;
	shr.u32 	%r93, %r92, 31;
	shr.u32 	%r94, %r110, 30;
	add.s32 	%r95, %r93, %r94;
	neg.s32 	%r96, %r95;
	setp.eq.s32 	%p17, %r89, 0;
	selp.b32 	%r112, %r95, %r96, %p17;
	setp.ne.s32 	%p18, %r93, 0;
	xor.b32  	%r97, %r89, -2147483648;
	selp.b32 	%r98, %r97, %r89, %p18;
	selp.b32 	%r99, -1, 0, %p18;
	xor.b32  	%r100, %r92, %r99;
	shl.b32 	%r101, %r111, 2;
	xor.b32  	%r102, %r101, %r99;
	cvt.u64.u32 	%rd42, %r100;
	cvt.u64.u32 	%rd43, %r102;
	bfi.b64 	%rd44, %rd42, %rd43, 32, 32;
	cvt.rn.f64.s64 	%fd3, %rd44;
	mul.f64 	%fd4, %fd3, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f39, %fd4;
	setp.eq.s32 	%p19, %r98, 0;
	neg.f32 	%f40, %f39;
	selp.f32 	%f64, %f39, %f40, %p19;

$L__BB0_23:
	mul.f32 	%f42, %f64, %f64;
	mov.f32 	%f43, 0f3B560000;
	mov.f32 	%f44, 0f3C190000;
	fma.rn.f32 	%f45, %f44, %f42, %f43;
	mov.f32 	%f46, 0f3CC70000;
	fma.rn.f32 	%f47, %f45, %f42, %f46;
	mov.f32 	%f48, 0f3D5B0000;
	fma.rn.f32 	%f49, %f47, %f42, %f48;
	mov.f32 	%f50, 0f3E089438;
	fma.rn.f32 	%f51, %f49, %f42, %f50;
	mov.f32 	%f52, 0f3EAAAA88;
	fma.rn.f32 	%f53, %f51, %f42, %f52;
	mul.rn.f32 	%f54, %f42, %f64;
	fma.rn.f32 	%f55, %f53, %f54, %f64;
	abs.f32 	%f56, %f64;
	setp.eq.f32 	%p20, %f56, 0f3A00B43C;
	selp.f32 	%f57, %f64, %f55, %p20;
	and.b32  	%r104, %r112, 1;
	setp.eq.b32 	%p21, %r104, 1;
	neg.f32 	%f58, %f57;
	rcp.approx.ftz.f32 	%f59, %f58;
	selp.f32 	%f60, %f59, %f57, %p21;
	st.global.f32 	[%rd10], %f60;

$L__BB0_24:
	ret;

}

`
 )
