package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for riemannsy kernel
var riemannsy_code cu.Function

// Stores the arguments for riemannsy kernel invocation
type riemannsy_args_t struct{
	 arg_sx unsafe.Pointer
	 arg_sy unsafe.Pointer
	 arg_sz unsafe.Pointer
	 arg_yx unsafe.Pointer
	 arg_yy unsafe.Pointer
	 arg_yz unsafe.Pointer
	 arg_m0x unsafe.Pointer
	 arg_m0y unsafe.Pointer
	 arg_m0z unsafe.Pointer
	 arg_m1x unsafe.Pointer
	 arg_m1y unsafe.Pointer
	 arg_m1z unsafe.Pointer
	 arg_t0x unsafe.Pointer
	 arg_t0y unsafe.Pointer
	 arg_t0z unsafe.Pointer
	 arg_t1x unsafe.Pointer
	 arg_t1y unsafe.Pointer
	 arg_t1z unsafe.Pointer
	 arg_N int
	 argptr [19]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for riemannsy kernel invocation
var riemannsy_args riemannsy_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 riemannsy_args.argptr[0] = unsafe.Pointer(&riemannsy_args.arg_sx)
	 riemannsy_args.argptr[1] = unsafe.Pointer(&riemannsy_args.arg_sy)
	 riemannsy_args.argptr[2] = unsafe.Pointer(&riemannsy_args.arg_sz)
	 riemannsy_args.argptr[3] = unsafe.Pointer(&riemannsy_args.arg_yx)
	 riemannsy_args.argptr[4] = unsafe.Pointer(&riemannsy_args.arg_yy)
	 riemannsy_args.argptr[5] = unsafe.Pointer(&riemannsy_args.arg_yz)
	 riemannsy_args.argptr[6] = unsafe.Pointer(&riemannsy_args.arg_m0x)
	 riemannsy_args.argptr[7] = unsafe.Pointer(&riemannsy_args.arg_m0y)
	 riemannsy_args.argptr[8] = unsafe.Pointer(&riemannsy_args.arg_m0z)
	 riemannsy_args.argptr[9] = unsafe.Pointer(&riemannsy_args.arg_m1x)
	 riemannsy_args.argptr[10] = unsafe.Pointer(&riemannsy_args.arg_m1y)
	 riemannsy_args.argptr[11] = unsafe.Pointer(&riemannsy_args.arg_m1z)
	 riemannsy_args.argptr[12] = unsafe.Pointer(&riemannsy_args.arg_t0x)
	 riemannsy_args.argptr[13] = unsafe.Pointer(&riemannsy_args.arg_t0y)
	 riemannsy_args.argptr[14] = unsafe.Pointer(&riemannsy_args.arg_t0z)
	 riemannsy_args.argptr[15] = unsafe.Pointer(&riemannsy_args.arg_t1x)
	 riemannsy_args.argptr[16] = unsafe.Pointer(&riemannsy_args.arg_t1y)
	 riemannsy_args.argptr[17] = unsafe.Pointer(&riemannsy_args.arg_t1z)
	 riemannsy_args.argptr[18] = unsafe.Pointer(&riemannsy_args.arg_N)
	 }

// Wrapper for riemannsy CUDA kernel, asynchronous.
func k_riemannsy_async ( sx unsafe.Pointer, sy unsafe.Pointer, sz unsafe.Pointer, yx unsafe.Pointer, yy unsafe.Pointer, yz unsafe.Pointer, m0x unsafe.Pointer, m0y unsafe.Pointer, m0z unsafe.Pointer, m1x unsafe.Pointer, m1y unsafe.Pointer, m1z unsafe.Pointer, t0x unsafe.Pointer, t0y unsafe.Pointer, t0z unsafe.Pointer, t1x unsafe.Pointer, t1y unsafe.Pointer, t1z unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("riemannsy")
	}

	riemannsy_args.Lock()
	defer riemannsy_args.Unlock()

	if riemannsy_code == 0{
		riemannsy_code = fatbinLoad(riemannsy_map, "riemannsy")
	}

	 riemannsy_args.arg_sx = sx
	 riemannsy_args.arg_sy = sy
	 riemannsy_args.arg_sz = sz
	 riemannsy_args.arg_yx = yx
	 riemannsy_args.arg_yy = yy
	 riemannsy_args.arg_yz = yz
	 riemannsy_args.arg_m0x = m0x
	 riemannsy_args.arg_m0y = m0y
	 riemannsy_args.arg_m0z = m0z
	 riemannsy_args.arg_m1x = m1x
	 riemannsy_args.arg_m1y = m1y
	 riemannsy_args.arg_m1z = m1z
	 riemannsy_args.arg_t0x = t0x
	 riemannsy_args.arg_t0y = t0y
	 riemannsy_args.arg_t0z = t0z
	 riemannsy_args.arg_t1x = t1x
	 riemannsy_args.arg_t1y = t1y
	 riemannsy_args.arg_t1z = t1z
	 riemannsy_args.arg_N = N
	

	args := riemannsy_args.argptr[:]
	cu.LaunchKernel(riemannsy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("riemannsy")
	}
}

// maps compute capability on PTX code for riemannsy kernel.
var riemannsy_map = map[int]string{ 0: "" ,
61: riemannsy_ptx_61  }

// riemannsy PTX code for various compute capabilities.
const(
  riemannsy_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	riemannsy

.visible .entry riemannsy(
	.param .u64 riemannsy_param_0,
	.param .u64 riemannsy_param_1,
	.param .u64 riemannsy_param_2,
	.param .u64 riemannsy_param_3,
	.param .u64 riemannsy_param_4,
	.param .u64 riemannsy_param_5,
	.param .u64 riemannsy_param_6,
	.param .u64 riemannsy_param_7,
	.param .u64 riemannsy_param_8,
	.param .u64 riemannsy_param_9,
	.param .u64 riemannsy_param_10,
	.param .u64 riemannsy_param_11,
	.param .u64 riemannsy_param_12,
	.param .u64 riemannsy_param_13,
	.param .u64 riemannsy_param_14,
	.param .u64 riemannsy_param_15,
	.param .u64 riemannsy_param_16,
	.param .u64 riemannsy_param_17,
	.param .u32 riemannsy_param_18
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<105>;
	.reg .b32 	%r<25>;
	.reg .b64 	%rd<58>;


	ld.param.u64 	%rd2, [riemannsy_param_0];
	ld.param.u64 	%rd3, [riemannsy_param_1];
	ld.param.u64 	%rd4, [riemannsy_param_2];
	ld.param.u64 	%rd5, [riemannsy_param_3];
	ld.param.u64 	%rd6, [riemannsy_param_4];
	ld.param.u64 	%rd7, [riemannsy_param_5];
	ld.param.u64 	%rd8, [riemannsy_param_6];
	ld.param.u64 	%rd9, [riemannsy_param_7];
	ld.param.u64 	%rd10, [riemannsy_param_8];
	ld.param.u64 	%rd11, [riemannsy_param_9];
	ld.param.u64 	%rd12, [riemannsy_param_10];
	ld.param.u64 	%rd13, [riemannsy_param_11];
	ld.param.u64 	%rd14, [riemannsy_param_12];
	ld.param.u64 	%rd15, [riemannsy_param_13];
	ld.param.u64 	%rd16, [riemannsy_param_14];
	ld.param.u64 	%rd17, [riemannsy_param_15];
	ld.param.u64 	%rd18, [riemannsy_param_16];
	ld.param.u64 	%rd19, [riemannsy_param_17];
	ld.param.u32 	%r2, [riemannsy_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_9;

	cvta.to.global.u64 	%rd20, %rd8;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd21, %r1, 4;
	add.s64 	%rd22, %rd20, %rd21;
	cvta.to.global.u64 	%rd23, %rd9;
	add.s64 	%rd24, %rd23, %rd21;
	cvta.to.global.u64 	%rd25, %rd10;
	add.s64 	%rd26, %rd25, %rd21;
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd21;
	cvta.to.global.u64 	%rd29, %rd12;
	add.s64 	%rd30, %rd29, %rd21;
	cvta.to.global.u64 	%rd31, %rd13;
	add.s64 	%rd32, %rd31, %rd21;
	cvta.to.global.u64 	%rd33, %rd14;
	add.s64 	%rd34, %rd33, %rd21;
	ld.global.nc.f32 	%f1, [%rd34];
	cvta.to.global.u64 	%rd35, %rd15;
	add.s64 	%rd36, %rd35, %rd21;
	ld.global.nc.f32 	%f2, [%rd36];
	cvta.to.global.u64 	%rd37, %rd16;
	add.s64 	%rd38, %rd37, %rd21;
	ld.global.nc.f32 	%f3, [%rd38];
	cvta.to.global.u64 	%rd39, %rd17;
	add.s64 	%rd40, %rd39, %rd21;
	ld.global.nc.f32 	%f4, [%rd40];
	cvta.to.global.u64 	%rd41, %rd18;
	add.s64 	%rd42, %rd41, %rd21;
	ld.global.nc.f32 	%f5, [%rd42];
	cvta.to.global.u64 	%rd43, %rd19;
	add.s64 	%rd44, %rd43, %rd21;
	ld.global.nc.f32 	%f6, [%rd44];
	ld.global.nc.f32 	%f28, [%rd28];
	ld.global.nc.f32 	%f7, [%rd22];
	sub.f32 	%f8, %f28, %f7;
	ld.global.nc.f32 	%f29, [%rd30];
	ld.global.nc.f32 	%f9, [%rd24];
	sub.f32 	%f10, %f29, %f9;
	ld.global.nc.f32 	%f30, [%rd32];
	ld.global.nc.f32 	%f11, [%rd26];
	sub.f32 	%f12, %f30, %f11;
	mul.f32 	%f31, %f9, %f10;
	fma.rn.f32 	%f32, %f7, %f8, %f31;
	fma.rn.f32 	%f13, %f11, %f12, %f32;
	add.f32 	%f14, %f13, 0f3F800000;
	mov.f32 	%f104, 0f3F800000;
	mul.f32 	%f33, %f9, %f30;
	mul.f32 	%f34, %f11, %f29;
	sub.f32 	%f15, %f33, %f34;
	mul.f32 	%f35, %f11, %f28;
	mul.f32 	%f36, %f7, %f30;
	sub.f32 	%f16, %f35, %f36;
	mul.f32 	%f37, %f7, %f29;
	mul.f32 	%f38, %f9, %f28;
	sub.f32 	%f17, %f37, %f38;
	mul.f32 	%f39, %f16, %f16;
	fma.rn.f32 	%f40, %f15, %f15, %f39;
	fma.rn.f32 	%f41, %f17, %f17, %f40;
	sqrt.rn.f32 	%f18, %f41;
	setp.leu.f32 	%p2, %f18, 0f2B8CBCCC;
	@%p2 bra 	$L__BB0_8;

	abs.f32 	%f19, %f14;
	setp.eq.f32 	%p3, %f19, 0f00000000;
	abs.f32 	%f20, %f18;
	setp.eq.f32 	%p4, %f20, 0f00000000;
	and.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_6;
	bra.uni 	$L__BB0_3;

$L__BB0_6:
	mov.b32 	%r19, %f14;
	shr.s32 	%r20, %r19, 31;
	and.b32  	%r21, %r20, 1078530011;
	mov.b32 	%r22, %f18;
	and.b32  	%r23, %r22, -2147483648;
	or.b32  	%r24, %r23, %r21;
	mov.b32 	%f103, %r24;
	bra.uni 	$L__BB0_7;

$L__BB0_3:
	setp.eq.f32 	%p6, %f19, 0f7F800000;
	setp.eq.f32 	%p7, %f20, 0f7F800000;
	and.pred  	%p8, %p6, %p7;
	@%p8 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_4;

$L__BB0_5:
	mov.b32 	%r14, %f14;
	setp.lt.s32 	%p12, %r14, 0;
	selp.b32 	%r15, 1075235812, 1061752795, %p12;
	mov.b32 	%r16, %f18;
	and.b32  	%r17, %r16, -2147483648;
	or.b32  	%r18, %r17, %r15;
	mov.b32 	%f103, %r18;
	bra.uni 	$L__BB0_7;

$L__BB0_4:
	max.f32 	%f42, %f20, %f19;
	min.f32 	%f43, %f20, %f19;
	div.rn.f32 	%f44, %f43, %f42;
	mul.rn.f32 	%f45, %f44, %f44;
	mov.f32 	%f46, 0fC0B59883;
	mov.f32 	%f47, 0fBF52C7EA;
	fma.rn.f32 	%f48, %f45, %f47, %f46;
	mov.f32 	%f49, 0fC0D21907;
	fma.rn.f32 	%f50, %f48, %f45, %f49;
	mul.f32 	%f51, %f45, %f50;
	mul.f32 	%f52, %f44, %f51;
	add.f32 	%f53, %f45, 0f41355DC0;
	mov.f32 	%f54, 0f41E6BD60;
	fma.rn.f32 	%f55, %f53, %f45, %f54;
	mov.f32 	%f56, 0f419D92C8;
	fma.rn.f32 	%f57, %f55, %f45, %f56;
	rcp.rn.f32 	%f58, %f57;
	fma.rn.f32 	%f59, %f52, %f58, %f44;
	mov.f32 	%f60, 0f3FC90FDB;
	sub.f32 	%f61, %f60, %f59;
	setp.gt.f32 	%p9, %f20, %f19;
	selp.f32 	%f62, %f61, %f59, %p9;
	mov.b32 	%r9, %f14;
	setp.lt.s32 	%p10, %r9, 0;
	mov.f32 	%f63, 0f40490FDB;
	sub.f32 	%f64, %f63, %f62;
	selp.f32 	%f65, %f64, %f62, %p10;
	mov.b32 	%r10, %f65;
	mov.b32 	%r11, %f18;
	and.b32  	%r12, %r11, -2147483648;
	or.b32  	%r13, %r12, %r10;
	mov.b32 	%f66, %r13;
	add.f32 	%f67, %f19, %f20;
	setp.le.f32 	%p11, %f67, 0f7F800000;
	selp.f32 	%f103, %f66, %f67, %p11;

$L__BB0_7:
	div.rn.f32 	%f104, %f103, %f18;

$L__BB0_8:
	mul.f32 	%f68, %f7, %f13;
	sub.f32 	%f69, %f8, %f68;
	mul.f32 	%f70, %f9, %f13;
	sub.f32 	%f71, %f10, %f70;
	mul.f32 	%f72, %f11, %f13;
	sub.f32 	%f73, %f12, %f72;
	mul.f32 	%f74, %f69, %f104;
	mul.f32 	%f75, %f71, %f104;
	mul.f32 	%f76, %f73, %f104;
	mul.f32 	%f77, %f17, %f5;
	mul.f32 	%f78, %f16, %f6;
	sub.f32 	%f79, %f78, %f77;
	mul.f32 	%f80, %f15, %f6;
	mul.f32 	%f81, %f17, %f4;
	sub.f32 	%f82, %f81, %f80;
	mul.f32 	%f83, %f16, %f4;
	mul.f32 	%f84, %f15, %f5;
	sub.f32 	%f85, %f84, %f83;
	mul.f32 	%f86, %f4, %f14;
	sub.f32 	%f87, %f86, %f79;
	mul.f32 	%f88, %f14, %f5;
	sub.f32 	%f89, %f88, %f82;
	mul.f32 	%f90, %f14, %f6;
	sub.f32 	%f91, %f90, %f85;
	mul.f32 	%f92, %f16, %f5;
	fma.rn.f32 	%f93, %f15, %f4, %f92;
	fma.rn.f32 	%f94, %f17, %f6, %f93;
	add.f32 	%f95, %f13, 0f40000000;
	div.rn.f32 	%f96, %f94, %f95;
	fma.rn.f32 	%f97, %f15, %f96, %f87;
	fma.rn.f32 	%f98, %f16, %f96, %f89;
	fma.rn.f32 	%f99, %f17, %f96, %f91;
	sub.f32 	%f100, %f1, %f97;
	sub.f32 	%f101, %f2, %f98;
	sub.f32 	%f102, %f3, %f99;
	cvta.to.global.u64 	%rd45, %rd2;
	shl.b64 	%rd46, %rd1, 2;
	add.s64 	%rd47, %rd45, %rd46;
	st.global.f32 	[%rd47], %f74;
	cvta.to.global.u64 	%rd48, %rd3;
	add.s64 	%rd49, %rd48, %rd46;
	st.global.f32 	[%rd49], %f75;
	cvta.to.global.u64 	%rd50, %rd4;
	add.s64 	%rd51, %rd50, %rd46;
	st.global.f32 	[%rd51], %f76;
	cvta.to.global.u64 	%rd52, %rd5;
	add.s64 	%rd53, %rd52, %rd46;
	st.global.f32 	[%rd53], %f100;
	cvta.to.global.u64 	%rd54, %rd6;
	add.s64 	%rd55, %rd54, %rd46;
	st.global.f32 	[%rd55], %f101;
	cvta.to.global.u64 	%rd56, %rd7;
	add.s64 	%rd57, %rd56, %rd46;
	st.global.f32 	[%rd57], %f102;

$L__BB0_9:
	ret;

}

`
 )
