package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for riemannian_displacement kernel
var riemannian_displacement_code cu.Function

// Stores the arguments for riemannian_displacement kernel invocation
type riemannian_displacement_args_t struct{
	 arg_outx unsafe.Pointer
	 arg_outy unsafe.Pointer
	 arg_outz unsafe.Pointer
	 arg_m0x unsafe.Pointer
	 arg_m0y unsafe.Pointer
	 arg_m0z unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_N int
	 argptr [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for riemannian_displacement kernel invocation
var riemannian_displacement_args riemannian_displacement_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 riemannian_displacement_args.argptr[0] = unsafe.Pointer(&riemannian_displacement_args.arg_outx)
	 riemannian_displacement_args.argptr[1] = unsafe.Pointer(&riemannian_displacement_args.arg_outy)
	 riemannian_displacement_args.argptr[2] = unsafe.Pointer(&riemannian_displacement_args.arg_outz)
	 riemannian_displacement_args.argptr[3] = unsafe.Pointer(&riemannian_displacement_args.arg_m0x)
	 riemannian_displacement_args.argptr[4] = unsafe.Pointer(&riemannian_displacement_args.arg_m0y)
	 riemannian_displacement_args.argptr[5] = unsafe.Pointer(&riemannian_displacement_args.arg_m0z)
	 riemannian_displacement_args.argptr[6] = unsafe.Pointer(&riemannian_displacement_args.arg_mx)
	 riemannian_displacement_args.argptr[7] = unsafe.Pointer(&riemannian_displacement_args.arg_my)
	 riemannian_displacement_args.argptr[8] = unsafe.Pointer(&riemannian_displacement_args.arg_mz)
	 riemannian_displacement_args.argptr[9] = unsafe.Pointer(&riemannian_displacement_args.arg_N)
	 }

// Wrapper for riemannian_displacement CUDA kernel, asynchronous.
func k_riemannian_displacement_async ( outx unsafe.Pointer, outy unsafe.Pointer, outz unsafe.Pointer, m0x unsafe.Pointer, m0y unsafe.Pointer, m0z unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("riemannian_displacement")
	}

	riemannian_displacement_args.Lock()
	defer riemannian_displacement_args.Unlock()

	if riemannian_displacement_code == 0{
		riemannian_displacement_code = fatbinLoad(riemannian_displacement_map, "riemannian_displacement")
	}

	 riemannian_displacement_args.arg_outx = outx
	 riemannian_displacement_args.arg_outy = outy
	 riemannian_displacement_args.arg_outz = outz
	 riemannian_displacement_args.arg_m0x = m0x
	 riemannian_displacement_args.arg_m0y = m0y
	 riemannian_displacement_args.arg_m0z = m0z
	 riemannian_displacement_args.arg_mx = mx
	 riemannian_displacement_args.arg_my = my
	 riemannian_displacement_args.arg_mz = mz
	 riemannian_displacement_args.arg_N = N
	

	args := riemannian_displacement_args.argptr[:]
	cu.LaunchKernel(riemannian_displacement_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("riemannian_displacement")
	}
}

// maps compute capability on PTX code for riemannian_displacement kernel.
var riemannian_displacement_map = map[int]string{ 0: "" ,
61: riemannian_displacement_ptx_61  }

// riemannian_displacement PTX code for various compute capabilities.
const(
  riemannian_displacement_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	riemannian_displacement
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry riemannian_displacement(
	.param .u64 riemannian_displacement_param_0,
	.param .u64 riemannian_displacement_param_1,
	.param .u64 riemannian_displacement_param_2,
	.param .u64 riemannian_displacement_param_3,
	.param .u64 riemannian_displacement_param_4,
	.param .u64 riemannian_displacement_param_5,
	.param .u64 riemannian_displacement_param_6,
	.param .u64 riemannian_displacement_param_7,
	.param .u64 riemannian_displacement_param_8,
	.param .u32 riemannian_displacement_param_9
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<16>;
	.reg .f32 	%f<97>;
	.reg .b32 	%r<65>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<52>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd9, [riemannian_displacement_param_0];
	ld.param.u64 	%rd10, [riemannian_displacement_param_1];
	ld.param.u64 	%rd11, [riemannian_displacement_param_2];
	ld.param.u64 	%rd12, [riemannian_displacement_param_3];
	ld.param.u64 	%rd13, [riemannian_displacement_param_4];
	ld.param.u64 	%rd14, [riemannian_displacement_param_5];
	ld.param.u64 	%rd15, [riemannian_displacement_param_6];
	ld.param.u64 	%rd16, [riemannian_displacement_param_7];
	ld.param.u64 	%rd17, [riemannian_displacement_param_8];
	ld.param.u32 	%r20, [riemannian_displacement_param_9];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r21, %nctaid.x;
	mov.u32 	%r22, %ctaid.y;
	mov.u32 	%r23, %ctaid.x;
	mad.lo.s32 	%r24, %r22, %r21, %r23;
	mov.u32 	%r25, %ntid.x;
	mov.u32 	%r26, %tid.x;
	mad.lo.s32 	%r1, %r24, %r25, %r26;
	setp.ge.s32 	%p1, %r1, %r20;
	@%p1 bra 	$L__BB0_16;

	cvta.to.global.u64 	%rd19, %rd12;
	cvt.s64.s32 	%rd2, %r1;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	cvta.to.global.u64 	%rd22, %rd13;
	add.s64 	%rd23, %rd22, %rd20;
	cvta.to.global.u64 	%rd24, %rd14;
	add.s64 	%rd25, %rd24, %rd20;
	cvta.to.global.u64 	%rd26, %rd15;
	add.s64 	%rd27, %rd26, %rd20;
	cvta.to.global.u64 	%rd28, %rd16;
	add.s64 	%rd29, %rd28, %rd20;
	cvta.to.global.u64 	%rd30, %rd17;
	add.s64 	%rd31, %rd30, %rd20;
	ld.global.f32 	%f1, [%rd27];
	ld.global.f32 	%f2, [%rd21];
	ld.global.f32 	%f3, [%rd29];
	ld.global.f32 	%f4, [%rd23];
	mul.f32 	%f24, %f4, %f3;
	fma.rn.f32 	%f25, %f2, %f1, %f24;
	ld.global.f32 	%f5, [%rd31];
	ld.global.f32 	%f6, [%rd25];
	fma.rn.f32 	%f26, %f6, %f5, %f25;
	mov.f32 	%f27, 0fBF800000;
	max.f32 	%f28, %f27, %f26;
	mov.f32 	%f96, 0f3F800000;
	min.f32 	%f7, %f96, %f28;
	abs.f32 	%f29, %f7;
	neg.f32 	%f30, %f29;
	mov.f32 	%f31, 0f3F000000;
	fma.rn.f32 	%f32, %f31, %f30, %f31;
	rsqrt.approx.ftz.f32 	%f33, %f32;
	mul.f32 	%f34, %f32, %f33;
	mul.f32 	%f35, %f33, 0f3F000000;
	neg.f32 	%f36, %f34;
	fma.rn.f32 	%f37, %f36, %f35, %f31;
	fma.rn.f32 	%f38, %f34, %f37, %f34;
	setp.eq.f32 	%p2, %f29, 0f3F800000;
	selp.f32 	%f39, 0f00000000, %f38, %p2;
	setp.gt.f32 	%p3, %f29, 0f3F0F5C29;
	selp.f32 	%f40, %f39, %f29, %p3;
	mov.b32 	%r27, %f40;
	mov.b32 	%r28, %f7;
	and.b32  	%r29, %r28, -2147483648;
	or.b32  	%r30, %r29, %r27;
	mov.b32 	%f41, %r30;
	mul.f32 	%f42, %f41, %f41;
	mov.f32 	%f43, 0f3C8B1ABB;
	mov.f32 	%f44, 0f3D10ECEF;
	fma.rn.f32 	%f45, %f44, %f42, %f43;
	mov.f32 	%f46, 0f3CFC028C;
	fma.rn.f32 	%f47, %f45, %f42, %f46;
	mov.f32 	%f48, 0f3D372139;
	fma.rn.f32 	%f49, %f47, %f42, %f48;
	mov.f32 	%f50, 0f3D9993DB;
	fma.rn.f32 	%f51, %f49, %f42, %f50;
	mov.f32 	%f52, 0f3E2AAAC6;
	fma.rn.f32 	%f53, %f51, %f42, %f52;
	mul.f32 	%f54, %f53, %f42;
	fma.rn.f32 	%f55, %f54, %f41, %f41;
	neg.f32 	%f56, %f55;
	selp.f32 	%f57, %f55, %f56, %p3;
	mov.f32 	%f58, 0f3FD774EB;
	mov.f32 	%f59, 0f3F6EE581;
	fma.rn.f32 	%f60, %f59, %f58, %f57;
	setp.gt.f32 	%p4, %f7, 0f3F0F5C29;
	selp.f32 	%f61, %f55, %f60, %p4;
	add.f32 	%f62, %f61, %f61;
	selp.f32 	%f8, %f62, %f61, %p3;
	setp.leu.f32 	%p5, %f8, 0f358637BD;
	@%p5 bra 	$L__BB0_15;

	mul.f32 	%f63, %f8, 0f3F22F983;
	cvt.rni.s32.f32 	%r64, %f63;
	cvt.rn.f32.s32 	%f64, %r64;
	mov.f32 	%f65, 0fBFC90FDA;
	fma.rn.f32 	%f66, %f64, %f65, %f8;
	mov.f32 	%f67, 0fB3A22168;
	fma.rn.f32 	%f68, %f64, %f67, %f66;
	mov.f32 	%f69, 0fA7C234C5;
	fma.rn.f32 	%f93, %f64, %f69, %f68;
	abs.f32 	%f10, %f8;
	setp.ltu.f32 	%p6, %f10, 0f47CE4780;
	@%p6 bra 	$L__BB0_10;

	setp.eq.f32 	%p7, %f10, 0f7F800000;
	@%p7 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_4;

$L__BB0_9:
	mov.f32 	%f72, 0f00000000;
	mul.rn.f32 	%f93, %f8, %f72;
	mov.u32 	%r64, 0;
	bra.uni 	$L__BB0_10;

$L__BB0_4:
	mov.b32 	%r3, %f8;
	bfe.u32 	%r32, %r3, 23, 8;
	add.s32 	%r4, %r32, -128;
	shl.b32 	%r33, %r3, 8;
	or.b32  	%r5, %r33, -2147483648;
	shr.u32 	%r6, %r4, 5;
	mov.u64 	%rd51, 0;
	mov.u32 	%r61, 0;
	mov.u64 	%rd50, __cudart_i2opi_f;
	mov.u64 	%rd49, %rd1;

$L__BB0_5:
	.pragma "nounroll";
	ld.global.nc.u32 	%r34, [%rd50];
	mad.wide.u32 	%rd34, %r34, %r5, %rd51;
	shr.u64 	%rd51, %rd34, 32;
	st.local.u32 	[%rd49], %rd34;
	add.s64 	%rd50, %rd50, 4;
	add.s64 	%rd49, %rd49, 4;
	add.s32 	%r61, %r61, 1;
	setp.ne.s32 	%p8, %r61, 6;
	@%p8 bra 	$L__BB0_5;

	st.local.u32 	[%rd1+24], %rd51;
	mov.u32 	%r35, 4;
	sub.s32 	%r9, %r35, %r6;
	mov.u32 	%r36, 6;
	sub.s32 	%r37, %r36, %r6;
	mul.wide.s32 	%rd35, %r37, 4;
	add.s64 	%rd36, %rd1, %rd35;
	ld.local.u32 	%r62, [%rd36];
	ld.local.u32 	%r63, [%rd36+-4];
	and.b32  	%r12, %r4, 31;
	setp.eq.s32 	%p9, %r12, 0;
	@%p9 bra 	$L__BB0_8;

	mov.u32 	%r38, 32;
	sub.s32 	%r39, %r38, %r12;
	shr.u32 	%r40, %r63, %r39;
	shl.b32 	%r41, %r62, %r12;
	add.s32 	%r62, %r40, %r41;
	mul.wide.s32 	%rd37, %r9, 4;
	add.s64 	%rd38, %rd1, %rd37;
	ld.local.u32 	%r42, [%rd38];
	shr.u32 	%r43, %r42, %r39;
	shl.b32 	%r44, %r63, %r12;
	add.s32 	%r63, %r43, %r44;

$L__BB0_8:
	and.b32  	%r45, %r3, -2147483648;
	shr.u32 	%r46, %r63, 30;
	shl.b32 	%r47, %r62, 2;
	or.b32  	%r48, %r46, %r47;
	shr.u32 	%r49, %r48, 31;
	shr.u32 	%r50, %r62, 30;
	add.s32 	%r51, %r49, %r50;
	neg.s32 	%r52, %r51;
	setp.eq.s32 	%p10, %r45, 0;
	selp.b32 	%r64, %r51, %r52, %p10;
	setp.ne.s32 	%p11, %r49, 0;
	xor.b32  	%r53, %r45, -2147483648;
	selp.b32 	%r54, %r53, %r45, %p11;
	selp.b32 	%r55, -1, 0, %p11;
	xor.b32  	%r56, %r48, %r55;
	shl.b32 	%r57, %r63, 2;
	xor.b32  	%r58, %r57, %r55;
	cvt.u64.u32 	%rd39, %r56;
	cvt.u64.u32 	%rd40, %r58;
	bfi.b64 	%rd41, %rd39, %rd40, 32, 32;
	cvt.rn.f64.s64 	%fd1, %rd41;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f70, %fd2;
	setp.eq.s32 	%p12, %r54, 0;
	neg.f32 	%f71, %f70;
	selp.f32 	%f93, %f70, %f71, %p12;

$L__BB0_10:
	and.b32  	%r19, %r64, 1;
	setp.eq.s32 	%p13, %r19, 0;
	selp.f32 	%f14, %f93, 0f3F800000, %p13;
	mul.rn.f32 	%f15, %f93, %f93;
	mov.f32 	%f94, 0fB94D4153;
	@%p13 bra 	$L__BB0_12;

	mov.f32 	%f74, 0fBAB607ED;
	mov.f32 	%f75, 0f37CBAC00;
	fma.rn.f32 	%f94, %f75, %f15, %f74;

$L__BB0_12:
	selp.f32 	%f76, 0f3C0885E4, 0f3D2AAABB, %p13;
	fma.rn.f32 	%f77, %f94, %f15, %f76;
	selp.f32 	%f78, 0fBE2AAAA8, 0fBEFFFFFF, %p13;
	fma.rn.f32 	%f79, %f77, %f15, %f78;
	mov.f32 	%f80, 0f00000000;
	fma.rn.f32 	%f81, %f15, %f14, %f80;
	fma.rn.f32 	%f95, %f79, %f81, %f14;
	and.b32  	%r60, %r64, 2;
	setp.eq.s32 	%p15, %r60, 0;
	@%p15 bra 	$L__BB0_14;

	mov.f32 	%f83, 0fBF800000;
	fma.rn.f32 	%f95, %f95, %f83, %f80;

$L__BB0_14:
	div.rn.f32 	%f96, %f8, %f95;

$L__BB0_15:
	mul.f32 	%f84, %f1, %f7;
	sub.f32 	%f85, %f84, %f2;
	mul.f32 	%f86, %f85, %f96;
	mul.f32 	%f87, %f3, %f7;
	sub.f32 	%f88, %f87, %f4;
	mul.f32 	%f89, %f88, %f96;
	mul.f32 	%f90, %f5, %f7;
	sub.f32 	%f91, %f90, %f6;
	mul.f32 	%f92, %f91, %f96;
	cvta.to.global.u64 	%rd42, %rd9;
	shl.b64 	%rd43, %rd2, 2;
	add.s64 	%rd44, %rd42, %rd43;
	st.global.f32 	[%rd44], %f86;
	cvta.to.global.u64 	%rd45, %rd10;
	add.s64 	%rd46, %rd45, %rd43;
	st.global.f32 	[%rd46], %f89;
	cvta.to.global.u64 	%rd47, %rd11;
	add.s64 	%rd48, %rd47, %rd43;
	st.global.f32 	[%rd48], %f92;

$L__BB0_16:
	ret;

}

`
 )
