package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_sinc kernel
var unary_sinc_code cu.Function

// Stores the arguments for unary_sinc kernel invocation
type unary_sinc_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_sinc kernel invocation
var unary_sinc_args unary_sinc_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_sinc_args.argptr[0] = unsafe.Pointer(&unary_sinc_args.arg_dst)
	 unary_sinc_args.argptr[1] = unsafe.Pointer(&unary_sinc_args.arg_a)
	 unary_sinc_args.argptr[2] = unsafe.Pointer(&unary_sinc_args.arg_N)
	 }

// Wrapper for unary_sinc CUDA kernel, asynchronous.
func k_unary_sinc_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_sinc")
	}

	unary_sinc_args.Lock()
	defer unary_sinc_args.Unlock()

	if unary_sinc_code == 0{
		unary_sinc_code = fatbinLoad(unary_sinc_map, "unary_sinc")
	}

	 unary_sinc_args.arg_dst = dst
	 unary_sinc_args.arg_a = a
	 unary_sinc_args.arg_N = N
	

	args := unary_sinc_args.argptr[:]
	cu.LaunchKernel(unary_sinc_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_sinc")
	}
}

// maps compute capability on PTX code for unary_sinc kernel.
var unary_sinc_map = map[int]string{ 0: "" ,
61: unary_sinc_ptx_61  }

// unary_sinc PTX code for various compute capabilities.
const(
  unary_sinc_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_sinc
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry unary_sinc(
	.param .u64 unary_sinc_param_0,
	.param .u64 unary_sinc_param_1,
	.param .u32 unary_sinc_param_2
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<13>;
	.reg .f32 	%f<42>;
	.reg .b32 	%r<61>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<31>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd9, [unary_sinc_param_0];
	ld.param.u64 	%rd10, [unary_sinc_param_1];
	ld.param.u32 	%r20, [unary_sinc_param_2];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r21, %nctaid.x;
	mov.u32 	%r22, %ctaid.y;
	mov.u32 	%r23, %ctaid.x;
	mad.lo.s32 	%r24, %r22, %r21, %r23;
	mov.u32 	%r25, %ntid.x;
	mov.u32 	%r26, %tid.x;
	mad.lo.s32 	%r1, %r24, %r25, %r26;
	setp.ge.s32 	%p1, %r1, %r20;
	@%p1 bra 	$L__BB0_16;

	cvta.to.global.u64 	%rd12, %rd10;
	cvt.s64.s32 	%rd2, %r1;
	mul.wide.s32 	%rd13, %r1, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.nc.f32 	%f1, [%rd14];
	setp.eq.f32 	%p2, %f1, 0f00000000;
	mov.f32 	%f41, 0f3F800000;
	@%p2 bra 	$L__BB0_15;

	mul.f32 	%f17, %f1, 0f3F22F983;
	cvt.rni.s32.f32 	%r60, %f17;
	cvt.rn.f32.s32 	%f18, %r60;
	mov.f32 	%f19, 0fBFC90FDA;
	fma.rn.f32 	%f20, %f18, %f19, %f1;
	mov.f32 	%f21, 0fB3A22168;
	fma.rn.f32 	%f22, %f18, %f21, %f20;
	mov.f32 	%f23, 0fA7C234C5;
	fma.rn.f32 	%f38, %f18, %f23, %f22;
	abs.f32 	%f3, %f1;
	setp.ltu.f32 	%p3, %f3, 0f47CE4780;
	@%p3 bra 	$L__BB0_10;

	setp.eq.f32 	%p4, %f3, 0f7F800000;
	@%p4 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_4;

$L__BB0_9:
	mov.f32 	%f26, 0f00000000;
	mul.rn.f32 	%f38, %f1, %f26;
	mov.u32 	%r60, 0;
	bra.uni 	$L__BB0_10;

$L__BB0_4:
	mov.b32 	%r3, %f1;
	bfe.u32 	%r28, %r3, 23, 8;
	add.s32 	%r4, %r28, -128;
	shl.b32 	%r29, %r3, 8;
	or.b32  	%r5, %r29, -2147483648;
	shr.u32 	%r6, %r4, 5;
	mov.u64 	%rd30, 0;
	mov.u32 	%r57, 0;
	mov.u64 	%rd29, __cudart_i2opi_f;
	mov.u64 	%rd28, %rd1;

$L__BB0_5:
	.pragma "nounroll";
	ld.global.nc.u32 	%r30, [%rd29];
	mad.wide.u32 	%rd17, %r30, %r5, %rd30;
	shr.u64 	%rd30, %rd17, 32;
	st.local.u32 	[%rd28], %rd17;
	add.s64 	%rd29, %rd29, 4;
	add.s64 	%rd28, %rd28, 4;
	add.s32 	%r57, %r57, 1;
	setp.ne.s32 	%p5, %r57, 6;
	@%p5 bra 	$L__BB0_5;

	st.local.u32 	[%rd1+24], %rd30;
	mov.u32 	%r31, 4;
	sub.s32 	%r9, %r31, %r6;
	mov.u32 	%r32, 6;
	sub.s32 	%r33, %r32, %r6;
	mul.wide.s32 	%rd18, %r33, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.local.u32 	%r58, [%rd19];
	ld.local.u32 	%r59, [%rd19+-4];
	and.b32  	%r12, %r4, 31;
	setp.eq.s32 	%p6, %r12, 0;
	@%p6 bra 	$L__BB0_8;

	mov.u32 	%r34, 32;
	sub.s32 	%r35, %r34, %r12;
	shr.u32 	%r36, %r59, %r35;
	shl.b32 	%r37, %r58, %r12;
	add.s32 	%r58, %r36, %r37;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r38, [%rd21];
	shr.u32 	%r39, %r38, %r35;
	shl.b32 	%r40, %r59, %r12;
	add.s32 	%r59, %r39, %r40;

$L__BB0_8:
	and.b32  	%r41, %r3, -2147483648;
	shr.u32 	%r42, %r59, 30;
	shl.b32 	%r43, %r58, 2;
	or.b32  	%r44, %r42, %r43;
	shr.u32 	%r45, %r44, 31;
	shr.u32 	%r46, %r58, 30;
	add.s32 	%r47, %r45, %r46;
	neg.s32 	%r48, %r47;
	setp.eq.s32 	%p7, %r41, 0;
	selp.b32 	%r60, %r47, %r48, %p7;
	setp.ne.s32 	%p8, %r45, 0;
	xor.b32  	%r49, %r41, -2147483648;
	selp.b32 	%r50, %r49, %r41, %p8;
	selp.b32 	%r51, -1, 0, %p8;
	xor.b32  	%r52, %r44, %r51;
	shl.b32 	%r53, %r59, 2;
	xor.b32  	%r54, %r53, %r51;
	cvt.u64.u32 	%rd22, %r52;
	cvt.u64.u32 	%rd23, %r54;
	bfi.b64 	%rd24, %rd22, %rd23, 32, 32;
	cvt.rn.f64.s64 	%fd1, %rd24;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f24, %fd2;
	setp.eq.s32 	%p9, %r50, 0;
	neg.f32 	%f25, %f24;
	selp.f32 	%f38, %f24, %f25, %p9;

$L__BB0_10:
	and.b32  	%r19, %r60, 1;
	setp.eq.s32 	%p10, %r19, 0;
	selp.f32 	%f7, %f38, 0f3F800000, %p10;
	mul.rn.f32 	%f8, %f38, %f38;
	mov.f32 	%f39, 0fB94D4153;
	@%p10 bra 	$L__BB0_12;

	mov.f32 	%f28, 0fBAB607ED;
	mov.f32 	%f29, 0f37CBAC00;
	fma.rn.f32 	%f39, %f29, %f8, %f28;

$L__BB0_12:
	selp.f32 	%f30, 0f3C0885E4, 0f3D2AAABB, %p10;
	fma.rn.f32 	%f31, %f39, %f8, %f30;
	selp.f32 	%f32, 0fBE2AAAA8, 0fBEFFFFFF, %p10;
	fma.rn.f32 	%f33, %f31, %f8, %f32;
	mov.f32 	%f34, 0f00000000;
	fma.rn.f32 	%f35, %f8, %f7, %f34;
	fma.rn.f32 	%f40, %f33, %f35, %f7;
	and.b32  	%r56, %r60, 2;
	setp.eq.s32 	%p12, %r56, 0;
	@%p12 bra 	$L__BB0_14;

	mov.f32 	%f37, 0fBF800000;
	fma.rn.f32 	%f40, %f40, %f37, %f34;

$L__BB0_14:
	div.rn.f32 	%f41, %f40, %f1;

$L__BB0_15:
	cvta.to.global.u64 	%rd25, %rd9;
	shl.b64 	%rd26, %rd2, 2;
	add.s64 	%rd27, %rd25, %rd26;
	st.global.f32 	[%rd27], %f41;

$L__BB0_16:
	ret;

}

`
 )
