package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_tan kernel
var unary_tan_code cu.Function

// Stores the arguments for unary_tan kernel invocation
type unary_tan_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_tan kernel invocation
var unary_tan_args unary_tan_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_tan_args.argptr[0] = unsafe.Pointer(&unary_tan_args.arg_dst)
	 unary_tan_args.argptr[1] = unsafe.Pointer(&unary_tan_args.arg_a)
	 unary_tan_args.argptr[2] = unsafe.Pointer(&unary_tan_args.arg_N)
	 }

// Wrapper for unary_tan CUDA kernel, asynchronous.
func k_unary_tan_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_tan")
	}

	unary_tan_args.Lock()
	defer unary_tan_args.Unlock()

	if unary_tan_code == 0{
		unary_tan_code = fatbinLoad(unary_tan_map, "unary_tan")
	}

	 unary_tan_args.arg_dst = dst
	 unary_tan_args.arg_a = a
	 unary_tan_args.arg_N = N
	

	args := unary_tan_args.argptr[:]
	cu.LaunchKernel(unary_tan_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_tan")
	}
}

// maps compute capability on PTX code for unary_tan kernel.
var unary_tan_map = map[int]string{ 0: "" ,
61: unary_tan_ptx_61  }

// unary_tan PTX code for various compute capabilities.
const(
  unary_tan_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_tan
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry unary_tan(
	.param .u64 unary_tan_param_0,
	.param .u64 unary_tan_param_1,
	.param .u32 unary_tan_param_2
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<11>;
	.reg .f32 	%f<37>;
	.reg .b32 	%r<60>;
	.reg .f64 	%fd<3>;
	.reg .b64 	%rd<31>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd9, [unary_tan_param_0];
	ld.param.u64 	%rd10, [unary_tan_param_1];
	ld.param.u32 	%r19, [unary_tan_param_2];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.y;
	mov.u32 	%r22, %ctaid.x;
	mad.lo.s32 	%r23, %r21, %r20, %r22;
	mov.u32 	%r24, %ntid.x;
	mov.u32 	%r25, %tid.x;
	mad.lo.s32 	%r1, %r23, %r24, %r25;
	setp.ge.s32 	%p1, %r1, %r19;
	@%p1 bra 	$L__BB0_10;

	cvta.to.global.u64 	%rd12, %rd10;
	cvt.s64.s32 	%rd2, %r1;
	mul.wide.s32 	%rd13, %r1, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.nc.f32 	%f1, [%rd14];
	mul.f32 	%f7, %f1, 0f3F22F983;
	cvt.rni.s32.f32 	%r59, %f7;
	cvt.rn.f32.s32 	%f8, %r59;
	mov.f32 	%f9, 0fBFC90FDA;
	fma.rn.f32 	%f10, %f8, %f9, %f1;
	mov.f32 	%f11, 0fB3A22168;
	fma.rn.f32 	%f12, %f8, %f11, %f10;
	mov.f32 	%f13, 0fA7C234C5;
	fma.rn.f32 	%f36, %f8, %f13, %f12;
	abs.f32 	%f3, %f1;
	setp.ltu.f32 	%p2, %f3, 0f47CE4780;
	@%p2 bra 	$L__BB0_9;

	setp.eq.f32 	%p3, %f3, 0f7F800000;
	@%p3 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_3;

$L__BB0_8:
	mov.f32 	%f16, 0f00000000;
	mul.rn.f32 	%f36, %f1, %f16;
	mov.u32 	%r59, 0;
	bra.uni 	$L__BB0_9;

$L__BB0_3:
	mov.b32 	%r3, %f1;
	bfe.u32 	%r27, %r3, 23, 8;
	add.s32 	%r4, %r27, -128;
	shl.b32 	%r28, %r3, 8;
	or.b32  	%r5, %r28, -2147483648;
	shr.u32 	%r6, %r4, 5;
	mov.u64 	%rd30, 0;
	mov.u32 	%r56, 0;
	mov.u64 	%rd29, __cudart_i2opi_f;
	mov.u64 	%rd28, %rd1;

$L__BB0_4:
	.pragma "nounroll";
	ld.global.nc.u32 	%r29, [%rd29];
	mad.wide.u32 	%rd17, %r29, %r5, %rd30;
	shr.u64 	%rd30, %rd17, 32;
	st.local.u32 	[%rd28], %rd17;
	add.s64 	%rd29, %rd29, 4;
	add.s64 	%rd28, %rd28, 4;
	add.s32 	%r56, %r56, 1;
	setp.ne.s32 	%p4, %r56, 6;
	@%p4 bra 	$L__BB0_4;

	st.local.u32 	[%rd1+24], %rd30;
	mov.u32 	%r30, 4;
	sub.s32 	%r9, %r30, %r6;
	mov.u32 	%r31, 6;
	sub.s32 	%r32, %r31, %r6;
	mul.wide.s32 	%rd18, %r32, 4;
	add.s64 	%rd19, %rd1, %rd18;
	ld.local.u32 	%r57, [%rd19];
	ld.local.u32 	%r58, [%rd19+-4];
	and.b32  	%r12, %r4, 31;
	setp.eq.s32 	%p5, %r12, 0;
	@%p5 bra 	$L__BB0_7;

	mov.u32 	%r33, 32;
	sub.s32 	%r34, %r33, %r12;
	shr.u32 	%r35, %r58, %r34;
	shl.b32 	%r36, %r57, %r12;
	add.s32 	%r57, %r35, %r36;
	mul.wide.s32 	%rd20, %r9, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r37, [%rd21];
	shr.u32 	%r38, %r37, %r34;
	shl.b32 	%r39, %r58, %r12;
	add.s32 	%r58, %r38, %r39;

$L__BB0_7:
	and.b32  	%r40, %r3, -2147483648;
	shr.u32 	%r41, %r58, 30;
	shl.b32 	%r42, %r57, 2;
	or.b32  	%r43, %r41, %r42;
	shr.u32 	%r44, %r43, 31;
	shr.u32 	%r45, %r57, 30;
	add.s32 	%r46, %r44, %r45;
	neg.s32 	%r47, %r46;
	setp.eq.s32 	%p6, %r40, 0;
	selp.b32 	%r59, %r46, %r47, %p6;
	setp.ne.s32 	%p7, %r44, 0;
	xor.b32  	%r48, %r40, -2147483648;
	selp.b32 	%r49, %r48, %r40, %p7;
	selp.b32 	%r50, -1, 0, %p7;
	xor.b32  	%r51, %r43, %r50;
	shl.b32 	%r52, %r58, 2;
	xor.b32  	%r53, %r52, %r50;
	cvt.u64.u32 	%rd22, %r51;
	cvt.u64.u32 	%rd23, %r53;
	bfi.b64 	%rd24, %rd22, %rd23, 32, 32;
	cvt.rn.f64.s64 	%fd1, %rd24;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f14, %fd2;
	setp.eq.s32 	%p8, %r49, 0;
	neg.f32 	%f15, %f14;
	selp.f32 	%f36, %f14, %f15, %p8;

$L__BB0_9:
	mul.f32 	%f17, %f36, %f36;
	mov.f32 	%f18, 0f3B560000;
	mov.f32 	%f19, 0f3C190000;
	fma.rn.f32 	%f20, %f19, %f17, %f18;
	mov.f32 	%f21, 0f3CC70000;
	fma.rn.f32 	%f22, %f20, %f17, %f21;
	mov.f32 	%f23, 0f3D5B0000;
	fma.rn.f32 	%f24, %f22, %f17, %f23;
	mov.f32 	%f25, 0f3E089438;
	fma.rn.f32 	%f26, %f24, %f17, %f25;
	mov.f32 	%f27, 0f3EAAAA88;
	fma.rn.f32 	%f28, %f26, %f17, %f27;
	mul.rn.f32 	%f29, %f17, %f36;
	fma.rn.f32 	%f30, %f28, %f29, %f36;
	abs.f32 	%f31, %f36;
	setp.eq.f32 	%p9, %f31, 0f3A00B43C;
	selp.f32 	%f32, %f36, %f30, %p9;
	and.b32  	%r55, %r59, 1;
	setp.eq.b32 	%p10, %r55, 1;
	neg.f32 	%f33, %f32;
	rcp.approx.ftz.f32 	%f34, %f33;
	selp.f32 	%f35, %f34, %f32, %p10;
	cvta.to.global.u64 	%rd25, %rd9;
	shl.b64 	%rd26, %rd2, 2;
	add.s64 	%rd27, %rd25, %rd26;
	st.global.f32 	[%rd27], %f35;

$L__BB0_10:
	ret;

}

`
 )
