package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for unary_tanh kernel
var unary_tanh_code cu.Function

// Stores the arguments for unary_tanh kernel invocation
type unary_tanh_args_t struct{
	 arg_dst unsafe.Pointer
	 arg_a unsafe.Pointer
	 arg_N int
	 argptr [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for unary_tanh kernel invocation
var unary_tanh_args unary_tanh_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 unary_tanh_args.argptr[0] = unsafe.Pointer(&unary_tanh_args.arg_dst)
	 unary_tanh_args.argptr[1] = unsafe.Pointer(&unary_tanh_args.arg_a)
	 unary_tanh_args.argptr[2] = unsafe.Pointer(&unary_tanh_args.arg_N)
	 }

// Wrapper for unary_tanh CUDA kernel, asynchronous.
func k_unary_tanh_async ( dst unsafe.Pointer, a unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("unary_tanh")
	}

	unary_tanh_args.Lock()
	defer unary_tanh_args.Unlock()

	if unary_tanh_code == 0{
		unary_tanh_code = fatbinLoad(unary_tanh_map, "unary_tanh")
	}

	 unary_tanh_args.arg_dst = dst
	 unary_tanh_args.arg_a = a
	 unary_tanh_args.arg_N = N
	

	args := unary_tanh_args.argptr[:]
	cu.LaunchKernel(unary_tanh_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("unary_tanh")
	}
}

// maps compute capability on PTX code for unary_tanh kernel.
var unary_tanh_map = map[int]string{ 0: "" ,
61: unary_tanh_ptx_61  }

// unary_tanh PTX code for various compute capabilities.
const(
  unary_tanh_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	unary_tanh

.visible .entry unary_tanh(
	.param .u64 unary_tanh_param_0,
	.param .u64 unary_tanh_param_1,
	.param .u32 unary_tanh_param_2
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<25>;
	.reg .b32 	%r<13>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [unary_tanh_param_0];
	ld.param.u64 	%rd3, [unary_tanh_param_1];
	ld.param.u32 	%r2, [unary_tanh_param_2];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_5;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f1, [%rd6];
	abs.f32 	%f2, %f1;
	setp.ltu.f32 	%p2, %f2, 0f3F19999A;
	@%p2 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	mul.f32 	%f14, %f1, %f1;
	mov.f32 	%f15, 0fBD563CAE;
	mov.f32 	%f16, 0f3C80F082;
	fma.rn.f32 	%f17, %f16, %f14, %f15;
	mov.f32 	%f18, 0f3E085941;
	fma.rn.f32 	%f19, %f17, %f14, %f18;
	mov.f32 	%f20, 0fBEAAA9ED;
	fma.rn.f32 	%f21, %f19, %f14, %f20;
	mov.f32 	%f22, 0f00000000;
	fma.rn.f32 	%f23, %f21, %f14, %f22;
	fma.rn.f32 	%f24, %f23, %f1, %f1;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	mul.f32 	%f6, %f2, 0f4038AA3B;
	ex2.approx.ftz.f32 	%f7, %f6;
	add.f32 	%f8, %f7, 0f3F800000;
	mov.f32 	%f9, 0f3F800000;
	rcp.approx.ftz.f32 	%f10, %f8;
	mov.f32 	%f11, 0fC0000000;
	fma.rn.f32 	%f12, %f10, %f11, %f9;
	setp.ge.f32 	%p3, %f2, 0f41102CB4;
	selp.f32 	%f13, 0f3F800000, %f12, %p3;
	mov.b32 	%r9, %f13;
	mov.b32 	%r10, %f1;
	and.b32  	%r11, %r10, -2147483648;
	or.b32  	%r12, %r11, %r9;
	mov.b32 	%f24, %r12;

$L__BB0_4:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f24;

$L__BB0_5:
	ret;

}

`
 )
