package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for transport_tangent kernel
var transport_tangent_code cu.Function

// Stores the arguments for transport_tangent kernel invocation
type transport_tangent_args_t struct{
	 arg_vx unsafe.Pointer
	 arg_vy unsafe.Pointer
	 arg_vz unsafe.Pointer
	 arg_m0x unsafe.Pointer
	 arg_m0y unsafe.Pointer
	 arg_m0z unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_N int
	 argptr [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for transport_tangent kernel invocation
var transport_tangent_args transport_tangent_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 transport_tangent_args.argptr[0] = unsafe.Pointer(&transport_tangent_args.arg_vx)
	 transport_tangent_args.argptr[1] = unsafe.Pointer(&transport_tangent_args.arg_vy)
	 transport_tangent_args.argptr[2] = unsafe.Pointer(&transport_tangent_args.arg_vz)
	 transport_tangent_args.argptr[3] = unsafe.Pointer(&transport_tangent_args.arg_m0x)
	 transport_tangent_args.argptr[4] = unsafe.Pointer(&transport_tangent_args.arg_m0y)
	 transport_tangent_args.argptr[5] = unsafe.Pointer(&transport_tangent_args.arg_m0z)
	 transport_tangent_args.argptr[6] = unsafe.Pointer(&transport_tangent_args.arg_mx)
	 transport_tangent_args.argptr[7] = unsafe.Pointer(&transport_tangent_args.arg_my)
	 transport_tangent_args.argptr[8] = unsafe.Pointer(&transport_tangent_args.arg_mz)
	 transport_tangent_args.argptr[9] = unsafe.Pointer(&transport_tangent_args.arg_N)
	 }

// Wrapper for transport_tangent CUDA kernel, asynchronous.
func k_transport_tangent_async ( vx unsafe.Pointer, vy unsafe.Pointer, vz unsafe.Pointer, m0x unsafe.Pointer, m0y unsafe.Pointer, m0z unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("transport_tangent")
	}

	transport_tangent_args.Lock()
	defer transport_tangent_args.Unlock()

	if transport_tangent_code == 0{
		transport_tangent_code = fatbinLoad(transport_tangent_map, "transport_tangent")
	}

	 transport_tangent_args.arg_vx = vx
	 transport_tangent_args.arg_vy = vy
	 transport_tangent_args.arg_vz = vz
	 transport_tangent_args.arg_m0x = m0x
	 transport_tangent_args.arg_m0y = m0y
	 transport_tangent_args.arg_m0z = m0z
	 transport_tangent_args.arg_mx = mx
	 transport_tangent_args.arg_my = my
	 transport_tangent_args.arg_mz = mz
	 transport_tangent_args.arg_N = N
	

	args := transport_tangent_args.argptr[:]
	cu.LaunchKernel(transport_tangent_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("transport_tangent")
	}
}

// maps compute capability on PTX code for transport_tangent kernel.
var transport_tangent_map = map[int]string{ 0: "" ,
61: transport_tangent_ptx_61  }

// transport_tangent PTX code for various compute capabilities.
const(
  transport_tangent_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	transport_tangent

.visible .entry transport_tangent(
	.param .u64 transport_tangent_param_0,
	.param .u64 transport_tangent_param_1,
	.param .u64 transport_tangent_param_2,
	.param .u64 transport_tangent_param_3,
	.param .u64 transport_tangent_param_4,
	.param .u64 transport_tangent_param_5,
	.param .u64 transport_tangent_param_6,
	.param .u64 transport_tangent_param_7,
	.param .u64 transport_tangent_param_8,
	.param .u32 transport_tangent_param_9
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<33>;
	.reg .b32 	%r<16>;
	.reg .b64 	%rd<36>;


	ld.param.u64 	%rd1, [transport_tangent_param_0];
	ld.param.u64 	%rd2, [transport_tangent_param_1];
	ld.param.u64 	%rd3, [transport_tangent_param_2];
	ld.param.u64 	%rd4, [transport_tangent_param_3];
	ld.param.u64 	%rd5, [transport_tangent_param_4];
	ld.param.u64 	%rd6, [transport_tangent_param_5];
	ld.param.u64 	%rd7, [transport_tangent_param_6];
	ld.param.u64 	%rd8, [transport_tangent_param_7];
	ld.param.u64 	%rd9, [transport_tangent_param_8];
	ld.param.u32 	%r2, [transport_tangent_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f30, [%rd12];
	cvta.to.global.u64 	%rd13, %rd2;
	add.s64 	%rd14, %rd13, %rd11;
	ld.global.f32 	%f31, [%rd14];
	cvta.to.global.u64 	%rd15, %rd3;
	add.s64 	%rd16, %rd15, %rd11;
	ld.global.f32 	%f32, [%rd16];
	cvta.to.global.u64 	%rd17, %rd4;
	add.s64 	%rd18, %rd17, %rd11;
	cvta.to.global.u64 	%rd19, %rd5;
	add.s64 	%rd20, %rd19, %rd11;
	cvta.to.global.u64 	%rd21, %rd6;
	add.s64 	%rd22, %rd21, %rd11;
	cvta.to.global.u64 	%rd23, %rd7;
	add.s64 	%rd24, %rd23, %rd11;
	cvta.to.global.u64 	%rd25, %rd8;
	add.s64 	%rd26, %rd25, %rd11;
	cvta.to.global.u64 	%rd27, %rd9;
	add.s64 	%rd28, %rd27, %rd11;
	ld.global.nc.f32 	%f4, [%rd24];
	ld.global.nc.f32 	%f5, [%rd18];
	ld.global.nc.f32 	%f6, [%rd26];
	ld.global.nc.f32 	%f7, [%rd20];
	mul.f32 	%f17, %f7, %f6;
	fma.rn.f32 	%f18, %f5, %f4, %f17;
	ld.global.nc.f32 	%f8, [%rd28];
	ld.global.nc.f32 	%f9, [%rd22];
	fma.rn.f32 	%f19, %f9, %f8, %f18;
	add.f32 	%f10, %f19, 0f3F800000;
	setp.leu.f32 	%p2, %f10, 0f2B8CBCCC;
	@%p2 bra 	$L__BB0_3;

	mul.f32 	%f20, %f31, %f6;
	fma.rn.f32 	%f21, %f30, %f4, %f20;
	fma.rn.f32 	%f22, %f32, %f8, %f21;
	div.rn.f32 	%f23, %f22, %f10;
	add.f32 	%f24, %f5, %f4;
	mul.f32 	%f25, %f24, %f23;
	add.f32 	%f26, %f7, %f6;
	mul.f32 	%f27, %f26, %f23;
	add.f32 	%f28, %f9, %f8;
	mul.f32 	%f29, %f28, %f23;
	sub.f32 	%f30, %f30, %f25;
	sub.f32 	%f31, %f31, %f27;
	sub.f32 	%f32, %f32, %f29;

$L__BB0_3:
	st.global.f32 	[%rd12], %f30;
	st.global.f32 	[%rd14], %f31;
	st.global.f32 	[%rd16], %f32;

$L__BB0_4:
	ret;

}

`
 )
